pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh '''#!/bin/bash

                    source ~/emsdk/emsdk_env.sh
                    cd project/emscripten
                    sh buildjs.sh
                '''           
            }
        }
    }
}