pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                source ~/emsdk/emsdk_env.sh
                cd project/emscripten
                sh buildjs.sh
            }
        }
    }
}