/* Build with the Windows SDK: cl buildProbeShaders.c /link d3dcompiler.lib
 * Run: buildProbeShaders.exe d3d11ProbeShaders.h
 * Keep shader compilation outside the probe: Wine's compiler does not yet
 * implement all structured-buffer operations exercised here.
 */
#define COBJMACROS
#include <windows.h>
#include <d3dcompiler.h>
#include <stdio.h>
#include <string.h>

int main(int argc, char** argv)
{
    const char* names[] = {"probeVS", "probePS", "probeCS"};
    const char* targets[] = {"vs_5_0", "ps_5_0", "cs_5_0"};
    const char* sources[] = {
        "float4 main(uint id:SV_VertexID):SV_Position { return float4(id==2?3:-1,id==1?3:-1,0,1); }",
        "float4 main():SV_Target { return float4(0,1,1,1); }",
        "RWStructuredBuffer<uint> result:register(u0); [numthreads(32,1,1)] "
        "void main(uint3 id:SV_DispatchThreadID) { result[id.x]=0x12345678^(id.x*79); }"
    };
    if (argc != 2) return 1;
    FILE* output = fopen(argv[1], "wb");
    if (!output) return 1;
    fputs("/* Generated by buildProbeShaders.c using D3DCompile. */\n#pragma once\n", output);
    for (unsigned i = 0; i < 3; ++i) {
        ID3DBlob *blob = NULL, *errors = NULL;
        HRESULT result = D3DCompile(sources[i], strlen(sources[i]), NULL, NULL, NULL,
            "main", targets[i], D3DCOMPILE_ENABLE_STRICTNESS, 0, &blob, &errors);
        if (FAILED(result)) {
            fprintf(stderr, "%s: %s\n", names[i], errors ? (char*)ID3D10Blob_GetBufferPointer(errors) : "compile failed");
            if (errors) ID3D10Blob_Release(errors);
            fclose(output);
            return 1;
        }
        if (errors) ID3D10Blob_Release(errors);
        fprintf(output, "static const DWORD %s[] = {\n", names[i]);
        const DWORD* data = ID3D10Blob_GetBufferPointer(blob);
        size_t count = ID3D10Blob_GetBufferSize(blob) / sizeof(*data);
        for (size_t word = 0; word < count; ++word)
            fprintf(output, "0x%08lx,%s", (unsigned long)data[word], word % 8 == 7 || word + 1 == count ? "\n" : " ");
        fputs("};\n", output);
        ID3D10Blob_Release(blob);
    }
    return fclose(output) != 0;
}
