pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               sh '''#!/bin/bash

                    cd project/linux
                    sh build.sh || exit
                '''           
            }
        }
        stage('Build x64 Core') {
            steps {
               sh '''#!/bin/bash

                    cd project/linux
                    sh build64.sh || exit
                '''           
            }
        }
        stage('Test') {
            steps {
                sh '''#!/bin/bash
                    cd project/linux
                    sh buildtest.sh || exit
                    ./bin/boxedwineTest || exit 
                '''
            }
        }
    }
}