#ifndef __VK_HOST__H__
#define __VK_HOST__H__
#define VK_NO_PROTOTYPES
#include "vk/vulkan.h"
#include "vk/vulkan_core.h"
#ifndef BOXED_VK_EXTERN
#define BOXED_VK_EXTERN extern
#endif
class BoxedVulkanInfo;
VkBaseOutStructure* vulkanGetNextPtr(BoxedVulkanInfo* pBoxedInfo, KMemory* memory, U32 address);
void vulkanWriteNextPtr(BoxedVulkanInfo* pBoxedInfo, KMemory* memory, U32 address, const void* pNext);
void* getVulkanPtr(KMemory* memory, U32 address);
BOXED_VK_EXTERN PFN_vkCreateInstance pvkCreateInstance;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceVersion pvkEnumerateInstanceVersion;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceLayerProperties pvkEnumerateInstanceLayerProperties;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceExtensionProperties pvkEnumerateInstanceExtensionProperties;
void vk_CreateInstance(CPU* cpu);
void vk_DestroyInstance(CPU* cpu);
void vk_EnumeratePhysicalDevices(CPU* cpu);
void vk_GetDeviceProcAddr(CPU* cpu);
void vk_GetInstanceProcAddr(CPU* cpu);
void vk_GetPhysicalDeviceProperties(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties(CPU* cpu);
void vk_GetPhysicalDeviceFeatures(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties(CPU* cpu);
void vk_CreateDevice(CPU* cpu);
void vk_DestroyDevice(CPU* cpu);
void vk_EnumerateInstanceVersion(CPU* cpu);
void vk_EnumerateInstanceLayerProperties(CPU* cpu);
void vk_EnumerateInstanceExtensionProperties(CPU* cpu);
void vk_EnumerateDeviceLayerProperties(CPU* cpu);
void vk_EnumerateDeviceExtensionProperties(CPU* cpu);
void vk_GetDeviceQueue(CPU* cpu);
void vk_QueueSubmit(CPU* cpu);
void vk_QueueWaitIdle(CPU* cpu);
void vk_DeviceWaitIdle(CPU* cpu);
void vk_AllocateMemory(CPU* cpu);
void vk_FreeMemory(CPU* cpu);
void vk_MapMemory(CPU* cpu);
void vk_UnmapMemory(CPU* cpu);
void vk_FlushMappedMemoryRanges(CPU* cpu);
void vk_InvalidateMappedMemoryRanges(CPU* cpu);
void vk_GetDeviceMemoryCommitment(CPU* cpu);
void vk_GetBufferMemoryRequirements(CPU* cpu);
void vk_BindBufferMemory(CPU* cpu);
void vk_GetImageMemoryRequirements(CPU* cpu);
void vk_BindImageMemory(CPU* cpu);
void vk_GetImageSparseMemoryRequirements(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties(CPU* cpu);
void vk_QueueBindSparse(CPU* cpu);
void vk_CreateFence(CPU* cpu);
void vk_DestroyFence(CPU* cpu);
void vk_ResetFences(CPU* cpu);
void vk_GetFenceStatus(CPU* cpu);
void vk_WaitForFences(CPU* cpu);
void vk_CreateSemaphore(CPU* cpu);
void vk_DestroySemaphore(CPU* cpu);
void vk_CreateEvent(CPU* cpu);
void vk_DestroyEvent(CPU* cpu);
void vk_GetEventStatus(CPU* cpu);
void vk_SetEvent(CPU* cpu);
void vk_ResetEvent(CPU* cpu);
void vk_CreateQueryPool(CPU* cpu);
void vk_DestroyQueryPool(CPU* cpu);
void vk_GetQueryPoolResults(CPU* cpu);
void vk_ResetQueryPool(CPU* cpu);
void vk_ResetQueryPoolEXT(CPU* cpu);
void vk_CreateBuffer(CPU* cpu);
void vk_DestroyBuffer(CPU* cpu);
void vk_CreateBufferView(CPU* cpu);
void vk_DestroyBufferView(CPU* cpu);
void vk_CreateImage(CPU* cpu);
void vk_DestroyImage(CPU* cpu);
void vk_GetImageSubresourceLayout(CPU* cpu);
void vk_CreateImageView(CPU* cpu);
void vk_DestroyImageView(CPU* cpu);
void vk_CreateShaderModule(CPU* cpu);
void vk_DestroyShaderModule(CPU* cpu);
void vk_CreatePipelineCache(CPU* cpu);
void vk_DestroyPipelineCache(CPU* cpu);
void vk_GetPipelineCacheData(CPU* cpu);
void vk_MergePipelineCaches(CPU* cpu);
void vk_CreatePipelineBinariesKHR(CPU* cpu);
void vk_DestroyPipelineBinaryKHR(CPU* cpu);
void vk_GetPipelineKeyKHR(CPU* cpu);
void vk_GetPipelineBinaryDataKHR(CPU* cpu);
void vk_ReleaseCapturedPipelineDataKHR(CPU* cpu);
void vk_CreateGraphicsPipelines(CPU* cpu);
void vk_CreateComputePipelines(CPU* cpu);
void vk_GetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI(CPU* cpu);
void vk_DestroyPipeline(CPU* cpu);
void vk_CreatePipelineLayout(CPU* cpu);
void vk_DestroyPipelineLayout(CPU* cpu);
void vk_CreateSampler(CPU* cpu);
void vk_DestroySampler(CPU* cpu);
void vk_CreateDescriptorSetLayout(CPU* cpu);
void vk_DestroyDescriptorSetLayout(CPU* cpu);
void vk_CreateDescriptorPool(CPU* cpu);
void vk_DestroyDescriptorPool(CPU* cpu);
void vk_ResetDescriptorPool(CPU* cpu);
void vk_AllocateDescriptorSets(CPU* cpu);
void vk_FreeDescriptorSets(CPU* cpu);
void vk_UpdateDescriptorSets(CPU* cpu);
void vk_CreateFramebuffer(CPU* cpu);
void vk_DestroyFramebuffer(CPU* cpu);
void vk_CreateRenderPass(CPU* cpu);
void vk_DestroyRenderPass(CPU* cpu);
void vk_GetRenderAreaGranularity(CPU* cpu);
void vk_GetRenderingAreaGranularity(CPU* cpu);
void vk_GetRenderingAreaGranularityKHR(CPU* cpu);
void vk_CreateCommandPool(CPU* cpu);
void vk_DestroyCommandPool(CPU* cpu);
void vk_ResetCommandPool(CPU* cpu);
void vk_AllocateCommandBuffers(CPU* cpu);
void vk_FreeCommandBuffers(CPU* cpu);
void vk_BeginCommandBuffer(CPU* cpu);
void vk_EndCommandBuffer(CPU* cpu);
void vk_ResetCommandBuffer(CPU* cpu);
void vk_CmdBindPipeline(CPU* cpu);
void vk_CmdSetAttachmentFeedbackLoopEnableEXT(CPU* cpu);
void vk_CmdSetViewport(CPU* cpu);
void vk_CmdSetScissor(CPU* cpu);
void vk_CmdSetLineWidth(CPU* cpu);
void vk_CmdSetDepthBias(CPU* cpu);
void vk_CmdSetBlendConstants(CPU* cpu);
void vk_CmdSetDepthBounds(CPU* cpu);
void vk_CmdSetStencilCompareMask(CPU* cpu);
void vk_CmdSetStencilWriteMask(CPU* cpu);
void vk_CmdSetStencilReference(CPU* cpu);
void vk_CmdBindDescriptorSets(CPU* cpu);
void vk_CmdBindIndexBuffer(CPU* cpu);
void vk_CmdBindVertexBuffers(CPU* cpu);
void vk_CmdDraw(CPU* cpu);
void vk_CmdDrawIndexed(CPU* cpu);
void vk_CmdDrawMultiEXT(CPU* cpu);
void vk_CmdDrawMultiIndexedEXT(CPU* cpu);
void vk_CmdDrawIndirect(CPU* cpu);
void vk_CmdDrawIndexedIndirect(CPU* cpu);
void vk_CmdDispatch(CPU* cpu);
void vk_CmdDispatchIndirect(CPU* cpu);
void vk_CmdSubpassShadingHUAWEI(CPU* cpu);
void vk_CmdDrawClusterHUAWEI(CPU* cpu);
void vk_CmdDrawClusterIndirectHUAWEI(CPU* cpu);
void vk_CmdUpdatePipelineIndirectBufferNV(CPU* cpu);
void vk_CmdCopyBuffer(CPU* cpu);
void vk_CmdCopyImage(CPU* cpu);
void vk_CmdBlitImage(CPU* cpu);
void vk_CmdCopyBufferToImage(CPU* cpu);
void vk_CmdCopyImageToBuffer(CPU* cpu);
void vk_CmdCopyMemoryIndirectNV(CPU* cpu);
void vk_CmdCopyMemoryToImageIndirectNV(CPU* cpu);
void vk_CmdUpdateBuffer(CPU* cpu);
void vk_CmdFillBuffer(CPU* cpu);
void vk_CmdClearColorImage(CPU* cpu);
void vk_CmdClearDepthStencilImage(CPU* cpu);
void vk_CmdClearAttachments(CPU* cpu);
void vk_CmdResolveImage(CPU* cpu);
void vk_CmdSetEvent(CPU* cpu);
void vk_CmdResetEvent(CPU* cpu);
void vk_CmdWaitEvents(CPU* cpu);
void vk_CmdPipelineBarrier(CPU* cpu);
void vk_CmdBeginQuery(CPU* cpu);
void vk_CmdEndQuery(CPU* cpu);
void vk_CmdBeginConditionalRenderingEXT(CPU* cpu);
void vk_CmdEndConditionalRenderingEXT(CPU* cpu);
void vk_CmdResetQueryPool(CPU* cpu);
void vk_CmdWriteTimestamp(CPU* cpu);
void vk_CmdCopyQueryPoolResults(CPU* cpu);
void vk_CmdPushConstants(CPU* cpu);
void vk_CmdBeginRenderPass(CPU* cpu);
void vk_CmdNextSubpass(CPU* cpu);
void vk_CmdEndRenderPass(CPU* cpu);
void vk_CmdExecuteCommands(CPU* cpu);
void vk_CreateSharedSwapchainsKHR(CPU* cpu);
void vk_DestroySurfaceKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceSupportKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceCapabilitiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceFormatsKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfacePresentModesKHR(CPU* cpu);
void vk_CreateSwapchainKHR(CPU* cpu);
void vk_DestroySwapchainKHR(CPU* cpu);
void vk_GetSwapchainImagesKHR(CPU* cpu);
void vk_AcquireNextImageKHR(CPU* cpu);
void vk_QueuePresentKHR(CPU* cpu);
void vk_CreateXlibSurfaceKHR(CPU* cpu);
void vk_GetPhysicalDeviceXlibPresentationSupportKHR(CPU* cpu);
void vk_CreateDebugReportCallbackEXT(CPU* cpu);
void vk_DestroyDebugReportCallbackEXT(CPU* cpu);
void vk_DebugReportMessageEXT(CPU* cpu);
void vk_DebugMarkerSetObjectNameEXT(CPU* cpu);
void vk_DebugMarkerSetObjectTagEXT(CPU* cpu);
void vk_CmdDebugMarkerBeginEXT(CPU* cpu);
void vk_CmdDebugMarkerEndEXT(CPU* cpu);
void vk_CmdDebugMarkerInsertEXT(CPU* cpu);
void vk_CmdExecuteGeneratedCommandsNV(CPU* cpu);
void vk_CmdPreprocessGeneratedCommandsNV(CPU* cpu);
void vk_CmdBindPipelineShaderGroupNV(CPU* cpu);
void vk_GetGeneratedCommandsMemoryRequirementsNV(CPU* cpu);
void vk_CreateIndirectCommandsLayoutNV(CPU* cpu);
void vk_DestroyIndirectCommandsLayoutNV(CPU* cpu);
void vk_CmdExecuteGeneratedCommandsEXT(CPU* cpu);
void vk_CmdPreprocessGeneratedCommandsEXT(CPU* cpu);
void vk_GetGeneratedCommandsMemoryRequirementsEXT(CPU* cpu);
void vk_CreateIndirectCommandsLayoutEXT(CPU* cpu);
void vk_DestroyIndirectCommandsLayoutEXT(CPU* cpu);
void vk_CreateIndirectExecutionSetEXT(CPU* cpu);
void vk_DestroyIndirectExecutionSetEXT(CPU* cpu);
void vk_UpdateIndirectExecutionSetPipelineEXT(CPU* cpu);
void vk_UpdateIndirectExecutionSetShaderEXT(CPU* cpu);
void vk_GetPhysicalDeviceFeatures2(CPU* cpu);
void vk_GetPhysicalDeviceFeatures2KHR(CPU* cpu);
void vk_GetPhysicalDeviceProperties2(CPU* cpu);
void vk_GetPhysicalDeviceProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties2(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties2(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties2KHR(CPU* cpu);
void vk_CmdPushDescriptorSet(CPU* cpu);
void vk_CmdPushDescriptorSetKHR(CPU* cpu);
void vk_TrimCommandPool(CPU* cpu);
void vk_TrimCommandPoolKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalBufferProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalBufferPropertiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalSemaphoreProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalSemaphorePropertiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalFenceProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalFencePropertiesKHR(CPU* cpu);
void vk_ReleaseDisplayEXT(CPU* cpu);
void vk_DisplayPowerControlEXT(CPU* cpu);
void vk_RegisterDeviceEventEXT(CPU* cpu);
void vk_RegisterDisplayEventEXT(CPU* cpu);
void vk_GetSwapchainCounterEXT(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceCapabilities2EXT(CPU* cpu);
void vk_EnumeratePhysicalDeviceGroups(CPU* cpu);
void vk_EnumeratePhysicalDeviceGroupsKHR(CPU* cpu);
void vk_GetDeviceGroupPeerMemoryFeatures(CPU* cpu);
void vk_GetDeviceGroupPeerMemoryFeaturesKHR(CPU* cpu);
void vk_BindBufferMemory2(CPU* cpu);
void vk_BindBufferMemory2KHR(CPU* cpu);
void vk_BindImageMemory2(CPU* cpu);
void vk_BindImageMemory2KHR(CPU* cpu);
void vk_CmdSetDeviceMask(CPU* cpu);
void vk_CmdSetDeviceMaskKHR(CPU* cpu);
void vk_GetDeviceGroupPresentCapabilitiesKHR(CPU* cpu);
void vk_GetDeviceGroupSurfacePresentModesKHR(CPU* cpu);
void vk_AcquireNextImage2KHR(CPU* cpu);
void vk_CmdDispatchBase(CPU* cpu);
void vk_CmdDispatchBaseKHR(CPU* cpu);
void vk_GetPhysicalDevicePresentRectanglesKHR(CPU* cpu);
void vk_CreateDescriptorUpdateTemplate(CPU* cpu);
void vk_CreateDescriptorUpdateTemplateKHR(CPU* cpu);
void vk_DestroyDescriptorUpdateTemplate(CPU* cpu);
void vk_DestroyDescriptorUpdateTemplateKHR(CPU* cpu);
void vk_UpdateDescriptorSetWithTemplate(CPU* cpu);
void vk_UpdateDescriptorSetWithTemplateKHR(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplate(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplateKHR(CPU* cpu);
void vk_SetHdrMetadataEXT(CPU* cpu);
void vk_CmdSetViewportWScalingNV(CPU* cpu);
void vk_CmdSetDiscardRectangleEXT(CPU* cpu);
void vk_CmdSetDiscardRectangleEnableEXT(CPU* cpu);
void vk_CmdSetDiscardRectangleModeEXT(CPU* cpu);
void vk_CmdSetSampleLocationsEXT(CPU* cpu);
void vk_GetPhysicalDeviceMultisamplePropertiesEXT(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceCapabilities2KHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceFormats2KHR(CPU* cpu);
void vk_GetPhysicalDeviceDisplayProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceDisplayPlaneProperties2KHR(CPU* cpu);
void vk_GetDisplayModeProperties2KHR(CPU* cpu);
void vk_GetDisplayPlaneCapabilities2KHR(CPU* cpu);
void vk_GetBufferMemoryRequirements2(CPU* cpu);
void vk_GetBufferMemoryRequirements2KHR(CPU* cpu);
void vk_GetImageMemoryRequirements2(CPU* cpu);
void vk_GetImageMemoryRequirements2KHR(CPU* cpu);
void vk_GetImageSparseMemoryRequirements2(CPU* cpu);
void vk_GetImageSparseMemoryRequirements2KHR(CPU* cpu);
void vk_GetDeviceBufferMemoryRequirements(CPU* cpu);
void vk_GetDeviceBufferMemoryRequirementsKHR(CPU* cpu);
void vk_GetDeviceImageMemoryRequirements(CPU* cpu);
void vk_GetDeviceImageMemoryRequirementsKHR(CPU* cpu);
void vk_GetDeviceImageSparseMemoryRequirements(CPU* cpu);
void vk_GetDeviceImageSparseMemoryRequirementsKHR(CPU* cpu);
void vk_CreateSamplerYcbcrConversion(CPU* cpu);
void vk_CreateSamplerYcbcrConversionKHR(CPU* cpu);
void vk_DestroySamplerYcbcrConversion(CPU* cpu);
void vk_DestroySamplerYcbcrConversionKHR(CPU* cpu);
void vk_GetDeviceQueue2(CPU* cpu);
void vk_CreateValidationCacheEXT(CPU* cpu);
void vk_DestroyValidationCacheEXT(CPU* cpu);
void vk_GetValidationCacheDataEXT(CPU* cpu);
void vk_MergeValidationCachesEXT(CPU* cpu);
void vk_GetDescriptorSetLayoutSupport(CPU* cpu);
void vk_GetDescriptorSetLayoutSupportKHR(CPU* cpu);
void vk_GetShaderInfoAMD(CPU* cpu);
void vk_GetPhysicalDeviceCalibrateableTimeDomainsKHR(CPU* cpu);
void vk_GetPhysicalDeviceCalibrateableTimeDomainsEXT(CPU* cpu);
void vk_GetCalibratedTimestampsKHR(CPU* cpu);
void vk_GetCalibratedTimestampsEXT(CPU* cpu);
void vk_SetDebugUtilsObjectNameEXT(CPU* cpu);
void vk_SetDebugUtilsObjectTagEXT(CPU* cpu);
void vk_QueueBeginDebugUtilsLabelEXT(CPU* cpu);
void vk_QueueEndDebugUtilsLabelEXT(CPU* cpu);
void vk_QueueInsertDebugUtilsLabelEXT(CPU* cpu);
void vk_CmdBeginDebugUtilsLabelEXT(CPU* cpu);
void vk_CmdEndDebugUtilsLabelEXT(CPU* cpu);
void vk_CmdInsertDebugUtilsLabelEXT(CPU* cpu);
void vk_CreateDebugUtilsMessengerEXT(CPU* cpu);
void vk_DestroyDebugUtilsMessengerEXT(CPU* cpu);
void vk_SubmitDebugUtilsMessageEXT(CPU* cpu);
void vk_GetMemoryHostPointerPropertiesEXT(CPU* cpu);
void vk_CmdWriteBufferMarkerAMD(CPU* cpu);
void vk_CreateRenderPass2(CPU* cpu);
void vk_CreateRenderPass2KHR(CPU* cpu);
void vk_CmdBeginRenderPass2(CPU* cpu);
void vk_CmdBeginRenderPass2KHR(CPU* cpu);
void vk_CmdNextSubpass2(CPU* cpu);
void vk_CmdNextSubpass2KHR(CPU* cpu);
void vk_CmdEndRenderPass2(CPU* cpu);
void vk_CmdEndRenderPass2KHR(CPU* cpu);
void vk_GetSemaphoreCounterValue(CPU* cpu);
void vk_GetSemaphoreCounterValueKHR(CPU* cpu);
void vk_WaitSemaphores(CPU* cpu);
void vk_WaitSemaphoresKHR(CPU* cpu);
void vk_SignalSemaphore(CPU* cpu);
void vk_SignalSemaphoreKHR(CPU* cpu);
void vk_CmdDrawIndirectCount(CPU* cpu);
void vk_CmdDrawIndirectCountKHR(CPU* cpu);
void vk_CmdDrawIndirectCountAMD(CPU* cpu);
void vk_CmdDrawIndexedIndirectCount(CPU* cpu);
void vk_CmdDrawIndexedIndirectCountKHR(CPU* cpu);
void vk_CmdDrawIndexedIndirectCountAMD(CPU* cpu);
void vk_CmdSetCheckpointNV(CPU* cpu);
void vk_GetQueueCheckpointDataNV(CPU* cpu);
void vk_CmdBindTransformFeedbackBuffersEXT(CPU* cpu);
void vk_CmdBeginTransformFeedbackEXT(CPU* cpu);
void vk_CmdEndTransformFeedbackEXT(CPU* cpu);
void vk_CmdBeginQueryIndexedEXT(CPU* cpu);
void vk_CmdEndQueryIndexedEXT(CPU* cpu);
void vk_CmdDrawIndirectByteCountEXT(CPU* cpu);
void vk_CmdSetExclusiveScissorNV(CPU* cpu);
void vk_CmdSetExclusiveScissorEnableNV(CPU* cpu);
void vk_CmdBindShadingRateImageNV(CPU* cpu);
void vk_CmdSetViewportShadingRatePaletteNV(CPU* cpu);
void vk_CmdSetCoarseSampleOrderNV(CPU* cpu);
void vk_CmdDrawMeshTasksNV(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectNV(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectCountNV(CPU* cpu);
void vk_CmdDrawMeshTasksEXT(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectEXT(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectCountEXT(CPU* cpu);
void vk_CompileDeferredNV(CPU* cpu);
void vk_CreateAccelerationStructureNV(CPU* cpu);
void vk_CmdBindInvocationMaskHUAWEI(CPU* cpu);
void vk_DestroyAccelerationStructureKHR(CPU* cpu);
void vk_DestroyAccelerationStructureNV(CPU* cpu);
void vk_GetAccelerationStructureMemoryRequirementsNV(CPU* cpu);
void vk_BindAccelerationStructureMemoryNV(CPU* cpu);
void vk_CmdCopyAccelerationStructureNV(CPU* cpu);
void vk_CmdCopyAccelerationStructureKHR(CPU* cpu);
void vk_CopyAccelerationStructureKHR(CPU* cpu);
void vk_CmdCopyAccelerationStructureToMemoryKHR(CPU* cpu);
void vk_CopyAccelerationStructureToMemoryKHR(CPU* cpu);
void vk_CmdCopyMemoryToAccelerationStructureKHR(CPU* cpu);
void vk_CopyMemoryToAccelerationStructureKHR(CPU* cpu);
void vk_CmdWriteAccelerationStructuresPropertiesKHR(CPU* cpu);
void vk_CmdWriteAccelerationStructuresPropertiesNV(CPU* cpu);
void vk_CmdBuildAccelerationStructureNV(CPU* cpu);
void vk_WriteAccelerationStructuresPropertiesKHR(CPU* cpu);
void vk_CmdTraceRaysKHR(CPU* cpu);
void vk_CmdTraceRaysNV(CPU* cpu);
void vk_GetRayTracingShaderGroupHandlesKHR(CPU* cpu);
void vk_GetRayTracingShaderGroupHandlesNV(CPU* cpu);
void vk_GetRayTracingCaptureReplayShaderGroupHandlesKHR(CPU* cpu);
void vk_GetAccelerationStructureHandleNV(CPU* cpu);
void vk_CreateRayTracingPipelinesNV(CPU* cpu);
void vk_CreateRayTracingPipelinesKHR(CPU* cpu);
void vk_GetPhysicalDeviceCooperativeMatrixPropertiesNV(CPU* cpu);
void vk_CmdTraceRaysIndirectKHR(CPU* cpu);
void vk_CmdTraceRaysIndirect2KHR(CPU* cpu);
void vk_GetDeviceAccelerationStructureCompatibilityKHR(CPU* cpu);
void vk_GetRayTracingShaderGroupStackSizeKHR(CPU* cpu);
void vk_CmdSetRayTracingPipelineStackSizeKHR(CPU* cpu);
void vk_GetImageViewHandleNVX(CPU* cpu);
void vk_GetImageViewHandle64NVX(CPU* cpu);
void vk_GetImageViewAddressNVX(CPU* cpu);
void vk_EnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR(CPU* cpu);
void vk_AcquireProfilingLockKHR(CPU* cpu);
void vk_ReleaseProfilingLockKHR(CPU* cpu);
void vk_GetBufferOpaqueCaptureAddress(CPU* cpu);
void vk_GetBufferOpaqueCaptureAddressKHR(CPU* cpu);
void vk_GetBufferDeviceAddress(CPU* cpu);
void vk_GetBufferDeviceAddressKHR(CPU* cpu);
void vk_GetBufferDeviceAddressEXT(CPU* cpu);
void vk_GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV(CPU* cpu);
void vk_InitializePerformanceApiINTEL(CPU* cpu);
void vk_UninitializePerformanceApiINTEL(CPU* cpu);
void vk_CmdSetPerformanceMarkerINTEL(CPU* cpu);
void vk_CmdSetPerformanceStreamMarkerINTEL(CPU* cpu);
void vk_CmdSetPerformanceOverrideINTEL(CPU* cpu);
void vk_AcquirePerformanceConfigurationINTEL(CPU* cpu);
void vk_ReleasePerformanceConfigurationINTEL(CPU* cpu);
void vk_QueueSetPerformanceConfigurationINTEL(CPU* cpu);
void vk_GetPerformanceParameterINTEL(CPU* cpu);
void vk_GetDeviceMemoryOpaqueCaptureAddress(CPU* cpu);
void vk_GetDeviceMemoryOpaqueCaptureAddressKHR(CPU* cpu);
void vk_GetPipelineExecutablePropertiesKHR(CPU* cpu);
void vk_GetPipelineExecutableStatisticsKHR(CPU* cpu);
void vk_GetPipelineExecutableInternalRepresentationsKHR(CPU* cpu);
void vk_CmdSetLineStipple(CPU* cpu);
void vk_CmdSetLineStippleKHR(CPU* cpu);
void vk_CmdSetLineStippleEXT(CPU* cpu);
void vk_GetPhysicalDeviceToolProperties(CPU* cpu);
void vk_GetPhysicalDeviceToolPropertiesEXT(CPU* cpu);
void vk_CreateAccelerationStructureKHR(CPU* cpu);
void vk_CmdBuildAccelerationStructuresKHR(CPU* cpu);
void vk_CmdBuildAccelerationStructuresIndirectKHR(CPU* cpu);
void vk_BuildAccelerationStructuresKHR(CPU* cpu);
void vk_GetAccelerationStructureDeviceAddressKHR(CPU* cpu);
void vk_CreateDeferredOperationKHR(CPU* cpu);
void vk_DestroyDeferredOperationKHR(CPU* cpu);
void vk_GetDeferredOperationMaxConcurrencyKHR(CPU* cpu);
void vk_GetDeferredOperationResultKHR(CPU* cpu);
void vk_DeferredOperationJoinKHR(CPU* cpu);
void vk_GetPipelineIndirectMemoryRequirementsNV(CPU* cpu);
void vk_GetPipelineIndirectDeviceAddressNV(CPU* cpu);
void vk_AntiLagUpdateAMD(CPU* cpu);
void vk_CmdSetCullMode(CPU* cpu);
void vk_CmdSetCullModeEXT(CPU* cpu);
void vk_CmdSetFrontFace(CPU* cpu);
void vk_CmdSetFrontFaceEXT(CPU* cpu);
void vk_CmdSetPrimitiveTopology(CPU* cpu);
void vk_CmdSetPrimitiveTopologyEXT(CPU* cpu);
void vk_CmdSetViewportWithCount(CPU* cpu);
void vk_CmdSetViewportWithCountEXT(CPU* cpu);
void vk_CmdSetScissorWithCount(CPU* cpu);
void vk_CmdSetScissorWithCountEXT(CPU* cpu);
void vk_CmdBindIndexBuffer2(CPU* cpu);
void vk_CmdBindIndexBuffer2KHR(CPU* cpu);
void vk_CmdBindVertexBuffers2(CPU* cpu);
void vk_CmdBindVertexBuffers2EXT(CPU* cpu);
void vk_CmdSetDepthTestEnable(CPU* cpu);
void vk_CmdSetDepthTestEnableEXT(CPU* cpu);
void vk_CmdSetDepthWriteEnable(CPU* cpu);
void vk_CmdSetDepthWriteEnableEXT(CPU* cpu);
void vk_CmdSetDepthCompareOp(CPU* cpu);
void vk_CmdSetDepthCompareOpEXT(CPU* cpu);
void vk_CmdSetDepthBoundsTestEnable(CPU* cpu);
void vk_CmdSetDepthBoundsTestEnableEXT(CPU* cpu);
void vk_CmdSetStencilTestEnable(CPU* cpu);
void vk_CmdSetStencilTestEnableEXT(CPU* cpu);
void vk_CmdSetStencilOp(CPU* cpu);
void vk_CmdSetStencilOpEXT(CPU* cpu);
void vk_CmdSetPatchControlPointsEXT(CPU* cpu);
void vk_CmdSetRasterizerDiscardEnable(CPU* cpu);
void vk_CmdSetRasterizerDiscardEnableEXT(CPU* cpu);
void vk_CmdSetDepthBiasEnable(CPU* cpu);
void vk_CmdSetDepthBiasEnableEXT(CPU* cpu);
void vk_CmdSetLogicOpEXT(CPU* cpu);
void vk_CmdSetPrimitiveRestartEnable(CPU* cpu);
void vk_CmdSetPrimitiveRestartEnableEXT(CPU* cpu);
void vk_CmdSetTessellationDomainOriginEXT(CPU* cpu);
void vk_CmdSetDepthClampEnableEXT(CPU* cpu);
void vk_CmdSetPolygonModeEXT(CPU* cpu);
void vk_CmdSetRasterizationSamplesEXT(CPU* cpu);
void vk_CmdSetSampleMaskEXT(CPU* cpu);
void vk_CmdSetAlphaToCoverageEnableEXT(CPU* cpu);
void vk_CmdSetAlphaToOneEnableEXT(CPU* cpu);
void vk_CmdSetLogicOpEnableEXT(CPU* cpu);
void vk_CmdSetColorBlendEnableEXT(CPU* cpu);
void vk_CmdSetColorBlendEquationEXT(CPU* cpu);
void vk_CmdSetColorWriteMaskEXT(CPU* cpu);
void vk_CmdSetRasterizationStreamEXT(CPU* cpu);
void vk_CmdSetConservativeRasterizationModeEXT(CPU* cpu);
void vk_CmdSetExtraPrimitiveOverestimationSizeEXT(CPU* cpu);
void vk_CmdSetDepthClipEnableEXT(CPU* cpu);
void vk_CmdSetSampleLocationsEnableEXT(CPU* cpu);
void vk_CmdSetColorBlendAdvancedEXT(CPU* cpu);
void vk_CmdSetProvokingVertexModeEXT(CPU* cpu);
void vk_CmdSetLineRasterizationModeEXT(CPU* cpu);
void vk_CmdSetLineStippleEnableEXT(CPU* cpu);
void vk_CmdSetDepthClipNegativeOneToOneEXT(CPU* cpu);
void vk_CmdSetViewportWScalingEnableNV(CPU* cpu);
void vk_CmdSetViewportSwizzleNV(CPU* cpu);
void vk_CmdSetCoverageToColorEnableNV(CPU* cpu);
void vk_CmdSetCoverageToColorLocationNV(CPU* cpu);
void vk_CmdSetCoverageModulationModeNV(CPU* cpu);
void vk_CmdSetCoverageModulationTableEnableNV(CPU* cpu);
void vk_CmdSetCoverageModulationTableNV(CPU* cpu);
void vk_CmdSetShadingRateImageEnableNV(CPU* cpu);
void vk_CmdSetCoverageReductionModeNV(CPU* cpu);
void vk_CmdSetRepresentativeFragmentTestEnableNV(CPU* cpu);
void vk_CreatePrivateDataSlot(CPU* cpu);
void vk_CreatePrivateDataSlotEXT(CPU* cpu);
void vk_DestroyPrivateDataSlot(CPU* cpu);
void vk_DestroyPrivateDataSlotEXT(CPU* cpu);
void vk_SetPrivateData(CPU* cpu);
void vk_SetPrivateDataEXT(CPU* cpu);
void vk_GetPrivateData(CPU* cpu);
void vk_GetPrivateDataEXT(CPU* cpu);
void vk_CmdCopyBuffer2(CPU* cpu);
void vk_CmdCopyBuffer2KHR(CPU* cpu);
void vk_CmdCopyImage2(CPU* cpu);
void vk_CmdCopyImage2KHR(CPU* cpu);
void vk_CmdBlitImage2(CPU* cpu);
void vk_CmdBlitImage2KHR(CPU* cpu);
void vk_CmdCopyBufferToImage2(CPU* cpu);
void vk_CmdCopyBufferToImage2KHR(CPU* cpu);
void vk_CmdCopyImageToBuffer2(CPU* cpu);
void vk_CmdCopyImageToBuffer2KHR(CPU* cpu);
void vk_CmdResolveImage2(CPU* cpu);
void vk_CmdResolveImage2KHR(CPU* cpu);
void vk_CmdSetFragmentShadingRateKHR(CPU* cpu);
void vk_GetPhysicalDeviceFragmentShadingRatesKHR(CPU* cpu);
void vk_CmdSetFragmentShadingRateEnumNV(CPU* cpu);
void vk_GetAccelerationStructureBuildSizesKHR(CPU* cpu);
void vk_CmdSetVertexInputEXT(CPU* cpu);
void vk_CmdSetColorWriteEnableEXT(CPU* cpu);
void vk_CmdSetEvent2(CPU* cpu);
void vk_CmdSetEvent2KHR(CPU* cpu);
void vk_CmdResetEvent2(CPU* cpu);
void vk_CmdResetEvent2KHR(CPU* cpu);
void vk_CmdWaitEvents2(CPU* cpu);
void vk_CmdWaitEvents2KHR(CPU* cpu);
void vk_CmdPipelineBarrier2(CPU* cpu);
void vk_CmdPipelineBarrier2KHR(CPU* cpu);
void vk_QueueSubmit2(CPU* cpu);
void vk_QueueSubmit2KHR(CPU* cpu);
void vk_CmdWriteTimestamp2(CPU* cpu);
void vk_CmdWriteTimestamp2KHR(CPU* cpu);
void vk_CmdWriteBufferMarker2AMD(CPU* cpu);
void vk_GetQueueCheckpointData2NV(CPU* cpu);
void vk_CopyMemoryToImage(CPU* cpu);
void vk_CopyMemoryToImageEXT(CPU* cpu);
void vk_CopyImageToMemory(CPU* cpu);
void vk_CopyImageToMemoryEXT(CPU* cpu);
void vk_CopyImageToImage(CPU* cpu);
void vk_CopyImageToImageEXT(CPU* cpu);
void vk_TransitionImageLayout(CPU* cpu);
void vk_TransitionImageLayoutEXT(CPU* cpu);
void vk_GetPhysicalDeviceVideoCapabilitiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceVideoFormatPropertiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR(CPU* cpu);
void vk_CreateVideoSessionKHR(CPU* cpu);
void vk_DestroyVideoSessionKHR(CPU* cpu);
void vk_CreateVideoSessionParametersKHR(CPU* cpu);
void vk_UpdateVideoSessionParametersKHR(CPU* cpu);
void vk_GetEncodedVideoSessionParametersKHR(CPU* cpu);
void vk_DestroyVideoSessionParametersKHR(CPU* cpu);
void vk_GetVideoSessionMemoryRequirementsKHR(CPU* cpu);
void vk_BindVideoSessionMemoryKHR(CPU* cpu);
void vk_CmdDecodeVideoKHR(CPU* cpu);
void vk_CmdBeginVideoCodingKHR(CPU* cpu);
void vk_CmdControlVideoCodingKHR(CPU* cpu);
void vk_CmdEndVideoCodingKHR(CPU* cpu);
void vk_CmdEncodeVideoKHR(CPU* cpu);
void vk_CmdDecompressMemoryNV(CPU* cpu);
void vk_CmdDecompressMemoryIndirectCountNV(CPU* cpu);
void vk_CreateCuModuleNVX(CPU* cpu);
void vk_CreateCuFunctionNVX(CPU* cpu);
void vk_DestroyCuModuleNVX(CPU* cpu);
void vk_DestroyCuFunctionNVX(CPU* cpu);
void vk_CmdCuLaunchKernelNVX(CPU* cpu);
void vk_GetDescriptorSetLayoutSizeEXT(CPU* cpu);
void vk_GetDescriptorSetLayoutBindingOffsetEXT(CPU* cpu);
void vk_GetDescriptorEXT(CPU* cpu);
void vk_CmdBindDescriptorBuffersEXT(CPU* cpu);
void vk_CmdSetDescriptorBufferOffsetsEXT(CPU* cpu);
void vk_CmdBindDescriptorBufferEmbeddedSamplersEXT(CPU* cpu);
void vk_GetBufferOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_GetImageOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_GetImageViewOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_GetSamplerOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_GetAccelerationStructureOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_SetDeviceMemoryPriorityEXT(CPU* cpu);
void vk_AcquireDrmDisplayEXT(CPU* cpu);
void vk_GetDrmDisplayEXT(CPU* cpu);
void vk_WaitForPresentKHR(CPU* cpu);
void vk_CreateCudaModuleNV(CPU* cpu);
void vk_GetCudaModuleCacheNV(CPU* cpu);
void vk_CreateCudaFunctionNV(CPU* cpu);
void vk_DestroyCudaModuleNV(CPU* cpu);
void vk_DestroyCudaFunctionNV(CPU* cpu);
void vk_CmdCudaLaunchKernelNV(CPU* cpu);
void vk_CmdBeginRendering(CPU* cpu);
void vk_CmdBeginRenderingKHR(CPU* cpu);
void vk_CmdEndRendering(CPU* cpu);
void vk_CmdEndRenderingKHR(CPU* cpu);
void vk_GetDescriptorSetLayoutHostMappingInfoVALVE(CPU* cpu);
void vk_GetDescriptorSetHostMappingVALVE(CPU* cpu);
void vk_CreateMicromapEXT(CPU* cpu);
void vk_CmdBuildMicromapsEXT(CPU* cpu);
void vk_BuildMicromapsEXT(CPU* cpu);
void vk_DestroyMicromapEXT(CPU* cpu);
void vk_CmdCopyMicromapEXT(CPU* cpu);
void vk_CopyMicromapEXT(CPU* cpu);
void vk_CmdCopyMicromapToMemoryEXT(CPU* cpu);
void vk_CopyMicromapToMemoryEXT(CPU* cpu);
void vk_CmdCopyMemoryToMicromapEXT(CPU* cpu);
void vk_CopyMemoryToMicromapEXT(CPU* cpu);
void vk_CmdWriteMicromapsPropertiesEXT(CPU* cpu);
void vk_WriteMicromapsPropertiesEXT(CPU* cpu);
void vk_GetDeviceMicromapCompatibilityEXT(CPU* cpu);
void vk_GetMicromapBuildSizesEXT(CPU* cpu);
void vk_GetShaderModuleIdentifierEXT(CPU* cpu);
void vk_GetShaderModuleCreateInfoIdentifierEXT(CPU* cpu);
void vk_GetImageSubresourceLayout2(CPU* cpu);
void vk_GetImageSubresourceLayout2KHR(CPU* cpu);
void vk_GetImageSubresourceLayout2EXT(CPU* cpu);
void vk_GetPipelinePropertiesEXT(CPU* cpu);
void vk_GetFramebufferTilePropertiesQCOM(CPU* cpu);
void vk_GetDynamicRenderingTilePropertiesQCOM(CPU* cpu);
void vk_GetPhysicalDeviceOpticalFlowImageFormatsNV(CPU* cpu);
void vk_CreateOpticalFlowSessionNV(CPU* cpu);
void vk_DestroyOpticalFlowSessionNV(CPU* cpu);
void vk_BindOpticalFlowSessionImageNV(CPU* cpu);
void vk_CmdOpticalFlowExecuteNV(CPU* cpu);
void vk_GetDeviceFaultInfoEXT(CPU* cpu);
void vk_CmdSetDepthBias2EXT(CPU* cpu);
void vk_ReleaseSwapchainImagesEXT(CPU* cpu);
void vk_GetDeviceImageSubresourceLayout(CPU* cpu);
void vk_GetDeviceImageSubresourceLayoutKHR(CPU* cpu);
void vk_MapMemory2(CPU* cpu);
void vk_MapMemory2KHR(CPU* cpu);
void vk_UnmapMemory2(CPU* cpu);
void vk_UnmapMemory2KHR(CPU* cpu);
void vk_CreateShadersEXT(CPU* cpu);
void vk_DestroyShaderEXT(CPU* cpu);
void vk_GetShaderBinaryDataEXT(CPU* cpu);
void vk_CmdBindShadersEXT(CPU* cpu);
void vk_GetPhysicalDeviceCooperativeMatrixPropertiesKHR(CPU* cpu);
void vk_CmdBindDescriptorSets2(CPU* cpu);
void vk_CmdBindDescriptorSets2KHR(CPU* cpu);
void vk_CmdPushConstants2(CPU* cpu);
void vk_CmdPushConstants2KHR(CPU* cpu);
void vk_CmdPushDescriptorSet2(CPU* cpu);
void vk_CmdPushDescriptorSet2KHR(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplate2(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplate2KHR(CPU* cpu);
void vk_CmdSetDescriptorBufferOffsets2EXT(CPU* cpu);
void vk_CmdBindDescriptorBufferEmbeddedSamplers2EXT(CPU* cpu);
void vk_SetLatencySleepModeNV(CPU* cpu);
void vk_LatencySleepNV(CPU* cpu);
void vk_SetLatencyMarkerNV(CPU* cpu);
void vk_GetLatencyTimingsNV(CPU* cpu);
void vk_QueueNotifyOutOfBandNV(CPU* cpu);
void vk_CmdSetRenderingAttachmentLocations(CPU* cpu);
void vk_CmdSetRenderingAttachmentLocationsKHR(CPU* cpu);
void vk_CmdSetRenderingInputAttachmentIndices(CPU* cpu);
void vk_CmdSetRenderingInputAttachmentIndicesKHR(CPU* cpu);
void vk_CmdSetDepthClampRangeEXT(CPU* cpu);
void vk_GetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV(CPU* cpu);
class BoxedVulkanInfo {
public:
    VkInstance instance;
    PFN_vkDestroyInstance pvkDestroyInstance;
    PFN_vkEnumeratePhysicalDevices pvkEnumeratePhysicalDevices;
    PFN_vkGetPhysicalDeviceProperties pvkGetPhysicalDeviceProperties;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties pvkGetPhysicalDeviceQueueFamilyProperties;
    PFN_vkGetPhysicalDeviceMemoryProperties pvkGetPhysicalDeviceMemoryProperties;
    PFN_vkGetPhysicalDeviceFeatures pvkGetPhysicalDeviceFeatures;
    PFN_vkGetPhysicalDeviceFormatProperties pvkGetPhysicalDeviceFormatProperties;
    PFN_vkGetPhysicalDeviceImageFormatProperties pvkGetPhysicalDeviceImageFormatProperties;
    PFN_vkCreateDevice pvkCreateDevice;
    PFN_vkDestroyDevice pvkDestroyDevice;
    PFN_vkEnumerateDeviceLayerProperties pvkEnumerateDeviceLayerProperties;
    PFN_vkEnumerateDeviceExtensionProperties pvkEnumerateDeviceExtensionProperties;
    PFN_vkGetDeviceQueue pvkGetDeviceQueue;
    PFN_vkQueueSubmit pvkQueueSubmit;
    PFN_vkQueueWaitIdle pvkQueueWaitIdle;
    PFN_vkDeviceWaitIdle pvkDeviceWaitIdle;
    PFN_vkAllocateMemory pvkAllocateMemory;
    PFN_vkFreeMemory pvkFreeMemory;
    PFN_vkMapMemory pvkMapMemory;
    PFN_vkUnmapMemory pvkUnmapMemory;
    PFN_vkFlushMappedMemoryRanges pvkFlushMappedMemoryRanges;
    PFN_vkInvalidateMappedMemoryRanges pvkInvalidateMappedMemoryRanges;
    PFN_vkGetDeviceMemoryCommitment pvkGetDeviceMemoryCommitment;
    PFN_vkGetBufferMemoryRequirements pvkGetBufferMemoryRequirements;
    PFN_vkBindBufferMemory pvkBindBufferMemory;
    PFN_vkGetImageMemoryRequirements pvkGetImageMemoryRequirements;
    PFN_vkBindImageMemory pvkBindImageMemory;
    PFN_vkGetImageSparseMemoryRequirements pvkGetImageSparseMemoryRequirements;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties pvkGetPhysicalDeviceSparseImageFormatProperties;
    PFN_vkQueueBindSparse pvkQueueBindSparse;
    PFN_vkCreateFence pvkCreateFence;
    PFN_vkDestroyFence pvkDestroyFence;
    PFN_vkResetFences pvkResetFences;
    PFN_vkGetFenceStatus pvkGetFenceStatus;
    PFN_vkWaitForFences pvkWaitForFences;
    PFN_vkCreateSemaphore pvkCreateSemaphore;
    PFN_vkDestroySemaphore pvkDestroySemaphore;
    PFN_vkCreateEvent pvkCreateEvent;
    PFN_vkDestroyEvent pvkDestroyEvent;
    PFN_vkGetEventStatus pvkGetEventStatus;
    PFN_vkSetEvent pvkSetEvent;
    PFN_vkResetEvent pvkResetEvent;
    PFN_vkCreateQueryPool pvkCreateQueryPool;
    PFN_vkDestroyQueryPool pvkDestroyQueryPool;
    PFN_vkGetQueryPoolResults pvkGetQueryPoolResults;
    PFN_vkResetQueryPool pvkResetQueryPool;
    PFN_vkResetQueryPoolEXT pvkResetQueryPoolEXT;
    PFN_vkCreateBuffer pvkCreateBuffer;
    PFN_vkDestroyBuffer pvkDestroyBuffer;
    PFN_vkCreateBufferView pvkCreateBufferView;
    PFN_vkDestroyBufferView pvkDestroyBufferView;
    PFN_vkCreateImage pvkCreateImage;
    PFN_vkDestroyImage pvkDestroyImage;
    PFN_vkGetImageSubresourceLayout pvkGetImageSubresourceLayout;
    PFN_vkCreateImageView pvkCreateImageView;
    PFN_vkDestroyImageView pvkDestroyImageView;
    PFN_vkCreateShaderModule pvkCreateShaderModule;
    PFN_vkDestroyShaderModule pvkDestroyShaderModule;
    PFN_vkCreatePipelineCache pvkCreatePipelineCache;
    PFN_vkDestroyPipelineCache pvkDestroyPipelineCache;
    PFN_vkGetPipelineCacheData pvkGetPipelineCacheData;
    PFN_vkMergePipelineCaches pvkMergePipelineCaches;
    PFN_vkCreatePipelineBinariesKHR pvkCreatePipelineBinariesKHR;
    PFN_vkDestroyPipelineBinaryKHR pvkDestroyPipelineBinaryKHR;
    PFN_vkGetPipelineKeyKHR pvkGetPipelineKeyKHR;
    PFN_vkGetPipelineBinaryDataKHR pvkGetPipelineBinaryDataKHR;
    PFN_vkReleaseCapturedPipelineDataKHR pvkReleaseCapturedPipelineDataKHR;
    PFN_vkCreateGraphicsPipelines pvkCreateGraphicsPipelines;
    PFN_vkCreateComputePipelines pvkCreateComputePipelines;
    PFN_vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI pvkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI;
    PFN_vkDestroyPipeline pvkDestroyPipeline;
    PFN_vkCreatePipelineLayout pvkCreatePipelineLayout;
    PFN_vkDestroyPipelineLayout pvkDestroyPipelineLayout;
    PFN_vkCreateSampler pvkCreateSampler;
    PFN_vkDestroySampler pvkDestroySampler;
    PFN_vkCreateDescriptorSetLayout pvkCreateDescriptorSetLayout;
    PFN_vkDestroyDescriptorSetLayout pvkDestroyDescriptorSetLayout;
    PFN_vkCreateDescriptorPool pvkCreateDescriptorPool;
    PFN_vkDestroyDescriptorPool pvkDestroyDescriptorPool;
    PFN_vkResetDescriptorPool pvkResetDescriptorPool;
    PFN_vkAllocateDescriptorSets pvkAllocateDescriptorSets;
    PFN_vkFreeDescriptorSets pvkFreeDescriptorSets;
    PFN_vkUpdateDescriptorSets pvkUpdateDescriptorSets;
    PFN_vkCreateFramebuffer pvkCreateFramebuffer;
    PFN_vkDestroyFramebuffer pvkDestroyFramebuffer;
    PFN_vkCreateRenderPass pvkCreateRenderPass;
    PFN_vkDestroyRenderPass pvkDestroyRenderPass;
    PFN_vkGetRenderAreaGranularity pvkGetRenderAreaGranularity;
    PFN_vkGetRenderingAreaGranularity pvkGetRenderingAreaGranularity;
    PFN_vkGetRenderingAreaGranularityKHR pvkGetRenderingAreaGranularityKHR;
    PFN_vkCreateCommandPool pvkCreateCommandPool;
    PFN_vkDestroyCommandPool pvkDestroyCommandPool;
    PFN_vkResetCommandPool pvkResetCommandPool;
    PFN_vkAllocateCommandBuffers pvkAllocateCommandBuffers;
    PFN_vkFreeCommandBuffers pvkFreeCommandBuffers;
    PFN_vkBeginCommandBuffer pvkBeginCommandBuffer;
    PFN_vkEndCommandBuffer pvkEndCommandBuffer;
    PFN_vkResetCommandBuffer pvkResetCommandBuffer;
    PFN_vkCmdBindPipeline pvkCmdBindPipeline;
    PFN_vkCmdSetAttachmentFeedbackLoopEnableEXT pvkCmdSetAttachmentFeedbackLoopEnableEXT;
    PFN_vkCmdSetViewport pvkCmdSetViewport;
    PFN_vkCmdSetScissor pvkCmdSetScissor;
    PFN_vkCmdSetLineWidth pvkCmdSetLineWidth;
    PFN_vkCmdSetDepthBias pvkCmdSetDepthBias;
    PFN_vkCmdSetBlendConstants pvkCmdSetBlendConstants;
    PFN_vkCmdSetDepthBounds pvkCmdSetDepthBounds;
    PFN_vkCmdSetStencilCompareMask pvkCmdSetStencilCompareMask;
    PFN_vkCmdSetStencilWriteMask pvkCmdSetStencilWriteMask;
    PFN_vkCmdSetStencilReference pvkCmdSetStencilReference;
    PFN_vkCmdBindDescriptorSets pvkCmdBindDescriptorSets;
    PFN_vkCmdBindIndexBuffer pvkCmdBindIndexBuffer;
    PFN_vkCmdBindVertexBuffers pvkCmdBindVertexBuffers;
    PFN_vkCmdDraw pvkCmdDraw;
    PFN_vkCmdDrawIndexed pvkCmdDrawIndexed;
    PFN_vkCmdDrawMultiEXT pvkCmdDrawMultiEXT;
    PFN_vkCmdDrawMultiIndexedEXT pvkCmdDrawMultiIndexedEXT;
    PFN_vkCmdDrawIndirect pvkCmdDrawIndirect;
    PFN_vkCmdDrawIndexedIndirect pvkCmdDrawIndexedIndirect;
    PFN_vkCmdDispatch pvkCmdDispatch;
    PFN_vkCmdDispatchIndirect pvkCmdDispatchIndirect;
    PFN_vkCmdSubpassShadingHUAWEI pvkCmdSubpassShadingHUAWEI;
    PFN_vkCmdDrawClusterHUAWEI pvkCmdDrawClusterHUAWEI;
    PFN_vkCmdDrawClusterIndirectHUAWEI pvkCmdDrawClusterIndirectHUAWEI;
    PFN_vkCmdUpdatePipelineIndirectBufferNV pvkCmdUpdatePipelineIndirectBufferNV;
    PFN_vkCmdCopyBuffer pvkCmdCopyBuffer;
    PFN_vkCmdCopyImage pvkCmdCopyImage;
    PFN_vkCmdBlitImage pvkCmdBlitImage;
    PFN_vkCmdCopyBufferToImage pvkCmdCopyBufferToImage;
    PFN_vkCmdCopyImageToBuffer pvkCmdCopyImageToBuffer;
    PFN_vkCmdCopyMemoryIndirectNV pvkCmdCopyMemoryIndirectNV;
    PFN_vkCmdCopyMemoryToImageIndirectNV pvkCmdCopyMemoryToImageIndirectNV;
    PFN_vkCmdUpdateBuffer pvkCmdUpdateBuffer;
    PFN_vkCmdFillBuffer pvkCmdFillBuffer;
    PFN_vkCmdClearColorImage pvkCmdClearColorImage;
    PFN_vkCmdClearDepthStencilImage pvkCmdClearDepthStencilImage;
    PFN_vkCmdClearAttachments pvkCmdClearAttachments;
    PFN_vkCmdResolveImage pvkCmdResolveImage;
    PFN_vkCmdSetEvent pvkCmdSetEvent;
    PFN_vkCmdResetEvent pvkCmdResetEvent;
    PFN_vkCmdWaitEvents pvkCmdWaitEvents;
    PFN_vkCmdPipelineBarrier pvkCmdPipelineBarrier;
    PFN_vkCmdBeginQuery pvkCmdBeginQuery;
    PFN_vkCmdEndQuery pvkCmdEndQuery;
    PFN_vkCmdBeginConditionalRenderingEXT pvkCmdBeginConditionalRenderingEXT;
    PFN_vkCmdEndConditionalRenderingEXT pvkCmdEndConditionalRenderingEXT;
    PFN_vkCmdResetQueryPool pvkCmdResetQueryPool;
    PFN_vkCmdWriteTimestamp pvkCmdWriteTimestamp;
    PFN_vkCmdCopyQueryPoolResults pvkCmdCopyQueryPoolResults;
    PFN_vkCmdPushConstants pvkCmdPushConstants;
    PFN_vkCmdBeginRenderPass pvkCmdBeginRenderPass;
    PFN_vkCmdNextSubpass pvkCmdNextSubpass;
    PFN_vkCmdEndRenderPass pvkCmdEndRenderPass;
    PFN_vkCmdExecuteCommands pvkCmdExecuteCommands;
    PFN_vkCreateSharedSwapchainsKHR pvkCreateSharedSwapchainsKHR;
    PFN_vkDestroySurfaceKHR pvkDestroySurfaceKHR;
    PFN_vkGetPhysicalDeviceSurfaceSupportKHR pvkGetPhysicalDeviceSurfaceSupportKHR;
    PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR pvkGetPhysicalDeviceSurfaceCapabilitiesKHR;
    PFN_vkGetPhysicalDeviceSurfaceFormatsKHR pvkGetPhysicalDeviceSurfaceFormatsKHR;
    PFN_vkGetPhysicalDeviceSurfacePresentModesKHR pvkGetPhysicalDeviceSurfacePresentModesKHR;
    PFN_vkCreateSwapchainKHR pvkCreateSwapchainKHR;
    PFN_vkDestroySwapchainKHR pvkDestroySwapchainKHR;
    PFN_vkGetSwapchainImagesKHR pvkGetSwapchainImagesKHR;
    PFN_vkAcquireNextImageKHR pvkAcquireNextImageKHR;
    PFN_vkQueuePresentKHR pvkQueuePresentKHR;
    PFN_vkCreateDebugReportCallbackEXT pvkCreateDebugReportCallbackEXT;
    PFN_vkDestroyDebugReportCallbackEXT pvkDestroyDebugReportCallbackEXT;
    PFN_vkDebugReportMessageEXT pvkDebugReportMessageEXT;
    PFN_vkDebugMarkerSetObjectNameEXT pvkDebugMarkerSetObjectNameEXT;
    PFN_vkDebugMarkerSetObjectTagEXT pvkDebugMarkerSetObjectTagEXT;
    PFN_vkCmdDebugMarkerBeginEXT pvkCmdDebugMarkerBeginEXT;
    PFN_vkCmdDebugMarkerEndEXT pvkCmdDebugMarkerEndEXT;
    PFN_vkCmdDebugMarkerInsertEXT pvkCmdDebugMarkerInsertEXT;
    PFN_vkCmdExecuteGeneratedCommandsNV pvkCmdExecuteGeneratedCommandsNV;
    PFN_vkCmdPreprocessGeneratedCommandsNV pvkCmdPreprocessGeneratedCommandsNV;
    PFN_vkCmdBindPipelineShaderGroupNV pvkCmdBindPipelineShaderGroupNV;
    PFN_vkGetGeneratedCommandsMemoryRequirementsNV pvkGetGeneratedCommandsMemoryRequirementsNV;
    PFN_vkCreateIndirectCommandsLayoutNV pvkCreateIndirectCommandsLayoutNV;
    PFN_vkDestroyIndirectCommandsLayoutNV pvkDestroyIndirectCommandsLayoutNV;
    PFN_vkCmdExecuteGeneratedCommandsEXT pvkCmdExecuteGeneratedCommandsEXT;
    PFN_vkCmdPreprocessGeneratedCommandsEXT pvkCmdPreprocessGeneratedCommandsEXT;
    PFN_vkGetGeneratedCommandsMemoryRequirementsEXT pvkGetGeneratedCommandsMemoryRequirementsEXT;
    PFN_vkCreateIndirectCommandsLayoutEXT pvkCreateIndirectCommandsLayoutEXT;
    PFN_vkDestroyIndirectCommandsLayoutEXT pvkDestroyIndirectCommandsLayoutEXT;
    PFN_vkCreateIndirectExecutionSetEXT pvkCreateIndirectExecutionSetEXT;
    PFN_vkDestroyIndirectExecutionSetEXT pvkDestroyIndirectExecutionSetEXT;
    PFN_vkUpdateIndirectExecutionSetPipelineEXT pvkUpdateIndirectExecutionSetPipelineEXT;
    PFN_vkUpdateIndirectExecutionSetShaderEXT pvkUpdateIndirectExecutionSetShaderEXT;
    PFN_vkGetPhysicalDeviceFeatures2 pvkGetPhysicalDeviceFeatures2;
    PFN_vkGetPhysicalDeviceFeatures2KHR pvkGetPhysicalDeviceFeatures2KHR;
    PFN_vkGetPhysicalDeviceProperties2 pvkGetPhysicalDeviceProperties2;
    PFN_vkGetPhysicalDeviceProperties2KHR pvkGetPhysicalDeviceProperties2KHR;
    PFN_vkGetPhysicalDeviceFormatProperties2 pvkGetPhysicalDeviceFormatProperties2;
    PFN_vkGetPhysicalDeviceFormatProperties2KHR pvkGetPhysicalDeviceFormatProperties2KHR;
    PFN_vkGetPhysicalDeviceImageFormatProperties2 pvkGetPhysicalDeviceImageFormatProperties2;
    PFN_vkGetPhysicalDeviceImageFormatProperties2KHR pvkGetPhysicalDeviceImageFormatProperties2KHR;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties2 pvkGetPhysicalDeviceQueueFamilyProperties2;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties2KHR pvkGetPhysicalDeviceQueueFamilyProperties2KHR;
    PFN_vkGetPhysicalDeviceMemoryProperties2 pvkGetPhysicalDeviceMemoryProperties2;
    PFN_vkGetPhysicalDeviceMemoryProperties2KHR pvkGetPhysicalDeviceMemoryProperties2KHR;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties2 pvkGetPhysicalDeviceSparseImageFormatProperties2;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties2KHR pvkGetPhysicalDeviceSparseImageFormatProperties2KHR;
    PFN_vkCmdPushDescriptorSet pvkCmdPushDescriptorSet;
    PFN_vkCmdPushDescriptorSetKHR pvkCmdPushDescriptorSetKHR;
    PFN_vkTrimCommandPool pvkTrimCommandPool;
    PFN_vkTrimCommandPoolKHR pvkTrimCommandPoolKHR;
    PFN_vkGetPhysicalDeviceExternalBufferProperties pvkGetPhysicalDeviceExternalBufferProperties;
    PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR pvkGetPhysicalDeviceExternalBufferPropertiesKHR;
    PFN_vkGetPhysicalDeviceExternalSemaphoreProperties pvkGetPhysicalDeviceExternalSemaphoreProperties;
    PFN_vkGetPhysicalDeviceExternalSemaphorePropertiesKHR pvkGetPhysicalDeviceExternalSemaphorePropertiesKHR;
    PFN_vkGetPhysicalDeviceExternalFenceProperties pvkGetPhysicalDeviceExternalFenceProperties;
    PFN_vkGetPhysicalDeviceExternalFencePropertiesKHR pvkGetPhysicalDeviceExternalFencePropertiesKHR;
    PFN_vkReleaseDisplayEXT pvkReleaseDisplayEXT;
    PFN_vkDisplayPowerControlEXT pvkDisplayPowerControlEXT;
    PFN_vkRegisterDeviceEventEXT pvkRegisterDeviceEventEXT;
    PFN_vkRegisterDisplayEventEXT pvkRegisterDisplayEventEXT;
    PFN_vkGetSwapchainCounterEXT pvkGetSwapchainCounterEXT;
    PFN_vkGetPhysicalDeviceSurfaceCapabilities2EXT pvkGetPhysicalDeviceSurfaceCapabilities2EXT;
    PFN_vkEnumeratePhysicalDeviceGroups pvkEnumeratePhysicalDeviceGroups;
    PFN_vkEnumeratePhysicalDeviceGroupsKHR pvkEnumeratePhysicalDeviceGroupsKHR;
    PFN_vkGetDeviceGroupPeerMemoryFeatures pvkGetDeviceGroupPeerMemoryFeatures;
    PFN_vkGetDeviceGroupPeerMemoryFeaturesKHR pvkGetDeviceGroupPeerMemoryFeaturesKHR;
    PFN_vkBindBufferMemory2 pvkBindBufferMemory2;
    PFN_vkBindBufferMemory2KHR pvkBindBufferMemory2KHR;
    PFN_vkBindImageMemory2 pvkBindImageMemory2;
    PFN_vkBindImageMemory2KHR pvkBindImageMemory2KHR;
    PFN_vkCmdSetDeviceMask pvkCmdSetDeviceMask;
    PFN_vkCmdSetDeviceMaskKHR pvkCmdSetDeviceMaskKHR;
    PFN_vkGetDeviceGroupPresentCapabilitiesKHR pvkGetDeviceGroupPresentCapabilitiesKHR;
    PFN_vkGetDeviceGroupSurfacePresentModesKHR pvkGetDeviceGroupSurfacePresentModesKHR;
    PFN_vkAcquireNextImage2KHR pvkAcquireNextImage2KHR;
    PFN_vkCmdDispatchBase pvkCmdDispatchBase;
    PFN_vkCmdDispatchBaseKHR pvkCmdDispatchBaseKHR;
    PFN_vkGetPhysicalDevicePresentRectanglesKHR pvkGetPhysicalDevicePresentRectanglesKHR;
    PFN_vkCreateDescriptorUpdateTemplate pvkCreateDescriptorUpdateTemplate;
    PFN_vkCreateDescriptorUpdateTemplateKHR pvkCreateDescriptorUpdateTemplateKHR;
    PFN_vkDestroyDescriptorUpdateTemplate pvkDestroyDescriptorUpdateTemplate;
    PFN_vkDestroyDescriptorUpdateTemplateKHR pvkDestroyDescriptorUpdateTemplateKHR;
    PFN_vkUpdateDescriptorSetWithTemplate pvkUpdateDescriptorSetWithTemplate;
    PFN_vkUpdateDescriptorSetWithTemplateKHR pvkUpdateDescriptorSetWithTemplateKHR;
    PFN_vkCmdPushDescriptorSetWithTemplate pvkCmdPushDescriptorSetWithTemplate;
    PFN_vkCmdPushDescriptorSetWithTemplateKHR pvkCmdPushDescriptorSetWithTemplateKHR;
    PFN_vkSetHdrMetadataEXT pvkSetHdrMetadataEXT;
    PFN_vkCmdSetViewportWScalingNV pvkCmdSetViewportWScalingNV;
    PFN_vkCmdSetDiscardRectangleEXT pvkCmdSetDiscardRectangleEXT;
    PFN_vkCmdSetDiscardRectangleEnableEXT pvkCmdSetDiscardRectangleEnableEXT;
    PFN_vkCmdSetDiscardRectangleModeEXT pvkCmdSetDiscardRectangleModeEXT;
    PFN_vkCmdSetSampleLocationsEXT pvkCmdSetSampleLocationsEXT;
    PFN_vkGetPhysicalDeviceMultisamplePropertiesEXT pvkGetPhysicalDeviceMultisamplePropertiesEXT;
    PFN_vkGetPhysicalDeviceSurfaceCapabilities2KHR pvkGetPhysicalDeviceSurfaceCapabilities2KHR;
    PFN_vkGetPhysicalDeviceSurfaceFormats2KHR pvkGetPhysicalDeviceSurfaceFormats2KHR;
    PFN_vkGetPhysicalDeviceDisplayProperties2KHR pvkGetPhysicalDeviceDisplayProperties2KHR;
    PFN_vkGetPhysicalDeviceDisplayPlaneProperties2KHR pvkGetPhysicalDeviceDisplayPlaneProperties2KHR;
    PFN_vkGetDisplayModeProperties2KHR pvkGetDisplayModeProperties2KHR;
    PFN_vkGetDisplayPlaneCapabilities2KHR pvkGetDisplayPlaneCapabilities2KHR;
    PFN_vkGetBufferMemoryRequirements2 pvkGetBufferMemoryRequirements2;
    PFN_vkGetBufferMemoryRequirements2KHR pvkGetBufferMemoryRequirements2KHR;
    PFN_vkGetImageMemoryRequirements2 pvkGetImageMemoryRequirements2;
    PFN_vkGetImageMemoryRequirements2KHR pvkGetImageMemoryRequirements2KHR;
    PFN_vkGetImageSparseMemoryRequirements2 pvkGetImageSparseMemoryRequirements2;
    PFN_vkGetImageSparseMemoryRequirements2KHR pvkGetImageSparseMemoryRequirements2KHR;
    PFN_vkGetDeviceBufferMemoryRequirements pvkGetDeviceBufferMemoryRequirements;
    PFN_vkGetDeviceBufferMemoryRequirementsKHR pvkGetDeviceBufferMemoryRequirementsKHR;
    PFN_vkGetDeviceImageMemoryRequirements pvkGetDeviceImageMemoryRequirements;
    PFN_vkGetDeviceImageMemoryRequirementsKHR pvkGetDeviceImageMemoryRequirementsKHR;
    PFN_vkGetDeviceImageSparseMemoryRequirements pvkGetDeviceImageSparseMemoryRequirements;
    PFN_vkGetDeviceImageSparseMemoryRequirementsKHR pvkGetDeviceImageSparseMemoryRequirementsKHR;
    PFN_vkCreateSamplerYcbcrConversion pvkCreateSamplerYcbcrConversion;
    PFN_vkCreateSamplerYcbcrConversionKHR pvkCreateSamplerYcbcrConversionKHR;
    PFN_vkDestroySamplerYcbcrConversion pvkDestroySamplerYcbcrConversion;
    PFN_vkDestroySamplerYcbcrConversionKHR pvkDestroySamplerYcbcrConversionKHR;
    PFN_vkGetDeviceQueue2 pvkGetDeviceQueue2;
    PFN_vkCreateValidationCacheEXT pvkCreateValidationCacheEXT;
    PFN_vkDestroyValidationCacheEXT pvkDestroyValidationCacheEXT;
    PFN_vkGetValidationCacheDataEXT pvkGetValidationCacheDataEXT;
    PFN_vkMergeValidationCachesEXT pvkMergeValidationCachesEXT;
    PFN_vkGetDescriptorSetLayoutSupport pvkGetDescriptorSetLayoutSupport;
    PFN_vkGetDescriptorSetLayoutSupportKHR pvkGetDescriptorSetLayoutSupportKHR;
    PFN_vkGetShaderInfoAMD pvkGetShaderInfoAMD;
    PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR pvkGetPhysicalDeviceCalibrateableTimeDomainsKHR;
    PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsEXT pvkGetPhysicalDeviceCalibrateableTimeDomainsEXT;
    PFN_vkGetCalibratedTimestampsKHR pvkGetCalibratedTimestampsKHR;
    PFN_vkGetCalibratedTimestampsEXT pvkGetCalibratedTimestampsEXT;
    PFN_vkSetDebugUtilsObjectNameEXT pvkSetDebugUtilsObjectNameEXT;
    PFN_vkSetDebugUtilsObjectTagEXT pvkSetDebugUtilsObjectTagEXT;
    PFN_vkQueueBeginDebugUtilsLabelEXT pvkQueueBeginDebugUtilsLabelEXT;
    PFN_vkQueueEndDebugUtilsLabelEXT pvkQueueEndDebugUtilsLabelEXT;
    PFN_vkQueueInsertDebugUtilsLabelEXT pvkQueueInsertDebugUtilsLabelEXT;
    PFN_vkCmdBeginDebugUtilsLabelEXT pvkCmdBeginDebugUtilsLabelEXT;
    PFN_vkCmdEndDebugUtilsLabelEXT pvkCmdEndDebugUtilsLabelEXT;
    PFN_vkCmdInsertDebugUtilsLabelEXT pvkCmdInsertDebugUtilsLabelEXT;
    PFN_vkCreateDebugUtilsMessengerEXT pvkCreateDebugUtilsMessengerEXT;
    PFN_vkDestroyDebugUtilsMessengerEXT pvkDestroyDebugUtilsMessengerEXT;
    PFN_vkSubmitDebugUtilsMessageEXT pvkSubmitDebugUtilsMessageEXT;
    PFN_vkGetMemoryHostPointerPropertiesEXT pvkGetMemoryHostPointerPropertiesEXT;
    PFN_vkCmdWriteBufferMarkerAMD pvkCmdWriteBufferMarkerAMD;
    PFN_vkCreateRenderPass2 pvkCreateRenderPass2;
    PFN_vkCreateRenderPass2KHR pvkCreateRenderPass2KHR;
    PFN_vkCmdBeginRenderPass2 pvkCmdBeginRenderPass2;
    PFN_vkCmdBeginRenderPass2KHR pvkCmdBeginRenderPass2KHR;
    PFN_vkCmdNextSubpass2 pvkCmdNextSubpass2;
    PFN_vkCmdNextSubpass2KHR pvkCmdNextSubpass2KHR;
    PFN_vkCmdEndRenderPass2 pvkCmdEndRenderPass2;
    PFN_vkCmdEndRenderPass2KHR pvkCmdEndRenderPass2KHR;
    PFN_vkGetSemaphoreCounterValue pvkGetSemaphoreCounterValue;
    PFN_vkGetSemaphoreCounterValueKHR pvkGetSemaphoreCounterValueKHR;
    PFN_vkWaitSemaphores pvkWaitSemaphores;
    PFN_vkWaitSemaphoresKHR pvkWaitSemaphoresKHR;
    PFN_vkSignalSemaphore pvkSignalSemaphore;
    PFN_vkSignalSemaphoreKHR pvkSignalSemaphoreKHR;
    PFN_vkCmdDrawIndirectCount pvkCmdDrawIndirectCount;
    PFN_vkCmdDrawIndirectCountKHR pvkCmdDrawIndirectCountKHR;
    PFN_vkCmdDrawIndirectCountAMD pvkCmdDrawIndirectCountAMD;
    PFN_vkCmdDrawIndexedIndirectCount pvkCmdDrawIndexedIndirectCount;
    PFN_vkCmdDrawIndexedIndirectCountKHR pvkCmdDrawIndexedIndirectCountKHR;
    PFN_vkCmdDrawIndexedIndirectCountAMD pvkCmdDrawIndexedIndirectCountAMD;
    PFN_vkCmdSetCheckpointNV pvkCmdSetCheckpointNV;
    PFN_vkGetQueueCheckpointDataNV pvkGetQueueCheckpointDataNV;
    PFN_vkCmdBindTransformFeedbackBuffersEXT pvkCmdBindTransformFeedbackBuffersEXT;
    PFN_vkCmdBeginTransformFeedbackEXT pvkCmdBeginTransformFeedbackEXT;
    PFN_vkCmdEndTransformFeedbackEXT pvkCmdEndTransformFeedbackEXT;
    PFN_vkCmdBeginQueryIndexedEXT pvkCmdBeginQueryIndexedEXT;
    PFN_vkCmdEndQueryIndexedEXT pvkCmdEndQueryIndexedEXT;
    PFN_vkCmdDrawIndirectByteCountEXT pvkCmdDrawIndirectByteCountEXT;
    PFN_vkCmdSetExclusiveScissorNV pvkCmdSetExclusiveScissorNV;
    PFN_vkCmdSetExclusiveScissorEnableNV pvkCmdSetExclusiveScissorEnableNV;
    PFN_vkCmdBindShadingRateImageNV pvkCmdBindShadingRateImageNV;
    PFN_vkCmdSetViewportShadingRatePaletteNV pvkCmdSetViewportShadingRatePaletteNV;
    PFN_vkCmdSetCoarseSampleOrderNV pvkCmdSetCoarseSampleOrderNV;
    PFN_vkCmdDrawMeshTasksNV pvkCmdDrawMeshTasksNV;
    PFN_vkCmdDrawMeshTasksIndirectNV pvkCmdDrawMeshTasksIndirectNV;
    PFN_vkCmdDrawMeshTasksIndirectCountNV pvkCmdDrawMeshTasksIndirectCountNV;
    PFN_vkCmdDrawMeshTasksEXT pvkCmdDrawMeshTasksEXT;
    PFN_vkCmdDrawMeshTasksIndirectEXT pvkCmdDrawMeshTasksIndirectEXT;
    PFN_vkCmdDrawMeshTasksIndirectCountEXT pvkCmdDrawMeshTasksIndirectCountEXT;
    PFN_vkCompileDeferredNV pvkCompileDeferredNV;
    PFN_vkCreateAccelerationStructureNV pvkCreateAccelerationStructureNV;
    PFN_vkCmdBindInvocationMaskHUAWEI pvkCmdBindInvocationMaskHUAWEI;
    PFN_vkDestroyAccelerationStructureKHR pvkDestroyAccelerationStructureKHR;
    PFN_vkDestroyAccelerationStructureNV pvkDestroyAccelerationStructureNV;
    PFN_vkGetAccelerationStructureMemoryRequirementsNV pvkGetAccelerationStructureMemoryRequirementsNV;
    PFN_vkBindAccelerationStructureMemoryNV pvkBindAccelerationStructureMemoryNV;
    PFN_vkCmdCopyAccelerationStructureNV pvkCmdCopyAccelerationStructureNV;
    PFN_vkCmdCopyAccelerationStructureKHR pvkCmdCopyAccelerationStructureKHR;
    PFN_vkCopyAccelerationStructureKHR pvkCopyAccelerationStructureKHR;
    PFN_vkCmdCopyAccelerationStructureToMemoryKHR pvkCmdCopyAccelerationStructureToMemoryKHR;
    PFN_vkCopyAccelerationStructureToMemoryKHR pvkCopyAccelerationStructureToMemoryKHR;
    PFN_vkCmdCopyMemoryToAccelerationStructureKHR pvkCmdCopyMemoryToAccelerationStructureKHR;
    PFN_vkCopyMemoryToAccelerationStructureKHR pvkCopyMemoryToAccelerationStructureKHR;
    PFN_vkCmdWriteAccelerationStructuresPropertiesKHR pvkCmdWriteAccelerationStructuresPropertiesKHR;
    PFN_vkCmdWriteAccelerationStructuresPropertiesNV pvkCmdWriteAccelerationStructuresPropertiesNV;
    PFN_vkCmdBuildAccelerationStructureNV pvkCmdBuildAccelerationStructureNV;
    PFN_vkWriteAccelerationStructuresPropertiesKHR pvkWriteAccelerationStructuresPropertiesKHR;
    PFN_vkCmdTraceRaysKHR pvkCmdTraceRaysKHR;
    PFN_vkCmdTraceRaysNV pvkCmdTraceRaysNV;
    PFN_vkGetRayTracingShaderGroupHandlesKHR pvkGetRayTracingShaderGroupHandlesKHR;
    PFN_vkGetRayTracingShaderGroupHandlesNV pvkGetRayTracingShaderGroupHandlesNV;
    PFN_vkGetRayTracingCaptureReplayShaderGroupHandlesKHR pvkGetRayTracingCaptureReplayShaderGroupHandlesKHR;
    PFN_vkGetAccelerationStructureHandleNV pvkGetAccelerationStructureHandleNV;
    PFN_vkCreateRayTracingPipelinesNV pvkCreateRayTracingPipelinesNV;
    PFN_vkCreateRayTracingPipelinesKHR pvkCreateRayTracingPipelinesKHR;
    PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesNV pvkGetPhysicalDeviceCooperativeMatrixPropertiesNV;
    PFN_vkCmdTraceRaysIndirectKHR pvkCmdTraceRaysIndirectKHR;
    PFN_vkCmdTraceRaysIndirect2KHR pvkCmdTraceRaysIndirect2KHR;
    PFN_vkGetDeviceAccelerationStructureCompatibilityKHR pvkGetDeviceAccelerationStructureCompatibilityKHR;
    PFN_vkGetRayTracingShaderGroupStackSizeKHR pvkGetRayTracingShaderGroupStackSizeKHR;
    PFN_vkCmdSetRayTracingPipelineStackSizeKHR pvkCmdSetRayTracingPipelineStackSizeKHR;
    PFN_vkGetImageViewHandleNVX pvkGetImageViewHandleNVX;
    PFN_vkGetImageViewHandle64NVX pvkGetImageViewHandle64NVX;
    PFN_vkGetImageViewAddressNVX pvkGetImageViewAddressNVX;
    PFN_vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR pvkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR;
    PFN_vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR pvkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR;
    PFN_vkAcquireProfilingLockKHR pvkAcquireProfilingLockKHR;
    PFN_vkReleaseProfilingLockKHR pvkReleaseProfilingLockKHR;
    PFN_vkGetBufferOpaqueCaptureAddress pvkGetBufferOpaqueCaptureAddress;
    PFN_vkGetBufferOpaqueCaptureAddressKHR pvkGetBufferOpaqueCaptureAddressKHR;
    PFN_vkGetBufferDeviceAddress pvkGetBufferDeviceAddress;
    PFN_vkGetBufferDeviceAddressKHR pvkGetBufferDeviceAddressKHR;
    PFN_vkGetBufferDeviceAddressEXT pvkGetBufferDeviceAddressEXT;
    PFN_vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV pvkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV;
    PFN_vkInitializePerformanceApiINTEL pvkInitializePerformanceApiINTEL;
    PFN_vkUninitializePerformanceApiINTEL pvkUninitializePerformanceApiINTEL;
    PFN_vkCmdSetPerformanceMarkerINTEL pvkCmdSetPerformanceMarkerINTEL;
    PFN_vkCmdSetPerformanceStreamMarkerINTEL pvkCmdSetPerformanceStreamMarkerINTEL;
    PFN_vkCmdSetPerformanceOverrideINTEL pvkCmdSetPerformanceOverrideINTEL;
    PFN_vkAcquirePerformanceConfigurationINTEL pvkAcquirePerformanceConfigurationINTEL;
    PFN_vkReleasePerformanceConfigurationINTEL pvkReleasePerformanceConfigurationINTEL;
    PFN_vkQueueSetPerformanceConfigurationINTEL pvkQueueSetPerformanceConfigurationINTEL;
    PFN_vkGetPerformanceParameterINTEL pvkGetPerformanceParameterINTEL;
    PFN_vkGetDeviceMemoryOpaqueCaptureAddress pvkGetDeviceMemoryOpaqueCaptureAddress;
    PFN_vkGetDeviceMemoryOpaqueCaptureAddressKHR pvkGetDeviceMemoryOpaqueCaptureAddressKHR;
    PFN_vkGetPipelineExecutablePropertiesKHR pvkGetPipelineExecutablePropertiesKHR;
    PFN_vkGetPipelineExecutableStatisticsKHR pvkGetPipelineExecutableStatisticsKHR;
    PFN_vkGetPipelineExecutableInternalRepresentationsKHR pvkGetPipelineExecutableInternalRepresentationsKHR;
    PFN_vkCmdSetLineStipple pvkCmdSetLineStipple;
    PFN_vkCmdSetLineStippleKHR pvkCmdSetLineStippleKHR;
    PFN_vkCmdSetLineStippleEXT pvkCmdSetLineStippleEXT;
    PFN_vkGetPhysicalDeviceToolProperties pvkGetPhysicalDeviceToolProperties;
    PFN_vkGetPhysicalDeviceToolPropertiesEXT pvkGetPhysicalDeviceToolPropertiesEXT;
    PFN_vkCreateAccelerationStructureKHR pvkCreateAccelerationStructureKHR;
    PFN_vkCmdBuildAccelerationStructuresKHR pvkCmdBuildAccelerationStructuresKHR;
    PFN_vkCmdBuildAccelerationStructuresIndirectKHR pvkCmdBuildAccelerationStructuresIndirectKHR;
    PFN_vkBuildAccelerationStructuresKHR pvkBuildAccelerationStructuresKHR;
    PFN_vkGetAccelerationStructureDeviceAddressKHR pvkGetAccelerationStructureDeviceAddressKHR;
    PFN_vkCreateDeferredOperationKHR pvkCreateDeferredOperationKHR;
    PFN_vkDestroyDeferredOperationKHR pvkDestroyDeferredOperationKHR;
    PFN_vkGetDeferredOperationMaxConcurrencyKHR pvkGetDeferredOperationMaxConcurrencyKHR;
    PFN_vkGetDeferredOperationResultKHR pvkGetDeferredOperationResultKHR;
    PFN_vkDeferredOperationJoinKHR pvkDeferredOperationJoinKHR;
    PFN_vkGetPipelineIndirectMemoryRequirementsNV pvkGetPipelineIndirectMemoryRequirementsNV;
    PFN_vkGetPipelineIndirectDeviceAddressNV pvkGetPipelineIndirectDeviceAddressNV;
    PFN_vkAntiLagUpdateAMD pvkAntiLagUpdateAMD;
    PFN_vkCmdSetCullMode pvkCmdSetCullMode;
    PFN_vkCmdSetCullModeEXT pvkCmdSetCullModeEXT;
    PFN_vkCmdSetFrontFace pvkCmdSetFrontFace;
    PFN_vkCmdSetFrontFaceEXT pvkCmdSetFrontFaceEXT;
    PFN_vkCmdSetPrimitiveTopology pvkCmdSetPrimitiveTopology;
    PFN_vkCmdSetPrimitiveTopologyEXT pvkCmdSetPrimitiveTopologyEXT;
    PFN_vkCmdSetViewportWithCount pvkCmdSetViewportWithCount;
    PFN_vkCmdSetViewportWithCountEXT pvkCmdSetViewportWithCountEXT;
    PFN_vkCmdSetScissorWithCount pvkCmdSetScissorWithCount;
    PFN_vkCmdSetScissorWithCountEXT pvkCmdSetScissorWithCountEXT;
    PFN_vkCmdBindIndexBuffer2 pvkCmdBindIndexBuffer2;
    PFN_vkCmdBindIndexBuffer2KHR pvkCmdBindIndexBuffer2KHR;
    PFN_vkCmdBindVertexBuffers2 pvkCmdBindVertexBuffers2;
    PFN_vkCmdBindVertexBuffers2EXT pvkCmdBindVertexBuffers2EXT;
    PFN_vkCmdSetDepthTestEnable pvkCmdSetDepthTestEnable;
    PFN_vkCmdSetDepthTestEnableEXT pvkCmdSetDepthTestEnableEXT;
    PFN_vkCmdSetDepthWriteEnable pvkCmdSetDepthWriteEnable;
    PFN_vkCmdSetDepthWriteEnableEXT pvkCmdSetDepthWriteEnableEXT;
    PFN_vkCmdSetDepthCompareOp pvkCmdSetDepthCompareOp;
    PFN_vkCmdSetDepthCompareOpEXT pvkCmdSetDepthCompareOpEXT;
    PFN_vkCmdSetDepthBoundsTestEnable pvkCmdSetDepthBoundsTestEnable;
    PFN_vkCmdSetDepthBoundsTestEnableEXT pvkCmdSetDepthBoundsTestEnableEXT;
    PFN_vkCmdSetStencilTestEnable pvkCmdSetStencilTestEnable;
    PFN_vkCmdSetStencilTestEnableEXT pvkCmdSetStencilTestEnableEXT;
    PFN_vkCmdSetStencilOp pvkCmdSetStencilOp;
    PFN_vkCmdSetStencilOpEXT pvkCmdSetStencilOpEXT;
    PFN_vkCmdSetPatchControlPointsEXT pvkCmdSetPatchControlPointsEXT;
    PFN_vkCmdSetRasterizerDiscardEnable pvkCmdSetRasterizerDiscardEnable;
    PFN_vkCmdSetRasterizerDiscardEnableEXT pvkCmdSetRasterizerDiscardEnableEXT;
    PFN_vkCmdSetDepthBiasEnable pvkCmdSetDepthBiasEnable;
    PFN_vkCmdSetDepthBiasEnableEXT pvkCmdSetDepthBiasEnableEXT;
    PFN_vkCmdSetLogicOpEXT pvkCmdSetLogicOpEXT;
    PFN_vkCmdSetPrimitiveRestartEnable pvkCmdSetPrimitiveRestartEnable;
    PFN_vkCmdSetPrimitiveRestartEnableEXT pvkCmdSetPrimitiveRestartEnableEXT;
    PFN_vkCmdSetTessellationDomainOriginEXT pvkCmdSetTessellationDomainOriginEXT;
    PFN_vkCmdSetDepthClampEnableEXT pvkCmdSetDepthClampEnableEXT;
    PFN_vkCmdSetPolygonModeEXT pvkCmdSetPolygonModeEXT;
    PFN_vkCmdSetRasterizationSamplesEXT pvkCmdSetRasterizationSamplesEXT;
    PFN_vkCmdSetSampleMaskEXT pvkCmdSetSampleMaskEXT;
    PFN_vkCmdSetAlphaToCoverageEnableEXT pvkCmdSetAlphaToCoverageEnableEXT;
    PFN_vkCmdSetAlphaToOneEnableEXT pvkCmdSetAlphaToOneEnableEXT;
    PFN_vkCmdSetLogicOpEnableEXT pvkCmdSetLogicOpEnableEXT;
    PFN_vkCmdSetColorBlendEnableEXT pvkCmdSetColorBlendEnableEXT;
    PFN_vkCmdSetColorBlendEquationEXT pvkCmdSetColorBlendEquationEXT;
    PFN_vkCmdSetColorWriteMaskEXT pvkCmdSetColorWriteMaskEXT;
    PFN_vkCmdSetRasterizationStreamEXT pvkCmdSetRasterizationStreamEXT;
    PFN_vkCmdSetConservativeRasterizationModeEXT pvkCmdSetConservativeRasterizationModeEXT;
    PFN_vkCmdSetExtraPrimitiveOverestimationSizeEXT pvkCmdSetExtraPrimitiveOverestimationSizeEXT;
    PFN_vkCmdSetDepthClipEnableEXT pvkCmdSetDepthClipEnableEXT;
    PFN_vkCmdSetSampleLocationsEnableEXT pvkCmdSetSampleLocationsEnableEXT;
    PFN_vkCmdSetColorBlendAdvancedEXT pvkCmdSetColorBlendAdvancedEXT;
    PFN_vkCmdSetProvokingVertexModeEXT pvkCmdSetProvokingVertexModeEXT;
    PFN_vkCmdSetLineRasterizationModeEXT pvkCmdSetLineRasterizationModeEXT;
    PFN_vkCmdSetLineStippleEnableEXT pvkCmdSetLineStippleEnableEXT;
    PFN_vkCmdSetDepthClipNegativeOneToOneEXT pvkCmdSetDepthClipNegativeOneToOneEXT;
    PFN_vkCmdSetViewportWScalingEnableNV pvkCmdSetViewportWScalingEnableNV;
    PFN_vkCmdSetViewportSwizzleNV pvkCmdSetViewportSwizzleNV;
    PFN_vkCmdSetCoverageToColorEnableNV pvkCmdSetCoverageToColorEnableNV;
    PFN_vkCmdSetCoverageToColorLocationNV pvkCmdSetCoverageToColorLocationNV;
    PFN_vkCmdSetCoverageModulationModeNV pvkCmdSetCoverageModulationModeNV;
    PFN_vkCmdSetCoverageModulationTableEnableNV pvkCmdSetCoverageModulationTableEnableNV;
    PFN_vkCmdSetCoverageModulationTableNV pvkCmdSetCoverageModulationTableNV;
    PFN_vkCmdSetShadingRateImageEnableNV pvkCmdSetShadingRateImageEnableNV;
    PFN_vkCmdSetCoverageReductionModeNV pvkCmdSetCoverageReductionModeNV;
    PFN_vkCmdSetRepresentativeFragmentTestEnableNV pvkCmdSetRepresentativeFragmentTestEnableNV;
    PFN_vkCreatePrivateDataSlot pvkCreatePrivateDataSlot;
    PFN_vkCreatePrivateDataSlotEXT pvkCreatePrivateDataSlotEXT;
    PFN_vkDestroyPrivateDataSlot pvkDestroyPrivateDataSlot;
    PFN_vkDestroyPrivateDataSlotEXT pvkDestroyPrivateDataSlotEXT;
    PFN_vkSetPrivateData pvkSetPrivateData;
    PFN_vkSetPrivateDataEXT pvkSetPrivateDataEXT;
    PFN_vkGetPrivateData pvkGetPrivateData;
    PFN_vkGetPrivateDataEXT pvkGetPrivateDataEXT;
    PFN_vkCmdCopyBuffer2 pvkCmdCopyBuffer2;
    PFN_vkCmdCopyBuffer2KHR pvkCmdCopyBuffer2KHR;
    PFN_vkCmdCopyImage2 pvkCmdCopyImage2;
    PFN_vkCmdCopyImage2KHR pvkCmdCopyImage2KHR;
    PFN_vkCmdBlitImage2 pvkCmdBlitImage2;
    PFN_vkCmdBlitImage2KHR pvkCmdBlitImage2KHR;
    PFN_vkCmdCopyBufferToImage2 pvkCmdCopyBufferToImage2;
    PFN_vkCmdCopyBufferToImage2KHR pvkCmdCopyBufferToImage2KHR;
    PFN_vkCmdCopyImageToBuffer2 pvkCmdCopyImageToBuffer2;
    PFN_vkCmdCopyImageToBuffer2KHR pvkCmdCopyImageToBuffer2KHR;
    PFN_vkCmdResolveImage2 pvkCmdResolveImage2;
    PFN_vkCmdResolveImage2KHR pvkCmdResolveImage2KHR;
    PFN_vkCmdSetFragmentShadingRateKHR pvkCmdSetFragmentShadingRateKHR;
    PFN_vkGetPhysicalDeviceFragmentShadingRatesKHR pvkGetPhysicalDeviceFragmentShadingRatesKHR;
    PFN_vkCmdSetFragmentShadingRateEnumNV pvkCmdSetFragmentShadingRateEnumNV;
    PFN_vkGetAccelerationStructureBuildSizesKHR pvkGetAccelerationStructureBuildSizesKHR;
    PFN_vkCmdSetVertexInputEXT pvkCmdSetVertexInputEXT;
    PFN_vkCmdSetColorWriteEnableEXT pvkCmdSetColorWriteEnableEXT;
    PFN_vkCmdSetEvent2 pvkCmdSetEvent2;
    PFN_vkCmdSetEvent2KHR pvkCmdSetEvent2KHR;
    PFN_vkCmdResetEvent2 pvkCmdResetEvent2;
    PFN_vkCmdResetEvent2KHR pvkCmdResetEvent2KHR;
    PFN_vkCmdWaitEvents2 pvkCmdWaitEvents2;
    PFN_vkCmdWaitEvents2KHR pvkCmdWaitEvents2KHR;
    PFN_vkCmdPipelineBarrier2 pvkCmdPipelineBarrier2;
    PFN_vkCmdPipelineBarrier2KHR pvkCmdPipelineBarrier2KHR;
    PFN_vkQueueSubmit2 pvkQueueSubmit2;
    PFN_vkQueueSubmit2KHR pvkQueueSubmit2KHR;
    PFN_vkCmdWriteTimestamp2 pvkCmdWriteTimestamp2;
    PFN_vkCmdWriteTimestamp2KHR pvkCmdWriteTimestamp2KHR;
    PFN_vkCmdWriteBufferMarker2AMD pvkCmdWriteBufferMarker2AMD;
    PFN_vkGetQueueCheckpointData2NV pvkGetQueueCheckpointData2NV;
    PFN_vkCopyMemoryToImage pvkCopyMemoryToImage;
    PFN_vkCopyMemoryToImageEXT pvkCopyMemoryToImageEXT;
    PFN_vkCopyImageToMemory pvkCopyImageToMemory;
    PFN_vkCopyImageToMemoryEXT pvkCopyImageToMemoryEXT;
    PFN_vkCopyImageToImage pvkCopyImageToImage;
    PFN_vkCopyImageToImageEXT pvkCopyImageToImageEXT;
    PFN_vkTransitionImageLayout pvkTransitionImageLayout;
    PFN_vkTransitionImageLayoutEXT pvkTransitionImageLayoutEXT;
    PFN_vkGetPhysicalDeviceVideoCapabilitiesKHR pvkGetPhysicalDeviceVideoCapabilitiesKHR;
    PFN_vkGetPhysicalDeviceVideoFormatPropertiesKHR pvkGetPhysicalDeviceVideoFormatPropertiesKHR;
    PFN_vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR pvkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR;
    PFN_vkCreateVideoSessionKHR pvkCreateVideoSessionKHR;
    PFN_vkDestroyVideoSessionKHR pvkDestroyVideoSessionKHR;
    PFN_vkCreateVideoSessionParametersKHR pvkCreateVideoSessionParametersKHR;
    PFN_vkUpdateVideoSessionParametersKHR pvkUpdateVideoSessionParametersKHR;
    PFN_vkGetEncodedVideoSessionParametersKHR pvkGetEncodedVideoSessionParametersKHR;
    PFN_vkDestroyVideoSessionParametersKHR pvkDestroyVideoSessionParametersKHR;
    PFN_vkGetVideoSessionMemoryRequirementsKHR pvkGetVideoSessionMemoryRequirementsKHR;
    PFN_vkBindVideoSessionMemoryKHR pvkBindVideoSessionMemoryKHR;
    PFN_vkCmdDecodeVideoKHR pvkCmdDecodeVideoKHR;
    PFN_vkCmdBeginVideoCodingKHR pvkCmdBeginVideoCodingKHR;
    PFN_vkCmdControlVideoCodingKHR pvkCmdControlVideoCodingKHR;
    PFN_vkCmdEndVideoCodingKHR pvkCmdEndVideoCodingKHR;
    PFN_vkCmdEncodeVideoKHR pvkCmdEncodeVideoKHR;
    PFN_vkCmdDecompressMemoryNV pvkCmdDecompressMemoryNV;
    PFN_vkCmdDecompressMemoryIndirectCountNV pvkCmdDecompressMemoryIndirectCountNV;
    PFN_vkCreateCuModuleNVX pvkCreateCuModuleNVX;
    PFN_vkCreateCuFunctionNVX pvkCreateCuFunctionNVX;
    PFN_vkDestroyCuModuleNVX pvkDestroyCuModuleNVX;
    PFN_vkDestroyCuFunctionNVX pvkDestroyCuFunctionNVX;
    PFN_vkCmdCuLaunchKernelNVX pvkCmdCuLaunchKernelNVX;
    PFN_vkGetDescriptorSetLayoutSizeEXT pvkGetDescriptorSetLayoutSizeEXT;
    PFN_vkGetDescriptorSetLayoutBindingOffsetEXT pvkGetDescriptorSetLayoutBindingOffsetEXT;
    PFN_vkGetDescriptorEXT pvkGetDescriptorEXT;
    PFN_vkCmdBindDescriptorBuffersEXT pvkCmdBindDescriptorBuffersEXT;
    PFN_vkCmdSetDescriptorBufferOffsetsEXT pvkCmdSetDescriptorBufferOffsetsEXT;
    PFN_vkCmdBindDescriptorBufferEmbeddedSamplersEXT pvkCmdBindDescriptorBufferEmbeddedSamplersEXT;
    PFN_vkGetBufferOpaqueCaptureDescriptorDataEXT pvkGetBufferOpaqueCaptureDescriptorDataEXT;
    PFN_vkGetImageOpaqueCaptureDescriptorDataEXT pvkGetImageOpaqueCaptureDescriptorDataEXT;
    PFN_vkGetImageViewOpaqueCaptureDescriptorDataEXT pvkGetImageViewOpaqueCaptureDescriptorDataEXT;
    PFN_vkGetSamplerOpaqueCaptureDescriptorDataEXT pvkGetSamplerOpaqueCaptureDescriptorDataEXT;
    PFN_vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT pvkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT;
    PFN_vkSetDeviceMemoryPriorityEXT pvkSetDeviceMemoryPriorityEXT;
    PFN_vkAcquireDrmDisplayEXT pvkAcquireDrmDisplayEXT;
    PFN_vkGetDrmDisplayEXT pvkGetDrmDisplayEXT;
    PFN_vkWaitForPresentKHR pvkWaitForPresentKHR;
    PFN_vkCreateCudaModuleNV pvkCreateCudaModuleNV;
    PFN_vkGetCudaModuleCacheNV pvkGetCudaModuleCacheNV;
    PFN_vkCreateCudaFunctionNV pvkCreateCudaFunctionNV;
    PFN_vkDestroyCudaModuleNV pvkDestroyCudaModuleNV;
    PFN_vkDestroyCudaFunctionNV pvkDestroyCudaFunctionNV;
    PFN_vkCmdCudaLaunchKernelNV pvkCmdCudaLaunchKernelNV;
    PFN_vkCmdBeginRendering pvkCmdBeginRendering;
    PFN_vkCmdBeginRenderingKHR pvkCmdBeginRenderingKHR;
    PFN_vkCmdEndRendering pvkCmdEndRendering;
    PFN_vkCmdEndRenderingKHR pvkCmdEndRenderingKHR;
    PFN_vkGetDescriptorSetLayoutHostMappingInfoVALVE pvkGetDescriptorSetLayoutHostMappingInfoVALVE;
    PFN_vkGetDescriptorSetHostMappingVALVE pvkGetDescriptorSetHostMappingVALVE;
    PFN_vkCreateMicromapEXT pvkCreateMicromapEXT;
    PFN_vkCmdBuildMicromapsEXT pvkCmdBuildMicromapsEXT;
    PFN_vkBuildMicromapsEXT pvkBuildMicromapsEXT;
    PFN_vkDestroyMicromapEXT pvkDestroyMicromapEXT;
    PFN_vkCmdCopyMicromapEXT pvkCmdCopyMicromapEXT;
    PFN_vkCopyMicromapEXT pvkCopyMicromapEXT;
    PFN_vkCmdCopyMicromapToMemoryEXT pvkCmdCopyMicromapToMemoryEXT;
    PFN_vkCopyMicromapToMemoryEXT pvkCopyMicromapToMemoryEXT;
    PFN_vkCmdCopyMemoryToMicromapEXT pvkCmdCopyMemoryToMicromapEXT;
    PFN_vkCopyMemoryToMicromapEXT pvkCopyMemoryToMicromapEXT;
    PFN_vkCmdWriteMicromapsPropertiesEXT pvkCmdWriteMicromapsPropertiesEXT;
    PFN_vkWriteMicromapsPropertiesEXT pvkWriteMicromapsPropertiesEXT;
    PFN_vkGetDeviceMicromapCompatibilityEXT pvkGetDeviceMicromapCompatibilityEXT;
    PFN_vkGetMicromapBuildSizesEXT pvkGetMicromapBuildSizesEXT;
    PFN_vkGetShaderModuleIdentifierEXT pvkGetShaderModuleIdentifierEXT;
    PFN_vkGetShaderModuleCreateInfoIdentifierEXT pvkGetShaderModuleCreateInfoIdentifierEXT;
    PFN_vkGetImageSubresourceLayout2 pvkGetImageSubresourceLayout2;
    PFN_vkGetImageSubresourceLayout2KHR pvkGetImageSubresourceLayout2KHR;
    PFN_vkGetImageSubresourceLayout2EXT pvkGetImageSubresourceLayout2EXT;
    PFN_vkGetPipelinePropertiesEXT pvkGetPipelinePropertiesEXT;
    PFN_vkGetFramebufferTilePropertiesQCOM pvkGetFramebufferTilePropertiesQCOM;
    PFN_vkGetDynamicRenderingTilePropertiesQCOM pvkGetDynamicRenderingTilePropertiesQCOM;
    PFN_vkGetPhysicalDeviceOpticalFlowImageFormatsNV pvkGetPhysicalDeviceOpticalFlowImageFormatsNV;
    PFN_vkCreateOpticalFlowSessionNV pvkCreateOpticalFlowSessionNV;
    PFN_vkDestroyOpticalFlowSessionNV pvkDestroyOpticalFlowSessionNV;
    PFN_vkBindOpticalFlowSessionImageNV pvkBindOpticalFlowSessionImageNV;
    PFN_vkCmdOpticalFlowExecuteNV pvkCmdOpticalFlowExecuteNV;
    PFN_vkGetDeviceFaultInfoEXT pvkGetDeviceFaultInfoEXT;
    PFN_vkCmdSetDepthBias2EXT pvkCmdSetDepthBias2EXT;
    PFN_vkReleaseSwapchainImagesEXT pvkReleaseSwapchainImagesEXT;
    PFN_vkGetDeviceImageSubresourceLayout pvkGetDeviceImageSubresourceLayout;
    PFN_vkGetDeviceImageSubresourceLayoutKHR pvkGetDeviceImageSubresourceLayoutKHR;
    PFN_vkMapMemory2 pvkMapMemory2;
    PFN_vkMapMemory2KHR pvkMapMemory2KHR;
    PFN_vkUnmapMemory2 pvkUnmapMemory2;
    PFN_vkUnmapMemory2KHR pvkUnmapMemory2KHR;
    PFN_vkCreateShadersEXT pvkCreateShadersEXT;
    PFN_vkDestroyShaderEXT pvkDestroyShaderEXT;
    PFN_vkGetShaderBinaryDataEXT pvkGetShaderBinaryDataEXT;
    PFN_vkCmdBindShadersEXT pvkCmdBindShadersEXT;
    PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR pvkGetPhysicalDeviceCooperativeMatrixPropertiesKHR;
    PFN_vkCmdBindDescriptorSets2 pvkCmdBindDescriptorSets2;
    PFN_vkCmdBindDescriptorSets2KHR pvkCmdBindDescriptorSets2KHR;
    PFN_vkCmdPushConstants2 pvkCmdPushConstants2;
    PFN_vkCmdPushConstants2KHR pvkCmdPushConstants2KHR;
    PFN_vkCmdPushDescriptorSet2 pvkCmdPushDescriptorSet2;
    PFN_vkCmdPushDescriptorSet2KHR pvkCmdPushDescriptorSet2KHR;
    PFN_vkCmdPushDescriptorSetWithTemplate2 pvkCmdPushDescriptorSetWithTemplate2;
    PFN_vkCmdPushDescriptorSetWithTemplate2KHR pvkCmdPushDescriptorSetWithTemplate2KHR;
    PFN_vkCmdSetDescriptorBufferOffsets2EXT pvkCmdSetDescriptorBufferOffsets2EXT;
    PFN_vkCmdBindDescriptorBufferEmbeddedSamplers2EXT pvkCmdBindDescriptorBufferEmbeddedSamplers2EXT;
    PFN_vkSetLatencySleepModeNV pvkSetLatencySleepModeNV;
    PFN_vkLatencySleepNV pvkLatencySleepNV;
    PFN_vkSetLatencyMarkerNV pvkSetLatencyMarkerNV;
    PFN_vkGetLatencyTimingsNV pvkGetLatencyTimingsNV;
    PFN_vkQueueNotifyOutOfBandNV pvkQueueNotifyOutOfBandNV;
    PFN_vkCmdSetRenderingAttachmentLocations pvkCmdSetRenderingAttachmentLocations;
    PFN_vkCmdSetRenderingAttachmentLocationsKHR pvkCmdSetRenderingAttachmentLocationsKHR;
    PFN_vkCmdSetRenderingInputAttachmentIndices pvkCmdSetRenderingInputAttachmentIndices;
    PFN_vkCmdSetRenderingInputAttachmentIndicesKHR pvkCmdSetRenderingInputAttachmentIndicesKHR;
    PFN_vkCmdSetDepthClampRangeEXT pvkCmdSetDepthClampRangeEXT;
    PFN_vkGetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV pvkGetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV;
    std::unordered_map<BString, U32> functionAddressByName;
    std::unordered_map<U32, void*> rayTracingCaptureReplayShaderGroupHandles;
    std::unordered_map<U64, void*> debugReportCallbacks;
    std::unordered_map<U64, void*> debugUtilsCallbacks;
    VkDebugUtilsMessengerEXT debugMessenger;
};
#endif
