#ifndef __VK_HOST__H__
#define __VK_HOST__H__
#define VK_NO_PROTOTYPES
#include "vk/vulkan.h"
#include "vk/vulkan_core.h"
#ifndef BOXED_VK_EXTERN
#define BOXED_VK_EXTERN extern
#endif
BOXED_VK_EXTERN PFN_vkCreateInstance pvkCreateInstance;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceVersion pvkEnumerateInstanceVersion;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceLayerProperties pvkEnumerateInstanceLayerProperties;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceExtensionProperties pvkEnumerateInstanceExtensionProperties;
BOXED_VK_EXTERN PFN_vkGetSubpassShadingMaxWorkgroupSizeHUAWEI pvkGetSubpassShadingMaxWorkgroupSizeHUAWEI;
void vk_CreateInstance(CPU* cpu);
void vk_DestroyInstance(CPU* cpu);
void vk_EnumeratePhysicalDevices(CPU* cpu);
void vk_GetPhysicalDeviceProperties(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties(CPU* cpu);
void vk_GetPhysicalDeviceFeatures(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties(CPU* cpu);
void vk_CreateDevice(CPU* cpu);
void vk_DestroyDevice(CPU* cpu);
void vk_EnumerateInstanceVersion(CPU* cpu);
void vk_EnumerateInstanceLayerProperties(CPU* cpu);
void vk_EnumerateInstanceExtensionProperties(CPU* cpu);
void vk_EnumerateDeviceLayerProperties(CPU* cpu);
void vk_EnumerateDeviceExtensionProperties(CPU* cpu);
void vk_GetDeviceQueue(CPU* cpu);
void vk_QueueSubmit(CPU* cpu);
void vk_QueueWaitIdle(CPU* cpu);
void vk_DeviceWaitIdle(CPU* cpu);
void vk_AllocateMemory(CPU* cpu);
void vk_FreeMemory(CPU* cpu);
void vk_MapMemory(CPU* cpu);
void vk_UnmapMemory(CPU* cpu);
void vk_FlushMappedMemoryRanges(CPU* cpu);
void vk_InvalidateMappedMemoryRanges(CPU* cpu);
void vk_GetDeviceMemoryCommitment(CPU* cpu);
void vk_GetBufferMemoryRequirements(CPU* cpu);
void vk_BindBufferMemory(CPU* cpu);
void vk_GetImageMemoryRequirements(CPU* cpu);
void vk_BindImageMemory(CPU* cpu);
void vk_GetImageSparseMemoryRequirements(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties(CPU* cpu);
void vk_QueueBindSparse(CPU* cpu);
void vk_CreateFence(CPU* cpu);
void vk_DestroyFence(CPU* cpu);
void vk_ResetFences(CPU* cpu);
void vk_GetFenceStatus(CPU* cpu);
void vk_WaitForFences(CPU* cpu);
void vk_CreateSemaphore(CPU* cpu);
void vk_DestroySemaphore(CPU* cpu);
void vk_CreateEvent(CPU* cpu);
void vk_DestroyEvent(CPU* cpu);
void vk_GetEventStatus(CPU* cpu);
void vk_SetEvent(CPU* cpu);
void vk_ResetEvent(CPU* cpu);
void vk_CreateQueryPool(CPU* cpu);
void vk_DestroyQueryPool(CPU* cpu);
void vk_GetQueryPoolResults(CPU* cpu);
void vk_ResetQueryPool(CPU* cpu);
void vk_ResetQueryPoolEXT(CPU* cpu);
void vk_CreateBuffer(CPU* cpu);
void vk_DestroyBuffer(CPU* cpu);
void vk_CreateBufferView(CPU* cpu);
void vk_DestroyBufferView(CPU* cpu);
void vk_CreateImage(CPU* cpu);
void vk_DestroyImage(CPU* cpu);
void vk_GetImageSubresourceLayout(CPU* cpu);
void vk_CreateImageView(CPU* cpu);
void vk_DestroyImageView(CPU* cpu);
void vk_CreateShaderModule(CPU* cpu);
void vk_DestroyShaderModule(CPU* cpu);
void vk_CreatePipelineCache(CPU* cpu);
void vk_DestroyPipelineCache(CPU* cpu);
void vk_GetPipelineCacheData(CPU* cpu);
void vk_MergePipelineCaches(CPU* cpu);
void vk_CreateGraphicsPipelines(CPU* cpu);
void vk_CreateComputePipelines(CPU* cpu);
void vk_GetSubpassShadingMaxWorkgroupSizeHUAWEI(CPU* cpu);
void vk_DestroyPipeline(CPU* cpu);
void vk_CreatePipelineLayout(CPU* cpu);
void vk_DestroyPipelineLayout(CPU* cpu);
void vk_CreateSampler(CPU* cpu);
void vk_DestroySampler(CPU* cpu);
void vk_CreateDescriptorSetLayout(CPU* cpu);
void vk_DestroyDescriptorSetLayout(CPU* cpu);
void vk_CreateDescriptorPool(CPU* cpu);
void vk_DestroyDescriptorPool(CPU* cpu);
void vk_ResetDescriptorPool(CPU* cpu);
void vk_AllocateDescriptorSets(CPU* cpu);
void vk_FreeDescriptorSets(CPU* cpu);
void vk_UpdateDescriptorSets(CPU* cpu);
void vk_CreateFramebuffer(CPU* cpu);
void vk_DestroyFramebuffer(CPU* cpu);
void vk_CreateRenderPass(CPU* cpu);
void vk_DestroyRenderPass(CPU* cpu);
void vk_GetRenderAreaGranularity(CPU* cpu);
void vk_CreateCommandPool(CPU* cpu);
void vk_DestroyCommandPool(CPU* cpu);
void vk_ResetCommandPool(CPU* cpu);
void vk_AllocateCommandBuffers(CPU* cpu);
void vk_FreeCommandBuffers(CPU* cpu);
void vk_BeginCommandBuffer(CPU* cpu);
void vk_EndCommandBuffer(CPU* cpu);
void vk_ResetCommandBuffer(CPU* cpu);
void vk_CmdBindPipeline(CPU* cpu);
void vk_CmdSetViewport(CPU* cpu);
void vk_CmdSetScissor(CPU* cpu);
void vk_CmdSetLineWidth(CPU* cpu);
void vk_CmdSetDepthBias(CPU* cpu);
void vk_CmdSetBlendConstants(CPU* cpu);
void vk_CmdSetDepthBounds(CPU* cpu);
void vk_CmdSetStencilCompareMask(CPU* cpu);
void vk_CmdSetStencilWriteMask(CPU* cpu);
void vk_CmdSetStencilReference(CPU* cpu);
void vk_CmdBindDescriptorSets(CPU* cpu);
void vk_CmdBindIndexBuffer(CPU* cpu);
void vk_CmdBindVertexBuffers(CPU* cpu);
void vk_CmdDraw(CPU* cpu);
void vk_CmdDrawIndexed(CPU* cpu);
void vk_CmdDrawMultiEXT(CPU* cpu);
void vk_CmdDrawMultiIndexedEXT(CPU* cpu);
void vk_CmdDrawIndirect(CPU* cpu);
void vk_CmdDrawIndexedIndirect(CPU* cpu);
void vk_CmdDispatch(CPU* cpu);
void vk_CmdDispatchIndirect(CPU* cpu);
void vk_CmdSubpassShadingHUAWEI(CPU* cpu);
void vk_CmdCopyBuffer(CPU* cpu);
void vk_CmdCopyImage(CPU* cpu);
void vk_CmdBlitImage(CPU* cpu);
void vk_CmdCopyBufferToImage(CPU* cpu);
void vk_CmdCopyImageToBuffer(CPU* cpu);
void vk_CmdUpdateBuffer(CPU* cpu);
void vk_CmdFillBuffer(CPU* cpu);
void vk_CmdClearColorImage(CPU* cpu);
void vk_CmdClearDepthStencilImage(CPU* cpu);
void vk_CmdClearAttachments(CPU* cpu);
void vk_CmdResolveImage(CPU* cpu);
void vk_CmdSetEvent(CPU* cpu);
void vk_CmdResetEvent(CPU* cpu);
void vk_CmdWaitEvents(CPU* cpu);
void vk_CmdPipelineBarrier(CPU* cpu);
void vk_CmdBeginQuery(CPU* cpu);
void vk_CmdEndQuery(CPU* cpu);
void vk_CmdBeginConditionalRenderingEXT(CPU* cpu);
void vk_CmdEndConditionalRenderingEXT(CPU* cpu);
void vk_CmdResetQueryPool(CPU* cpu);
void vk_CmdWriteTimestamp(CPU* cpu);
void vk_CmdCopyQueryPoolResults(CPU* cpu);
void vk_CmdPushConstants(CPU* cpu);
void vk_CmdBeginRenderPass(CPU* cpu);
void vk_CmdNextSubpass(CPU* cpu);
void vk_CmdEndRenderPass(CPU* cpu);
void vk_CmdExecuteCommands(CPU* cpu);
void vk_DestroySurfaceKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceSupportKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceCapabilitiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceFormatsKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfacePresentModesKHR(CPU* cpu);
void vk_CreateSwapchainKHR(CPU* cpu);
void vk_DestroySwapchainKHR(CPU* cpu);
void vk_GetSwapchainImagesKHR(CPU* cpu);
void vk_AcquireNextImageKHR(CPU* cpu);
void vk_QueuePresentKHR(CPU* cpu);
void vk_CmdExecuteGeneratedCommandsNV(CPU* cpu);
void vk_CmdPreprocessGeneratedCommandsNV(CPU* cpu);
void vk_CmdBindPipelineShaderGroupNV(CPU* cpu);
void vk_GetGeneratedCommandsMemoryRequirementsNV(CPU* cpu);
void vk_CreateIndirectCommandsLayoutNV(CPU* cpu);
void vk_DestroyIndirectCommandsLayoutNV(CPU* cpu);
void vk_GetPhysicalDeviceFeatures2(CPU* cpu);
void vk_GetPhysicalDeviceFeatures2KHR(CPU* cpu);
void vk_GetPhysicalDeviceProperties2(CPU* cpu);
void vk_GetPhysicalDeviceProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties2(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties2(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties2KHR(CPU* cpu);
void vk_CmdPushDescriptorSetKHR(CPU* cpu);
void vk_TrimCommandPool(CPU* cpu);
void vk_TrimCommandPoolKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalBufferProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalBufferPropertiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalSemaphoreProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalSemaphorePropertiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalFenceProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalFencePropertiesKHR(CPU* cpu);
void vk_EnumeratePhysicalDeviceGroups(CPU* cpu);
void vk_EnumeratePhysicalDeviceGroupsKHR(CPU* cpu);
void vk_GetDeviceGroupPeerMemoryFeatures(CPU* cpu);
void vk_GetDeviceGroupPeerMemoryFeaturesKHR(CPU* cpu);
void vk_BindBufferMemory2(CPU* cpu);
void vk_BindBufferMemory2KHR(CPU* cpu);
void vk_BindImageMemory2(CPU* cpu);
void vk_BindImageMemory2KHR(CPU* cpu);
void vk_CmdSetDeviceMask(CPU* cpu);
void vk_CmdSetDeviceMaskKHR(CPU* cpu);
void vk_GetDeviceGroupPresentCapabilitiesKHR(CPU* cpu);
void vk_GetDeviceGroupSurfacePresentModesKHR(CPU* cpu);
void vk_AcquireNextImage2KHR(CPU* cpu);
void vk_CmdDispatchBase(CPU* cpu);
void vk_CmdDispatchBaseKHR(CPU* cpu);
void vk_GetPhysicalDevicePresentRectanglesKHR(CPU* cpu);
void vk_CreateDescriptorUpdateTemplate(CPU* cpu);
void vk_CreateDescriptorUpdateTemplateKHR(CPU* cpu);
void vk_DestroyDescriptorUpdateTemplate(CPU* cpu);
void vk_DestroyDescriptorUpdateTemplateKHR(CPU* cpu);
void vk_UpdateDescriptorSetWithTemplate(CPU* cpu);
void vk_UpdateDescriptorSetWithTemplateKHR(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplateKHR(CPU* cpu);
void vk_CmdSetViewportWScalingNV(CPU* cpu);
void vk_CmdSetDiscardRectangleEXT(CPU* cpu);
void vk_CmdSetSampleLocationsEXT(CPU* cpu);
void vk_GetPhysicalDeviceMultisamplePropertiesEXT(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceCapabilities2KHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceFormats2KHR(CPU* cpu);
void vk_GetBufferMemoryRequirements2(CPU* cpu);
void vk_GetBufferMemoryRequirements2KHR(CPU* cpu);
void vk_GetImageMemoryRequirements2(CPU* cpu);
void vk_GetImageMemoryRequirements2KHR(CPU* cpu);
void vk_GetImageSparseMemoryRequirements2(CPU* cpu);
void vk_GetImageSparseMemoryRequirements2KHR(CPU* cpu);
void vk_CreateSamplerYcbcrConversion(CPU* cpu);
void vk_CreateSamplerYcbcrConversionKHR(CPU* cpu);
void vk_DestroySamplerYcbcrConversion(CPU* cpu);
void vk_DestroySamplerYcbcrConversionKHR(CPU* cpu);
void vk_GetDeviceQueue2(CPU* cpu);
void vk_CreateValidationCacheEXT(CPU* cpu);
void vk_DestroyValidationCacheEXT(CPU* cpu);
void vk_GetValidationCacheDataEXT(CPU* cpu);
void vk_MergeValidationCachesEXT(CPU* cpu);
void vk_GetDescriptorSetLayoutSupport(CPU* cpu);
void vk_GetDescriptorSetLayoutSupportKHR(CPU* cpu);
void vk_GetShaderInfoAMD(CPU* cpu);
void vk_GetPhysicalDeviceCalibrateableTimeDomainsEXT(CPU* cpu);
void vk_GetCalibratedTimestampsEXT(CPU* cpu);
void vk_GetMemoryHostPointerPropertiesEXT(CPU* cpu);
void vk_CmdWriteBufferMarkerAMD(CPU* cpu);
void vk_CreateRenderPass2(CPU* cpu);
void vk_CreateRenderPass2KHR(CPU* cpu);
void vk_CmdBeginRenderPass2(CPU* cpu);
void vk_CmdBeginRenderPass2KHR(CPU* cpu);
void vk_CmdNextSubpass2(CPU* cpu);
void vk_CmdNextSubpass2KHR(CPU* cpu);
void vk_CmdEndRenderPass2(CPU* cpu);
void vk_CmdEndRenderPass2KHR(CPU* cpu);
void vk_GetSemaphoreCounterValue(CPU* cpu);
void vk_GetSemaphoreCounterValueKHR(CPU* cpu);
void vk_WaitSemaphores(CPU* cpu);
void vk_WaitSemaphoresKHR(CPU* cpu);
void vk_SignalSemaphore(CPU* cpu);
void vk_SignalSemaphoreKHR(CPU* cpu);
void vk_CmdDrawIndirectCount(CPU* cpu);
void vk_CmdDrawIndirectCountKHR(CPU* cpu);
void vk_CmdDrawIndirectCountAMD(CPU* cpu);
void vk_CmdDrawIndexedIndirectCount(CPU* cpu);
void vk_CmdDrawIndexedIndirectCountKHR(CPU* cpu);
void vk_CmdDrawIndexedIndirectCountAMD(CPU* cpu);
void vk_CmdBindTransformFeedbackBuffersEXT(CPU* cpu);
void vk_CmdBeginTransformFeedbackEXT(CPU* cpu);
void vk_CmdEndTransformFeedbackEXT(CPU* cpu);
void vk_CmdBeginQueryIndexedEXT(CPU* cpu);
void vk_CmdEndQueryIndexedEXT(CPU* cpu);
void vk_CmdDrawIndirectByteCountEXT(CPU* cpu);
void vk_CmdSetExclusiveScissorNV(CPU* cpu);
void vk_CmdBindShadingRateImageNV(CPU* cpu);
void vk_CmdSetViewportShadingRatePaletteNV(CPU* cpu);
void vk_CmdSetCoarseSampleOrderNV(CPU* cpu);
void vk_CmdDrawMeshTasksNV(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectNV(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectCountNV(CPU* cpu);
void vk_CompileDeferredNV(CPU* cpu);
void vk_CreateAccelerationStructureNV(CPU* cpu);
void vk_DestroyAccelerationStructureNV(CPU* cpu);
void vk_GetAccelerationStructureMemoryRequirementsNV(CPU* cpu);
void vk_BindAccelerationStructureMemoryNV(CPU* cpu);
void vk_CmdCopyAccelerationStructureNV(CPU* cpu);
void vk_CmdWriteAccelerationStructuresPropertiesNV(CPU* cpu);
void vk_CmdBuildAccelerationStructureNV(CPU* cpu);
void vk_CmdTraceRaysNV(CPU* cpu);
void vk_GetRayTracingShaderGroupHandlesNV(CPU* cpu);
void vk_GetAccelerationStructureHandleNV(CPU* cpu);
void vk_CreateRayTracingPipelinesNV(CPU* cpu);
void vk_GetPhysicalDeviceCooperativeMatrixPropertiesNV(CPU* cpu);
void vk_EnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR(CPU* cpu);
void vk_AcquireProfilingLockKHR(CPU* cpu);
void vk_ReleaseProfilingLockKHR(CPU* cpu);
void vk_GetBufferOpaqueCaptureAddress(CPU* cpu);
void vk_GetBufferOpaqueCaptureAddressKHR(CPU* cpu);
void vk_GetBufferDeviceAddress(CPU* cpu);
void vk_GetBufferDeviceAddressKHR(CPU* cpu);
void vk_GetBufferDeviceAddressEXT(CPU* cpu);
void vk_CreateHeadlessSurfaceEXT(CPU* cpu);
void vk_GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV(CPU* cpu);
void vk_GetDeviceMemoryOpaqueCaptureAddress(CPU* cpu);
void vk_GetDeviceMemoryOpaqueCaptureAddressKHR(CPU* cpu);
void vk_CmdSetLineStippleEXT(CPU* cpu);
void vk_GetPhysicalDeviceToolPropertiesEXT(CPU* cpu);
void vk_CreateDeferredOperationKHR(CPU* cpu);
void vk_DestroyDeferredOperationKHR(CPU* cpu);
void vk_GetDeferredOperationMaxConcurrencyKHR(CPU* cpu);
void vk_GetDeferredOperationResultKHR(CPU* cpu);
void vk_DeferredOperationJoinKHR(CPU* cpu);
void vk_CmdSetCullModeEXT(CPU* cpu);
void vk_CmdSetFrontFaceEXT(CPU* cpu);
void vk_CmdSetPrimitiveTopologyEXT(CPU* cpu);
void vk_CmdSetViewportWithCountEXT(CPU* cpu);
void vk_CmdSetScissorWithCountEXT(CPU* cpu);
void vk_CmdBindVertexBuffers2EXT(CPU* cpu);
void vk_CmdSetDepthTestEnableEXT(CPU* cpu);
void vk_CmdSetDepthWriteEnableEXT(CPU* cpu);
void vk_CmdSetDepthCompareOpEXT(CPU* cpu);
void vk_CmdSetDepthBoundsTestEnableEXT(CPU* cpu);
void vk_CmdSetStencilTestEnableEXT(CPU* cpu);
void vk_CmdSetStencilOpEXT(CPU* cpu);
void vk_CmdSetPatchControlPointsEXT(CPU* cpu);
void vk_CmdSetRasterizerDiscardEnableEXT(CPU* cpu);
void vk_CmdSetDepthBiasEnableEXT(CPU* cpu);
void vk_CmdSetLogicOpEXT(CPU* cpu);
void vk_CmdSetPrimitiveRestartEnableEXT(CPU* cpu);
void vk_CreatePrivateDataSlotEXT(CPU* cpu);
void vk_DestroyPrivateDataSlotEXT(CPU* cpu);
void vk_SetPrivateDataEXT(CPU* cpu);
void vk_GetPrivateDataEXT(CPU* cpu);
void vk_CmdCopyBuffer2KHR(CPU* cpu);
void vk_CmdCopyImage2KHR(CPU* cpu);
void vk_CmdBlitImage2KHR(CPU* cpu);
void vk_CmdCopyBufferToImage2KHR(CPU* cpu);
void vk_CmdCopyImageToBuffer2KHR(CPU* cpu);
void vk_CmdResolveImage2KHR(CPU* cpu);
void vk_CmdSetFragmentShadingRateKHR(CPU* cpu);
void vk_GetPhysicalDeviceFragmentShadingRatesKHR(CPU* cpu);
void vk_CmdSetFragmentShadingRateEnumNV(CPU* cpu);
void vk_CmdSetVertexInputEXT(CPU* cpu);
void vk_CmdSetColorWriteEnableEXT(CPU* cpu);
void vk_CmdSetEvent2KHR(CPU* cpu);
void vk_CmdResetEvent2KHR(CPU* cpu);
void vk_CmdWaitEvents2KHR(CPU* cpu);
void vk_CmdPipelineBarrier2KHR(CPU* cpu);
void vk_QueueSubmit2KHR(CPU* cpu);
void vk_CmdWriteTimestamp2KHR(CPU* cpu);
void vk_CmdWriteBufferMarker2AMD(CPU* cpu);
void vk_GetQueueCheckpointData2NV(CPU* cpu);
class BoxedVulkanInfo {
public:
    VkInstance instance;
    PFN_vkDestroyInstance pvkDestroyInstance;
    PFN_vkEnumeratePhysicalDevices pvkEnumeratePhysicalDevices;
    PFN_vkGetPhysicalDeviceProperties pvkGetPhysicalDeviceProperties;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties pvkGetPhysicalDeviceQueueFamilyProperties;
    PFN_vkGetPhysicalDeviceMemoryProperties pvkGetPhysicalDeviceMemoryProperties;
    PFN_vkGetPhysicalDeviceFeatures pvkGetPhysicalDeviceFeatures;
    PFN_vkGetPhysicalDeviceFormatProperties pvkGetPhysicalDeviceFormatProperties;
    PFN_vkGetPhysicalDeviceImageFormatProperties pvkGetPhysicalDeviceImageFormatProperties;
    PFN_vkCreateDevice pvkCreateDevice;
    PFN_vkDestroyDevice pvkDestroyDevice;
    PFN_vkEnumerateDeviceLayerProperties pvkEnumerateDeviceLayerProperties;
    PFN_vkEnumerateDeviceExtensionProperties pvkEnumerateDeviceExtensionProperties;
    PFN_vkGetDeviceQueue pvkGetDeviceQueue;
    PFN_vkQueueSubmit pvkQueueSubmit;
    PFN_vkQueueWaitIdle pvkQueueWaitIdle;
    PFN_vkDeviceWaitIdle pvkDeviceWaitIdle;
    PFN_vkAllocateMemory pvkAllocateMemory;
    PFN_vkFreeMemory pvkFreeMemory;
    PFN_vkMapMemory pvkMapMemory;
    PFN_vkUnmapMemory pvkUnmapMemory;
    PFN_vkFlushMappedMemoryRanges pvkFlushMappedMemoryRanges;
    PFN_vkInvalidateMappedMemoryRanges pvkInvalidateMappedMemoryRanges;
    PFN_vkGetDeviceMemoryCommitment pvkGetDeviceMemoryCommitment;
    PFN_vkGetBufferMemoryRequirements pvkGetBufferMemoryRequirements;
    PFN_vkBindBufferMemory pvkBindBufferMemory;
    PFN_vkGetImageMemoryRequirements pvkGetImageMemoryRequirements;
    PFN_vkBindImageMemory pvkBindImageMemory;
    PFN_vkGetImageSparseMemoryRequirements pvkGetImageSparseMemoryRequirements;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties pvkGetPhysicalDeviceSparseImageFormatProperties;
    PFN_vkQueueBindSparse pvkQueueBindSparse;
    PFN_vkCreateFence pvkCreateFence;
    PFN_vkDestroyFence pvkDestroyFence;
    PFN_vkResetFences pvkResetFences;
    PFN_vkGetFenceStatus pvkGetFenceStatus;
    PFN_vkWaitForFences pvkWaitForFences;
    PFN_vkCreateSemaphore pvkCreateSemaphore;
    PFN_vkDestroySemaphore pvkDestroySemaphore;
    PFN_vkCreateEvent pvkCreateEvent;
    PFN_vkDestroyEvent pvkDestroyEvent;
    PFN_vkGetEventStatus pvkGetEventStatus;
    PFN_vkSetEvent pvkSetEvent;
    PFN_vkResetEvent pvkResetEvent;
    PFN_vkCreateQueryPool pvkCreateQueryPool;
    PFN_vkDestroyQueryPool pvkDestroyQueryPool;
    PFN_vkGetQueryPoolResults pvkGetQueryPoolResults;
    PFN_vkResetQueryPool pvkResetQueryPool;
    PFN_vkResetQueryPoolEXT pvkResetQueryPoolEXT;
    PFN_vkCreateBuffer pvkCreateBuffer;
    PFN_vkDestroyBuffer pvkDestroyBuffer;
    PFN_vkCreateBufferView pvkCreateBufferView;
    PFN_vkDestroyBufferView pvkDestroyBufferView;
    PFN_vkCreateImage pvkCreateImage;
    PFN_vkDestroyImage pvkDestroyImage;
    PFN_vkGetImageSubresourceLayout pvkGetImageSubresourceLayout;
    PFN_vkCreateImageView pvkCreateImageView;
    PFN_vkDestroyImageView pvkDestroyImageView;
    PFN_vkCreateShaderModule pvkCreateShaderModule;
    PFN_vkDestroyShaderModule pvkDestroyShaderModule;
    PFN_vkCreatePipelineCache pvkCreatePipelineCache;
    PFN_vkDestroyPipelineCache pvkDestroyPipelineCache;
    PFN_vkGetPipelineCacheData pvkGetPipelineCacheData;
    PFN_vkMergePipelineCaches pvkMergePipelineCaches;
    PFN_vkCreateGraphicsPipelines pvkCreateGraphicsPipelines;
    PFN_vkCreateComputePipelines pvkCreateComputePipelines;
    PFN_vkDestroyPipeline pvkDestroyPipeline;
    PFN_vkCreatePipelineLayout pvkCreatePipelineLayout;
    PFN_vkDestroyPipelineLayout pvkDestroyPipelineLayout;
    PFN_vkCreateSampler pvkCreateSampler;
    PFN_vkDestroySampler pvkDestroySampler;
    PFN_vkCreateDescriptorSetLayout pvkCreateDescriptorSetLayout;
    PFN_vkDestroyDescriptorSetLayout pvkDestroyDescriptorSetLayout;
    PFN_vkCreateDescriptorPool pvkCreateDescriptorPool;
    PFN_vkDestroyDescriptorPool pvkDestroyDescriptorPool;
    PFN_vkResetDescriptorPool pvkResetDescriptorPool;
    PFN_vkAllocateDescriptorSets pvkAllocateDescriptorSets;
    PFN_vkFreeDescriptorSets pvkFreeDescriptorSets;
    PFN_vkUpdateDescriptorSets pvkUpdateDescriptorSets;
    PFN_vkCreateFramebuffer pvkCreateFramebuffer;
    PFN_vkDestroyFramebuffer pvkDestroyFramebuffer;
    PFN_vkCreateRenderPass pvkCreateRenderPass;
    PFN_vkDestroyRenderPass pvkDestroyRenderPass;
    PFN_vkGetRenderAreaGranularity pvkGetRenderAreaGranularity;
    PFN_vkCreateCommandPool pvkCreateCommandPool;
    PFN_vkDestroyCommandPool pvkDestroyCommandPool;
    PFN_vkResetCommandPool pvkResetCommandPool;
    PFN_vkAllocateCommandBuffers pvkAllocateCommandBuffers;
    PFN_vkFreeCommandBuffers pvkFreeCommandBuffers;
    PFN_vkBeginCommandBuffer pvkBeginCommandBuffer;
    PFN_vkEndCommandBuffer pvkEndCommandBuffer;
    PFN_vkResetCommandBuffer pvkResetCommandBuffer;
    PFN_vkCmdBindPipeline pvkCmdBindPipeline;
    PFN_vkCmdSetViewport pvkCmdSetViewport;
    PFN_vkCmdSetScissor pvkCmdSetScissor;
    PFN_vkCmdSetLineWidth pvkCmdSetLineWidth;
    PFN_vkCmdSetDepthBias pvkCmdSetDepthBias;
    PFN_vkCmdSetBlendConstants pvkCmdSetBlendConstants;
    PFN_vkCmdSetDepthBounds pvkCmdSetDepthBounds;
    PFN_vkCmdSetStencilCompareMask pvkCmdSetStencilCompareMask;
    PFN_vkCmdSetStencilWriteMask pvkCmdSetStencilWriteMask;
    PFN_vkCmdSetStencilReference pvkCmdSetStencilReference;
    PFN_vkCmdBindDescriptorSets pvkCmdBindDescriptorSets;
    PFN_vkCmdBindIndexBuffer pvkCmdBindIndexBuffer;
    PFN_vkCmdBindVertexBuffers pvkCmdBindVertexBuffers;
    PFN_vkCmdDraw pvkCmdDraw;
    PFN_vkCmdDrawIndexed pvkCmdDrawIndexed;
    PFN_vkCmdDrawMultiEXT pvkCmdDrawMultiEXT;
    PFN_vkCmdDrawMultiIndexedEXT pvkCmdDrawMultiIndexedEXT;
    PFN_vkCmdDrawIndirect pvkCmdDrawIndirect;
    PFN_vkCmdDrawIndexedIndirect pvkCmdDrawIndexedIndirect;
    PFN_vkCmdDispatch pvkCmdDispatch;
    PFN_vkCmdDispatchIndirect pvkCmdDispatchIndirect;
    PFN_vkCmdSubpassShadingHUAWEI pvkCmdSubpassShadingHUAWEI;
    PFN_vkCmdCopyBuffer pvkCmdCopyBuffer;
    PFN_vkCmdCopyImage pvkCmdCopyImage;
    PFN_vkCmdBlitImage pvkCmdBlitImage;
    PFN_vkCmdCopyBufferToImage pvkCmdCopyBufferToImage;
    PFN_vkCmdCopyImageToBuffer pvkCmdCopyImageToBuffer;
    PFN_vkCmdUpdateBuffer pvkCmdUpdateBuffer;
    PFN_vkCmdFillBuffer pvkCmdFillBuffer;
    PFN_vkCmdClearColorImage pvkCmdClearColorImage;
    PFN_vkCmdClearDepthStencilImage pvkCmdClearDepthStencilImage;
    PFN_vkCmdClearAttachments pvkCmdClearAttachments;
    PFN_vkCmdResolveImage pvkCmdResolveImage;
    PFN_vkCmdSetEvent pvkCmdSetEvent;
    PFN_vkCmdResetEvent pvkCmdResetEvent;
    PFN_vkCmdWaitEvents pvkCmdWaitEvents;
    PFN_vkCmdPipelineBarrier pvkCmdPipelineBarrier;
    PFN_vkCmdBeginQuery pvkCmdBeginQuery;
    PFN_vkCmdEndQuery pvkCmdEndQuery;
    PFN_vkCmdBeginConditionalRenderingEXT pvkCmdBeginConditionalRenderingEXT;
    PFN_vkCmdEndConditionalRenderingEXT pvkCmdEndConditionalRenderingEXT;
    PFN_vkCmdResetQueryPool pvkCmdResetQueryPool;
    PFN_vkCmdWriteTimestamp pvkCmdWriteTimestamp;
    PFN_vkCmdCopyQueryPoolResults pvkCmdCopyQueryPoolResults;
    PFN_vkCmdPushConstants pvkCmdPushConstants;
    PFN_vkCmdBeginRenderPass pvkCmdBeginRenderPass;
    PFN_vkCmdNextSubpass pvkCmdNextSubpass;
    PFN_vkCmdEndRenderPass pvkCmdEndRenderPass;
    PFN_vkCmdExecuteCommands pvkCmdExecuteCommands;
    PFN_vkDestroySurfaceKHR pvkDestroySurfaceKHR;
    PFN_vkGetPhysicalDeviceSurfaceSupportKHR pvkGetPhysicalDeviceSurfaceSupportKHR;
    PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR pvkGetPhysicalDeviceSurfaceCapabilitiesKHR;
    PFN_vkGetPhysicalDeviceSurfaceFormatsKHR pvkGetPhysicalDeviceSurfaceFormatsKHR;
    PFN_vkGetPhysicalDeviceSurfacePresentModesKHR pvkGetPhysicalDeviceSurfacePresentModesKHR;
    PFN_vkCreateSwapchainKHR pvkCreateSwapchainKHR;
    PFN_vkDestroySwapchainKHR pvkDestroySwapchainKHR;
    PFN_vkGetSwapchainImagesKHR pvkGetSwapchainImagesKHR;
    PFN_vkAcquireNextImageKHR pvkAcquireNextImageKHR;
    PFN_vkQueuePresentKHR pvkQueuePresentKHR;
    PFN_vkCmdExecuteGeneratedCommandsNV pvkCmdExecuteGeneratedCommandsNV;
    PFN_vkCmdPreprocessGeneratedCommandsNV pvkCmdPreprocessGeneratedCommandsNV;
    PFN_vkCmdBindPipelineShaderGroupNV pvkCmdBindPipelineShaderGroupNV;
    PFN_vkGetGeneratedCommandsMemoryRequirementsNV pvkGetGeneratedCommandsMemoryRequirementsNV;
    PFN_vkCreateIndirectCommandsLayoutNV pvkCreateIndirectCommandsLayoutNV;
    PFN_vkDestroyIndirectCommandsLayoutNV pvkDestroyIndirectCommandsLayoutNV;
    PFN_vkGetPhysicalDeviceFeatures2 pvkGetPhysicalDeviceFeatures2;
    PFN_vkGetPhysicalDeviceFeatures2KHR pvkGetPhysicalDeviceFeatures2KHR;
    PFN_vkGetPhysicalDeviceProperties2 pvkGetPhysicalDeviceProperties2;
    PFN_vkGetPhysicalDeviceProperties2KHR pvkGetPhysicalDeviceProperties2KHR;
    PFN_vkGetPhysicalDeviceFormatProperties2 pvkGetPhysicalDeviceFormatProperties2;
    PFN_vkGetPhysicalDeviceFormatProperties2KHR pvkGetPhysicalDeviceFormatProperties2KHR;
    PFN_vkGetPhysicalDeviceImageFormatProperties2 pvkGetPhysicalDeviceImageFormatProperties2;
    PFN_vkGetPhysicalDeviceImageFormatProperties2KHR pvkGetPhysicalDeviceImageFormatProperties2KHR;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties2 pvkGetPhysicalDeviceQueueFamilyProperties2;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties2KHR pvkGetPhysicalDeviceQueueFamilyProperties2KHR;
    PFN_vkGetPhysicalDeviceMemoryProperties2 pvkGetPhysicalDeviceMemoryProperties2;
    PFN_vkGetPhysicalDeviceMemoryProperties2KHR pvkGetPhysicalDeviceMemoryProperties2KHR;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties2 pvkGetPhysicalDeviceSparseImageFormatProperties2;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties2KHR pvkGetPhysicalDeviceSparseImageFormatProperties2KHR;
    PFN_vkCmdPushDescriptorSetKHR pvkCmdPushDescriptorSetKHR;
    PFN_vkTrimCommandPool pvkTrimCommandPool;
    PFN_vkTrimCommandPoolKHR pvkTrimCommandPoolKHR;
    PFN_vkGetPhysicalDeviceExternalBufferProperties pvkGetPhysicalDeviceExternalBufferProperties;
    PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR pvkGetPhysicalDeviceExternalBufferPropertiesKHR;
    PFN_vkGetPhysicalDeviceExternalSemaphoreProperties pvkGetPhysicalDeviceExternalSemaphoreProperties;
    PFN_vkGetPhysicalDeviceExternalSemaphorePropertiesKHR pvkGetPhysicalDeviceExternalSemaphorePropertiesKHR;
    PFN_vkGetPhysicalDeviceExternalFenceProperties pvkGetPhysicalDeviceExternalFenceProperties;
    PFN_vkGetPhysicalDeviceExternalFencePropertiesKHR pvkGetPhysicalDeviceExternalFencePropertiesKHR;
    PFN_vkEnumeratePhysicalDeviceGroups pvkEnumeratePhysicalDeviceGroups;
    PFN_vkEnumeratePhysicalDeviceGroupsKHR pvkEnumeratePhysicalDeviceGroupsKHR;
    PFN_vkGetDeviceGroupPeerMemoryFeatures pvkGetDeviceGroupPeerMemoryFeatures;
    PFN_vkGetDeviceGroupPeerMemoryFeaturesKHR pvkGetDeviceGroupPeerMemoryFeaturesKHR;
    PFN_vkBindBufferMemory2 pvkBindBufferMemory2;
    PFN_vkBindBufferMemory2KHR pvkBindBufferMemory2KHR;
    PFN_vkBindImageMemory2 pvkBindImageMemory2;
    PFN_vkBindImageMemory2KHR pvkBindImageMemory2KHR;
    PFN_vkCmdSetDeviceMask pvkCmdSetDeviceMask;
    PFN_vkCmdSetDeviceMaskKHR pvkCmdSetDeviceMaskKHR;
    PFN_vkGetDeviceGroupPresentCapabilitiesKHR pvkGetDeviceGroupPresentCapabilitiesKHR;
    PFN_vkGetDeviceGroupSurfacePresentModesKHR pvkGetDeviceGroupSurfacePresentModesKHR;
    PFN_vkAcquireNextImage2KHR pvkAcquireNextImage2KHR;
    PFN_vkCmdDispatchBase pvkCmdDispatchBase;
    PFN_vkCmdDispatchBaseKHR pvkCmdDispatchBaseKHR;
    PFN_vkGetPhysicalDevicePresentRectanglesKHR pvkGetPhysicalDevicePresentRectanglesKHR;
    PFN_vkCreateDescriptorUpdateTemplate pvkCreateDescriptorUpdateTemplate;
    PFN_vkCreateDescriptorUpdateTemplateKHR pvkCreateDescriptorUpdateTemplateKHR;
    PFN_vkDestroyDescriptorUpdateTemplate pvkDestroyDescriptorUpdateTemplate;
    PFN_vkDestroyDescriptorUpdateTemplateKHR pvkDestroyDescriptorUpdateTemplateKHR;
    PFN_vkUpdateDescriptorSetWithTemplate pvkUpdateDescriptorSetWithTemplate;
    PFN_vkUpdateDescriptorSetWithTemplateKHR pvkUpdateDescriptorSetWithTemplateKHR;
    PFN_vkCmdPushDescriptorSetWithTemplateKHR pvkCmdPushDescriptorSetWithTemplateKHR;
    PFN_vkCmdSetViewportWScalingNV pvkCmdSetViewportWScalingNV;
    PFN_vkCmdSetDiscardRectangleEXT pvkCmdSetDiscardRectangleEXT;
    PFN_vkCmdSetSampleLocationsEXT pvkCmdSetSampleLocationsEXT;
    PFN_vkGetPhysicalDeviceMultisamplePropertiesEXT pvkGetPhysicalDeviceMultisamplePropertiesEXT;
    PFN_vkGetPhysicalDeviceSurfaceCapabilities2KHR pvkGetPhysicalDeviceSurfaceCapabilities2KHR;
    PFN_vkGetPhysicalDeviceSurfaceFormats2KHR pvkGetPhysicalDeviceSurfaceFormats2KHR;
    PFN_vkGetBufferMemoryRequirements2 pvkGetBufferMemoryRequirements2;
    PFN_vkGetBufferMemoryRequirements2KHR pvkGetBufferMemoryRequirements2KHR;
    PFN_vkGetImageMemoryRequirements2 pvkGetImageMemoryRequirements2;
    PFN_vkGetImageMemoryRequirements2KHR pvkGetImageMemoryRequirements2KHR;
    PFN_vkGetImageSparseMemoryRequirements2 pvkGetImageSparseMemoryRequirements2;
    PFN_vkGetImageSparseMemoryRequirements2KHR pvkGetImageSparseMemoryRequirements2KHR;
    PFN_vkCreateSamplerYcbcrConversion pvkCreateSamplerYcbcrConversion;
    PFN_vkCreateSamplerYcbcrConversionKHR pvkCreateSamplerYcbcrConversionKHR;
    PFN_vkDestroySamplerYcbcrConversion pvkDestroySamplerYcbcrConversion;
    PFN_vkDestroySamplerYcbcrConversionKHR pvkDestroySamplerYcbcrConversionKHR;
    PFN_vkGetDeviceQueue2 pvkGetDeviceQueue2;
    PFN_vkCreateValidationCacheEXT pvkCreateValidationCacheEXT;
    PFN_vkDestroyValidationCacheEXT pvkDestroyValidationCacheEXT;
    PFN_vkGetValidationCacheDataEXT pvkGetValidationCacheDataEXT;
    PFN_vkMergeValidationCachesEXT pvkMergeValidationCachesEXT;
    PFN_vkGetDescriptorSetLayoutSupport pvkGetDescriptorSetLayoutSupport;
    PFN_vkGetDescriptorSetLayoutSupportKHR pvkGetDescriptorSetLayoutSupportKHR;
    PFN_vkGetShaderInfoAMD pvkGetShaderInfoAMD;
    PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsEXT pvkGetPhysicalDeviceCalibrateableTimeDomainsEXT;
    PFN_vkGetCalibratedTimestampsEXT pvkGetCalibratedTimestampsEXT;
    PFN_vkGetMemoryHostPointerPropertiesEXT pvkGetMemoryHostPointerPropertiesEXT;
    PFN_vkCmdWriteBufferMarkerAMD pvkCmdWriteBufferMarkerAMD;
    PFN_vkCreateRenderPass2 pvkCreateRenderPass2;
    PFN_vkCreateRenderPass2KHR pvkCreateRenderPass2KHR;
    PFN_vkCmdBeginRenderPass2 pvkCmdBeginRenderPass2;
    PFN_vkCmdBeginRenderPass2KHR pvkCmdBeginRenderPass2KHR;
    PFN_vkCmdNextSubpass2 pvkCmdNextSubpass2;
    PFN_vkCmdNextSubpass2KHR pvkCmdNextSubpass2KHR;
    PFN_vkCmdEndRenderPass2 pvkCmdEndRenderPass2;
    PFN_vkCmdEndRenderPass2KHR pvkCmdEndRenderPass2KHR;
    PFN_vkGetSemaphoreCounterValue pvkGetSemaphoreCounterValue;
    PFN_vkGetSemaphoreCounterValueKHR pvkGetSemaphoreCounterValueKHR;
    PFN_vkWaitSemaphores pvkWaitSemaphores;
    PFN_vkWaitSemaphoresKHR pvkWaitSemaphoresKHR;
    PFN_vkSignalSemaphore pvkSignalSemaphore;
    PFN_vkSignalSemaphoreKHR pvkSignalSemaphoreKHR;
    PFN_vkCmdDrawIndirectCount pvkCmdDrawIndirectCount;
    PFN_vkCmdDrawIndirectCountKHR pvkCmdDrawIndirectCountKHR;
    PFN_vkCmdDrawIndirectCountAMD pvkCmdDrawIndirectCountAMD;
    PFN_vkCmdDrawIndexedIndirectCount pvkCmdDrawIndexedIndirectCount;
    PFN_vkCmdDrawIndexedIndirectCountKHR pvkCmdDrawIndexedIndirectCountKHR;
    PFN_vkCmdDrawIndexedIndirectCountAMD pvkCmdDrawIndexedIndirectCountAMD;
    PFN_vkCmdBindTransformFeedbackBuffersEXT pvkCmdBindTransformFeedbackBuffersEXT;
    PFN_vkCmdBeginTransformFeedbackEXT pvkCmdBeginTransformFeedbackEXT;
    PFN_vkCmdEndTransformFeedbackEXT pvkCmdEndTransformFeedbackEXT;
    PFN_vkCmdBeginQueryIndexedEXT pvkCmdBeginQueryIndexedEXT;
    PFN_vkCmdEndQueryIndexedEXT pvkCmdEndQueryIndexedEXT;
    PFN_vkCmdDrawIndirectByteCountEXT pvkCmdDrawIndirectByteCountEXT;
    PFN_vkCmdSetExclusiveScissorNV pvkCmdSetExclusiveScissorNV;
    PFN_vkCmdBindShadingRateImageNV pvkCmdBindShadingRateImageNV;
    PFN_vkCmdSetViewportShadingRatePaletteNV pvkCmdSetViewportShadingRatePaletteNV;
    PFN_vkCmdSetCoarseSampleOrderNV pvkCmdSetCoarseSampleOrderNV;
    PFN_vkCmdDrawMeshTasksNV pvkCmdDrawMeshTasksNV;
    PFN_vkCmdDrawMeshTasksIndirectNV pvkCmdDrawMeshTasksIndirectNV;
    PFN_vkCmdDrawMeshTasksIndirectCountNV pvkCmdDrawMeshTasksIndirectCountNV;
    PFN_vkCompileDeferredNV pvkCompileDeferredNV;
    PFN_vkCreateAccelerationStructureNV pvkCreateAccelerationStructureNV;
    PFN_vkDestroyAccelerationStructureNV pvkDestroyAccelerationStructureNV;
    PFN_vkGetAccelerationStructureMemoryRequirementsNV pvkGetAccelerationStructureMemoryRequirementsNV;
    PFN_vkBindAccelerationStructureMemoryNV pvkBindAccelerationStructureMemoryNV;
    PFN_vkCmdCopyAccelerationStructureNV pvkCmdCopyAccelerationStructureNV;
    PFN_vkCmdWriteAccelerationStructuresPropertiesNV pvkCmdWriteAccelerationStructuresPropertiesNV;
    PFN_vkCmdBuildAccelerationStructureNV pvkCmdBuildAccelerationStructureNV;
    PFN_vkCmdTraceRaysNV pvkCmdTraceRaysNV;
    PFN_vkGetRayTracingShaderGroupHandlesNV pvkGetRayTracingShaderGroupHandlesNV;
    PFN_vkGetAccelerationStructureHandleNV pvkGetAccelerationStructureHandleNV;
    PFN_vkCreateRayTracingPipelinesNV pvkCreateRayTracingPipelinesNV;
    PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesNV pvkGetPhysicalDeviceCooperativeMatrixPropertiesNV;
    PFN_vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR pvkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR;
    PFN_vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR pvkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR;
    PFN_vkAcquireProfilingLockKHR pvkAcquireProfilingLockKHR;
    PFN_vkReleaseProfilingLockKHR pvkReleaseProfilingLockKHR;
    PFN_vkGetBufferOpaqueCaptureAddress pvkGetBufferOpaqueCaptureAddress;
    PFN_vkGetBufferOpaqueCaptureAddressKHR pvkGetBufferOpaqueCaptureAddressKHR;
    PFN_vkGetBufferDeviceAddress pvkGetBufferDeviceAddress;
    PFN_vkGetBufferDeviceAddressKHR pvkGetBufferDeviceAddressKHR;
    PFN_vkGetBufferDeviceAddressEXT pvkGetBufferDeviceAddressEXT;
    PFN_vkCreateHeadlessSurfaceEXT pvkCreateHeadlessSurfaceEXT;
    PFN_vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV pvkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV;
    PFN_vkGetDeviceMemoryOpaqueCaptureAddress pvkGetDeviceMemoryOpaqueCaptureAddress;
    PFN_vkGetDeviceMemoryOpaqueCaptureAddressKHR pvkGetDeviceMemoryOpaqueCaptureAddressKHR;
    PFN_vkCmdSetLineStippleEXT pvkCmdSetLineStippleEXT;
    PFN_vkGetPhysicalDeviceToolPropertiesEXT pvkGetPhysicalDeviceToolPropertiesEXT;
    PFN_vkCreateDeferredOperationKHR pvkCreateDeferredOperationKHR;
    PFN_vkDestroyDeferredOperationKHR pvkDestroyDeferredOperationKHR;
    PFN_vkGetDeferredOperationMaxConcurrencyKHR pvkGetDeferredOperationMaxConcurrencyKHR;
    PFN_vkGetDeferredOperationResultKHR pvkGetDeferredOperationResultKHR;
    PFN_vkDeferredOperationJoinKHR pvkDeferredOperationJoinKHR;
    PFN_vkCmdSetCullModeEXT pvkCmdSetCullModeEXT;
    PFN_vkCmdSetFrontFaceEXT pvkCmdSetFrontFaceEXT;
    PFN_vkCmdSetPrimitiveTopologyEXT pvkCmdSetPrimitiveTopologyEXT;
    PFN_vkCmdSetViewportWithCountEXT pvkCmdSetViewportWithCountEXT;
    PFN_vkCmdSetScissorWithCountEXT pvkCmdSetScissorWithCountEXT;
    PFN_vkCmdBindVertexBuffers2EXT pvkCmdBindVertexBuffers2EXT;
    PFN_vkCmdSetDepthTestEnableEXT pvkCmdSetDepthTestEnableEXT;
    PFN_vkCmdSetDepthWriteEnableEXT pvkCmdSetDepthWriteEnableEXT;
    PFN_vkCmdSetDepthCompareOpEXT pvkCmdSetDepthCompareOpEXT;
    PFN_vkCmdSetDepthBoundsTestEnableEXT pvkCmdSetDepthBoundsTestEnableEXT;
    PFN_vkCmdSetStencilTestEnableEXT pvkCmdSetStencilTestEnableEXT;
    PFN_vkCmdSetStencilOpEXT pvkCmdSetStencilOpEXT;
    PFN_vkCmdSetPatchControlPointsEXT pvkCmdSetPatchControlPointsEXT;
    PFN_vkCmdSetRasterizerDiscardEnableEXT pvkCmdSetRasterizerDiscardEnableEXT;
    PFN_vkCmdSetDepthBiasEnableEXT pvkCmdSetDepthBiasEnableEXT;
    PFN_vkCmdSetLogicOpEXT pvkCmdSetLogicOpEXT;
    PFN_vkCmdSetPrimitiveRestartEnableEXT pvkCmdSetPrimitiveRestartEnableEXT;
    PFN_vkCreatePrivateDataSlotEXT pvkCreatePrivateDataSlotEXT;
    PFN_vkDestroyPrivateDataSlotEXT pvkDestroyPrivateDataSlotEXT;
    PFN_vkSetPrivateDataEXT pvkSetPrivateDataEXT;
    PFN_vkGetPrivateDataEXT pvkGetPrivateDataEXT;
    PFN_vkCmdCopyBuffer2KHR pvkCmdCopyBuffer2KHR;
    PFN_vkCmdCopyImage2KHR pvkCmdCopyImage2KHR;
    PFN_vkCmdBlitImage2KHR pvkCmdBlitImage2KHR;
    PFN_vkCmdCopyBufferToImage2KHR pvkCmdCopyBufferToImage2KHR;
    PFN_vkCmdCopyImageToBuffer2KHR pvkCmdCopyImageToBuffer2KHR;
    PFN_vkCmdResolveImage2KHR pvkCmdResolveImage2KHR;
    PFN_vkCmdSetFragmentShadingRateKHR pvkCmdSetFragmentShadingRateKHR;
    PFN_vkGetPhysicalDeviceFragmentShadingRatesKHR pvkGetPhysicalDeviceFragmentShadingRatesKHR;
    PFN_vkCmdSetFragmentShadingRateEnumNV pvkCmdSetFragmentShadingRateEnumNV;
    PFN_vkCmdSetVertexInputEXT pvkCmdSetVertexInputEXT;
    PFN_vkCmdSetColorWriteEnableEXT pvkCmdSetColorWriteEnableEXT;
    PFN_vkCmdSetEvent2KHR pvkCmdSetEvent2KHR;
    PFN_vkCmdResetEvent2KHR pvkCmdResetEvent2KHR;
    PFN_vkCmdWaitEvents2KHR pvkCmdWaitEvents2KHR;
    PFN_vkCmdPipelineBarrier2KHR pvkCmdPipelineBarrier2KHR;
    PFN_vkQueueSubmit2KHR pvkQueueSubmit2KHR;
    PFN_vkCmdWriteTimestamp2KHR pvkCmdWriteTimestamp2KHR;
    PFN_vkCmdWriteBufferMarker2AMD pvkCmdWriteBufferMarker2AMD;
    PFN_vkGetQueueCheckpointData2NV pvkGetQueueCheckpointData2NV;
    std::unordered_map<BString, U32> functionAddressByName;
};
#endif
