#ifndef __VK_HOST__H__
#define __VK_HOST__H__
#include <unordered_set>
#define VK_NO_PROTOTYPES
#include "vk/vulkan.h"
#include "vk/vulkan_core.h"
#ifndef BOXED_VK_EXTERN
#define BOXED_VK_EXTERN extern
#endif
class MarshalVkDescriptorUpdateTemplateCreateInfo;
class MarshalVkImageCreateInfo;
class BoxedVulkanInfo;
class MarshalCallbackData;
VkBaseOutStructure* vulkanGetNextPtr(BoxedVulkanInfo* pBoxedInfo, KMemory* memory, U32 address);
void vulkanDeleteNextPtr(const void* pNext);
U32 createVulkanPtr(KMemory* memory, void* value, BoxedVulkanInfo* info);
BoxedVulkanInfo* createVulkanDeviceInfo(VkDevice device, BoxedVulkanInfo* instanceInfo);
void vulkanWriteNextPtr(BoxedVulkanInfo* pBoxedInfo, KMemory* memory, U32 address, const void* pNext);
void* getVulkanPtr(KMemory* memory, U32 address);
BOXED_VK_EXTERN PFN_vkCreateInstance pvkCreateInstance;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceVersion pvkEnumerateInstanceVersion;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceLayerProperties pvkEnumerateInstanceLayerProperties;
BOXED_VK_EXTERN PFN_vkEnumerateInstanceExtensionProperties pvkEnumerateInstanceExtensionProperties;
void vk_CreateInstance(CPU* cpu);
void vk_DestroyInstance(CPU* cpu);
void vk_EnumeratePhysicalDevices(CPU* cpu);
void vk_GetDeviceProcAddr(CPU* cpu);
void vk_GetInstanceProcAddr(CPU* cpu);
void vk_GetPhysicalDeviceProperties(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties(CPU* cpu);
void vk_GetPhysicalDeviceFeatures(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties(CPU* cpu);
void vk_CreateDevice(CPU* cpu);
void vk_DestroyDevice(CPU* cpu);
void vk_EnumerateInstanceVersion(CPU* cpu);
void vk_EnumerateInstanceLayerProperties(CPU* cpu);
void vk_EnumerateInstanceExtensionProperties(CPU* cpu);
void vk_EnumerateDeviceLayerProperties(CPU* cpu);
void vk_EnumerateDeviceExtensionProperties(CPU* cpu);
void vk_GetDeviceQueue(CPU* cpu);
void vk_QueueSubmit(CPU* cpu);
void vk_QueueWaitIdle(CPU* cpu);
void vk_DeviceWaitIdle(CPU* cpu);
void vk_AllocateMemory(CPU* cpu);
void vk_FreeMemory(CPU* cpu);
void vk_MapMemory(CPU* cpu);
void vk_UnmapMemory(CPU* cpu);
void vk_FlushMappedMemoryRanges(CPU* cpu);
void vk_InvalidateMappedMemoryRanges(CPU* cpu);
void vk_GetDeviceMemoryCommitment(CPU* cpu);
void vk_GetBufferMemoryRequirements(CPU* cpu);
void vk_BindBufferMemory(CPU* cpu);
void vk_GetImageMemoryRequirements(CPU* cpu);
void vk_BindImageMemory(CPU* cpu);
void vk_GetImageSparseMemoryRequirements(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties(CPU* cpu);
void vk_QueueBindSparse(CPU* cpu);
void vk_CreateFence(CPU* cpu);
void vk_DestroyFence(CPU* cpu);
void vk_ResetFences(CPU* cpu);
void vk_GetFenceStatus(CPU* cpu);
void vk_WaitForFences(CPU* cpu);
void vk_CreateSemaphore(CPU* cpu);
void vk_DestroySemaphore(CPU* cpu);
void vk_CreateEvent(CPU* cpu);
void vk_DestroyEvent(CPU* cpu);
void vk_GetEventStatus(CPU* cpu);
void vk_SetEvent(CPU* cpu);
void vk_ResetEvent(CPU* cpu);
void vk_CreateQueryPool(CPU* cpu);
void vk_DestroyQueryPool(CPU* cpu);
void vk_GetQueryPoolResults(CPU* cpu);
void vk_ResetQueryPool(CPU* cpu);
void vk_ResetQueryPoolEXT(CPU* cpu);
void vk_CreateBuffer(CPU* cpu);
void vk_DestroyBuffer(CPU* cpu);
void vk_CreateBufferView(CPU* cpu);
void vk_DestroyBufferView(CPU* cpu);
void vk_CreateImage(CPU* cpu);
void vk_DestroyImage(CPU* cpu);
void vk_GetImageSubresourceLayout(CPU* cpu);
void vk_CreateImageView(CPU* cpu);
void vk_DestroyImageView(CPU* cpu);
void vk_CreateShaderModule(CPU* cpu);
void vk_DestroyShaderModule(CPU* cpu);
void vk_CreatePipelineCache(CPU* cpu);
void vk_DestroyPipelineCache(CPU* cpu);
void vk_GetPipelineCacheData(CPU* cpu);
void vk_MergePipelineCaches(CPU* cpu);
void vk_CreatePipelineBinariesKHR(CPU* cpu);
void vk_DestroyPipelineBinaryKHR(CPU* cpu);
void vk_GetPipelineKeyKHR(CPU* cpu);
void vk_GetPipelineBinaryDataKHR(CPU* cpu);
void vk_ReleaseCapturedPipelineDataKHR(CPU* cpu);
void vk_CreateGraphicsPipelines(CPU* cpu);
void vk_CreateComputePipelines(CPU* cpu);
void vk_GetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI(CPU* cpu);
void vk_DestroyPipeline(CPU* cpu);
void vk_CreatePipelineLayout(CPU* cpu);
void vk_DestroyPipelineLayout(CPU* cpu);
void vk_CreateSampler(CPU* cpu);
void vk_DestroySampler(CPU* cpu);
void vk_CreateDescriptorSetLayout(CPU* cpu);
void vk_DestroyDescriptorSetLayout(CPU* cpu);
void vk_CreateDescriptorPool(CPU* cpu);
void vk_DestroyDescriptorPool(CPU* cpu);
void vk_ResetDescriptorPool(CPU* cpu);
void vk_AllocateDescriptorSets(CPU* cpu);
void vk_FreeDescriptorSets(CPU* cpu);
void vk_UpdateDescriptorSets(CPU* cpu);
void vk_CreateFramebuffer(CPU* cpu);
void vk_DestroyFramebuffer(CPU* cpu);
void vk_CreateRenderPass(CPU* cpu);
void vk_DestroyRenderPass(CPU* cpu);
void vk_GetRenderAreaGranularity(CPU* cpu);
void vk_GetRenderingAreaGranularity(CPU* cpu);
void vk_GetRenderingAreaGranularityKHR(CPU* cpu);
void vk_CreateCommandPool(CPU* cpu);
void vk_DestroyCommandPool(CPU* cpu);
void vk_ResetCommandPool(CPU* cpu);
void vk_AllocateCommandBuffers(CPU* cpu);
void vk_FreeCommandBuffers(CPU* cpu);
void vk_BeginCommandBuffer(CPU* cpu);
void vk_EndCommandBuffer(CPU* cpu);
void vk_ResetCommandBuffer(CPU* cpu);
void vk_CmdBindPipeline(CPU* cpu);
void vk_CmdSetAttachmentFeedbackLoopEnableEXT(CPU* cpu);
void vk_CmdSetViewport(CPU* cpu);
void vk_CmdSetScissor(CPU* cpu);
void vk_CmdSetLineWidth(CPU* cpu);
void vk_CmdSetDepthBias(CPU* cpu);
void vk_CmdSetBlendConstants(CPU* cpu);
void vk_CmdSetDepthBounds(CPU* cpu);
void vk_CmdSetStencilCompareMask(CPU* cpu);
void vk_CmdSetStencilWriteMask(CPU* cpu);
void vk_CmdSetStencilReference(CPU* cpu);
void vk_CmdBindDescriptorSets(CPU* cpu);
void vk_CmdBindIndexBuffer(CPU* cpu);
void vk_CmdBindVertexBuffers(CPU* cpu);
void vk_CmdDraw(CPU* cpu);
void vk_CmdDrawIndexed(CPU* cpu);
void vk_CmdDrawMultiEXT(CPU* cpu);
void vk_CmdDrawMultiIndexedEXT(CPU* cpu);
void vk_CmdDrawIndirect(CPU* cpu);
void vk_CmdDrawIndexedIndirect(CPU* cpu);
void vk_CmdDispatch(CPU* cpu);
void vk_CmdDispatchIndirect(CPU* cpu);
void vk_CmdSubpassShadingHUAWEI(CPU* cpu);
void vk_CmdDrawClusterHUAWEI(CPU* cpu);
void vk_CmdDrawClusterIndirectHUAWEI(CPU* cpu);
void vk_CmdUpdatePipelineIndirectBufferNV(CPU* cpu);
void vk_CmdCopyBuffer(CPU* cpu);
void vk_CmdCopyImage(CPU* cpu);
void vk_CmdBlitImage(CPU* cpu);
void vk_CmdCopyBufferToImage(CPU* cpu);
void vk_CmdCopyImageToBuffer(CPU* cpu);
void vk_CmdCopyMemoryIndirectNV(CPU* cpu);
void vk_CmdCopyMemoryIndirectKHR(CPU* cpu);
void vk_CmdCopyMemoryToImageIndirectNV(CPU* cpu);
void vk_CmdCopyMemoryToImageIndirectKHR(CPU* cpu);
void vk_CmdUpdateBuffer(CPU* cpu);
void vk_CmdFillBuffer(CPU* cpu);
void vk_CmdClearColorImage(CPU* cpu);
void vk_CmdClearDepthStencilImage(CPU* cpu);
void vk_CmdClearAttachments(CPU* cpu);
void vk_CmdResolveImage(CPU* cpu);
void vk_CmdSetEvent(CPU* cpu);
void vk_CmdResetEvent(CPU* cpu);
void vk_CmdWaitEvents(CPU* cpu);
void vk_CmdPipelineBarrier(CPU* cpu);
void vk_CmdBeginQuery(CPU* cpu);
void vk_CmdEndQuery(CPU* cpu);
void vk_CmdBeginConditionalRenderingEXT(CPU* cpu);
void vk_CmdEndConditionalRenderingEXT(CPU* cpu);
void vk_CmdBeginCustomResolveEXT(CPU* cpu);
void vk_CmdResetQueryPool(CPU* cpu);
void vk_CmdWriteTimestamp(CPU* cpu);
void vk_CmdCopyQueryPoolResults(CPU* cpu);
void vk_CmdPushConstants(CPU* cpu);
void vk_CmdBeginRenderPass(CPU* cpu);
void vk_CmdNextSubpass(CPU* cpu);
void vk_CmdEndRenderPass(CPU* cpu);
void vk_CmdExecuteCommands(CPU* cpu);
void vk_CreateSharedSwapchainsKHR(CPU* cpu);
void vk_DestroySurfaceKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceSupportKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceCapabilitiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceFormatsKHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfacePresentModesKHR(CPU* cpu);
void vk_CreateSwapchainKHR(CPU* cpu);
void vk_DestroySwapchainKHR(CPU* cpu);
void vk_GetSwapchainImagesKHR(CPU* cpu);
void vk_AcquireNextImageKHR(CPU* cpu);
void vk_QueuePresentKHR(CPU* cpu);
void vk_CreateXlibSurfaceKHR(CPU* cpu);
void vk_GetPhysicalDeviceXlibPresentationSupportKHR(CPU* cpu);
void vk_CreateDebugReportCallbackEXT(CPU* cpu);
void vk_DestroyDebugReportCallbackEXT(CPU* cpu);
void vk_DebugReportMessageEXT(CPU* cpu);
void vk_DebugMarkerSetObjectNameEXT(CPU* cpu);
void vk_DebugMarkerSetObjectTagEXT(CPU* cpu);
void vk_CmdDebugMarkerBeginEXT(CPU* cpu);
void vk_CmdDebugMarkerEndEXT(CPU* cpu);
void vk_CmdDebugMarkerInsertEXT(CPU* cpu);
void vk_CmdExecuteGeneratedCommandsNV(CPU* cpu);
void vk_CmdPreprocessGeneratedCommandsNV(CPU* cpu);
void vk_CmdBindPipelineShaderGroupNV(CPU* cpu);
void vk_GetGeneratedCommandsMemoryRequirementsNV(CPU* cpu);
void vk_CreateIndirectCommandsLayoutNV(CPU* cpu);
void vk_DestroyIndirectCommandsLayoutNV(CPU* cpu);
void vk_CmdExecuteGeneratedCommandsEXT(CPU* cpu);
void vk_CmdPreprocessGeneratedCommandsEXT(CPU* cpu);
void vk_GetGeneratedCommandsMemoryRequirementsEXT(CPU* cpu);
void vk_CreateIndirectCommandsLayoutEXT(CPU* cpu);
void vk_DestroyIndirectCommandsLayoutEXT(CPU* cpu);
void vk_CreateIndirectExecutionSetEXT(CPU* cpu);
void vk_DestroyIndirectExecutionSetEXT(CPU* cpu);
void vk_UpdateIndirectExecutionSetPipelineEXT(CPU* cpu);
void vk_UpdateIndirectExecutionSetShaderEXT(CPU* cpu);
void vk_GetPhysicalDeviceFeatures2(CPU* cpu);
void vk_GetPhysicalDeviceFeatures2KHR(CPU* cpu);
void vk_GetPhysicalDeviceProperties2(CPU* cpu);
void vk_GetPhysicalDeviceProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceFormatProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceImageFormatProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties2(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties2(CPU* cpu);
void vk_GetPhysicalDeviceMemoryProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties2(CPU* cpu);
void vk_GetPhysicalDeviceSparseImageFormatProperties2KHR(CPU* cpu);
void vk_CmdPushDescriptorSet(CPU* cpu);
void vk_CmdPushDescriptorSetKHR(CPU* cpu);
void vk_TrimCommandPool(CPU* cpu);
void vk_TrimCommandPoolKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalBufferProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalBufferPropertiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalSemaphoreProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalSemaphorePropertiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceExternalFenceProperties(CPU* cpu);
void vk_GetPhysicalDeviceExternalFencePropertiesKHR(CPU* cpu);
void vk_ReleaseDisplayEXT(CPU* cpu);
void vk_DisplayPowerControlEXT(CPU* cpu);
void vk_RegisterDeviceEventEXT(CPU* cpu);
void vk_RegisterDisplayEventEXT(CPU* cpu);
void vk_GetSwapchainCounterEXT(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceCapabilities2EXT(CPU* cpu);
void vk_EnumeratePhysicalDeviceGroups(CPU* cpu);
void vk_EnumeratePhysicalDeviceGroupsKHR(CPU* cpu);
void vk_GetDeviceGroupPeerMemoryFeatures(CPU* cpu);
void vk_GetDeviceGroupPeerMemoryFeaturesKHR(CPU* cpu);
void vk_BindBufferMemory2(CPU* cpu);
void vk_BindBufferMemory2KHR(CPU* cpu);
void vk_BindImageMemory2(CPU* cpu);
void vk_BindImageMemory2KHR(CPU* cpu);
void vk_CmdSetDeviceMask(CPU* cpu);
void vk_CmdSetDeviceMaskKHR(CPU* cpu);
void vk_GetDeviceGroupPresentCapabilitiesKHR(CPU* cpu);
void vk_GetDeviceGroupSurfacePresentModesKHR(CPU* cpu);
void vk_AcquireNextImage2KHR(CPU* cpu);
void vk_CmdDispatchBase(CPU* cpu);
void vk_CmdDispatchBaseKHR(CPU* cpu);
void vk_GetPhysicalDevicePresentRectanglesKHR(CPU* cpu);
void vk_CreateDescriptorUpdateTemplate(CPU* cpu);
void vk_CreateDescriptorUpdateTemplateKHR(CPU* cpu);
void vk_DestroyDescriptorUpdateTemplate(CPU* cpu);
void vk_DestroyDescriptorUpdateTemplateKHR(CPU* cpu);
void vk_UpdateDescriptorSetWithTemplate(CPU* cpu);
void vk_UpdateDescriptorSetWithTemplateKHR(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplate(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplateKHR(CPU* cpu);
void vk_SetHdrMetadataEXT(CPU* cpu);
void vk_CmdSetViewportWScalingNV(CPU* cpu);
void vk_CmdSetDiscardRectangleEXT(CPU* cpu);
void vk_CmdSetDiscardRectangleEnableEXT(CPU* cpu);
void vk_CmdSetDiscardRectangleModeEXT(CPU* cpu);
void vk_CmdSetSampleLocationsEXT(CPU* cpu);
void vk_GetPhysicalDeviceMultisamplePropertiesEXT(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceCapabilities2KHR(CPU* cpu);
void vk_GetPhysicalDeviceSurfaceFormats2KHR(CPU* cpu);
void vk_GetPhysicalDeviceDisplayProperties2KHR(CPU* cpu);
void vk_GetPhysicalDeviceDisplayPlaneProperties2KHR(CPU* cpu);
void vk_GetDisplayModeProperties2KHR(CPU* cpu);
void vk_GetDisplayPlaneCapabilities2KHR(CPU* cpu);
void vk_GetBufferMemoryRequirements2(CPU* cpu);
void vk_GetBufferMemoryRequirements2KHR(CPU* cpu);
void vk_GetImageMemoryRequirements2(CPU* cpu);
void vk_GetImageMemoryRequirements2KHR(CPU* cpu);
void vk_GetImageSparseMemoryRequirements2(CPU* cpu);
void vk_GetImageSparseMemoryRequirements2KHR(CPU* cpu);
void vk_GetDeviceBufferMemoryRequirements(CPU* cpu);
void vk_GetDeviceBufferMemoryRequirementsKHR(CPU* cpu);
void vk_GetDeviceImageMemoryRequirements(CPU* cpu);
void vk_GetDeviceImageMemoryRequirementsKHR(CPU* cpu);
void vk_GetDeviceImageSparseMemoryRequirements(CPU* cpu);
void vk_GetDeviceImageSparseMemoryRequirementsKHR(CPU* cpu);
void vk_CreateSamplerYcbcrConversion(CPU* cpu);
void vk_CreateSamplerYcbcrConversionKHR(CPU* cpu);
void vk_DestroySamplerYcbcrConversion(CPU* cpu);
void vk_DestroySamplerYcbcrConversionKHR(CPU* cpu);
void vk_GetDeviceQueue2(CPU* cpu);
void vk_CreateValidationCacheEXT(CPU* cpu);
void vk_DestroyValidationCacheEXT(CPU* cpu);
void vk_GetValidationCacheDataEXT(CPU* cpu);
void vk_MergeValidationCachesEXT(CPU* cpu);
void vk_GetDescriptorSetLayoutSupport(CPU* cpu);
void vk_GetDescriptorSetLayoutSupportKHR(CPU* cpu);
void vk_GetShaderInfoAMD(CPU* cpu);
void vk_GetPhysicalDeviceCalibrateableTimeDomainsKHR(CPU* cpu);
void vk_GetPhysicalDeviceCalibrateableTimeDomainsEXT(CPU* cpu);
void vk_GetCalibratedTimestampsKHR(CPU* cpu);
void vk_GetCalibratedTimestampsEXT(CPU* cpu);
void vk_SetDebugUtilsObjectNameEXT(CPU* cpu);
void vk_SetDebugUtilsObjectTagEXT(CPU* cpu);
void vk_QueueBeginDebugUtilsLabelEXT(CPU* cpu);
void vk_QueueEndDebugUtilsLabelEXT(CPU* cpu);
void vk_QueueInsertDebugUtilsLabelEXT(CPU* cpu);
void vk_CmdBeginDebugUtilsLabelEXT(CPU* cpu);
void vk_CmdEndDebugUtilsLabelEXT(CPU* cpu);
void vk_CmdInsertDebugUtilsLabelEXT(CPU* cpu);
void vk_CreateDebugUtilsMessengerEXT(CPU* cpu);
void vk_DestroyDebugUtilsMessengerEXT(CPU* cpu);
void vk_SubmitDebugUtilsMessageEXT(CPU* cpu);
void vk_GetMemoryHostPointerPropertiesEXT(CPU* cpu);
void vk_CmdWriteBufferMarkerAMD(CPU* cpu);
void vk_CreateRenderPass2(CPU* cpu);
void vk_CreateRenderPass2KHR(CPU* cpu);
void vk_CmdBeginRenderPass2(CPU* cpu);
void vk_CmdBeginRenderPass2KHR(CPU* cpu);
void vk_CmdNextSubpass2(CPU* cpu);
void vk_CmdNextSubpass2KHR(CPU* cpu);
void vk_CmdEndRenderPass2(CPU* cpu);
void vk_CmdEndRenderPass2KHR(CPU* cpu);
void vk_GetSemaphoreCounterValue(CPU* cpu);
void vk_GetSemaphoreCounterValueKHR(CPU* cpu);
void vk_WaitSemaphores(CPU* cpu);
void vk_WaitSemaphoresKHR(CPU* cpu);
void vk_SignalSemaphore(CPU* cpu);
void vk_SignalSemaphoreKHR(CPU* cpu);
void vk_CmdDrawIndirectCount(CPU* cpu);
void vk_CmdDrawIndirectCountKHR(CPU* cpu);
void vk_CmdDrawIndirectCountAMD(CPU* cpu);
void vk_CmdDrawIndexedIndirectCount(CPU* cpu);
void vk_CmdDrawIndexedIndirectCountKHR(CPU* cpu);
void vk_CmdDrawIndexedIndirectCountAMD(CPU* cpu);
void vk_CmdSetCheckpointNV(CPU* cpu);
void vk_GetQueueCheckpointDataNV(CPU* cpu);
void vk_CmdBindTransformFeedbackBuffersEXT(CPU* cpu);
void vk_CmdBeginTransformFeedbackEXT(CPU* cpu);
void vk_CmdEndTransformFeedbackEXT(CPU* cpu);
void vk_CmdBeginQueryIndexedEXT(CPU* cpu);
void vk_CmdEndQueryIndexedEXT(CPU* cpu);
void vk_CmdDrawIndirectByteCountEXT(CPU* cpu);
void vk_CmdSetExclusiveScissorNV(CPU* cpu);
void vk_CmdSetExclusiveScissorEnableNV(CPU* cpu);
void vk_CmdBindShadingRateImageNV(CPU* cpu);
void vk_CmdSetViewportShadingRatePaletteNV(CPU* cpu);
void vk_CmdSetCoarseSampleOrderNV(CPU* cpu);
void vk_CmdDrawMeshTasksNV(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectNV(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectCountNV(CPU* cpu);
void vk_CmdDrawMeshTasksEXT(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectEXT(CPU* cpu);
void vk_CmdDrawMeshTasksIndirectCountEXT(CPU* cpu);
void vk_CompileDeferredNV(CPU* cpu);
void vk_CreateAccelerationStructureNV(CPU* cpu);
void vk_CmdBindInvocationMaskHUAWEI(CPU* cpu);
void vk_DestroyAccelerationStructureKHR(CPU* cpu);
void vk_DestroyAccelerationStructureNV(CPU* cpu);
void vk_GetAccelerationStructureMemoryRequirementsNV(CPU* cpu);
void vk_BindAccelerationStructureMemoryNV(CPU* cpu);
void vk_CmdCopyAccelerationStructureNV(CPU* cpu);
void vk_CmdCopyAccelerationStructureKHR(CPU* cpu);
void vk_CopyAccelerationStructureKHR(CPU* cpu);
void vk_CmdCopyAccelerationStructureToMemoryKHR(CPU* cpu);
void vk_CopyAccelerationStructureToMemoryKHR(CPU* cpu);
void vk_CmdCopyMemoryToAccelerationStructureKHR(CPU* cpu);
void vk_CopyMemoryToAccelerationStructureKHR(CPU* cpu);
void vk_CmdWriteAccelerationStructuresPropertiesKHR(CPU* cpu);
void vk_CmdWriteAccelerationStructuresPropertiesNV(CPU* cpu);
void vk_CmdBuildAccelerationStructureNV(CPU* cpu);
void vk_WriteAccelerationStructuresPropertiesKHR(CPU* cpu);
void vk_CmdTraceRaysKHR(CPU* cpu);
void vk_CmdTraceRaysNV(CPU* cpu);
void vk_GetRayTracingShaderGroupHandlesKHR(CPU* cpu);
void vk_GetRayTracingShaderGroupHandlesNV(CPU* cpu);
void vk_GetRayTracingCaptureReplayShaderGroupHandlesKHR(CPU* cpu);
void vk_GetAccelerationStructureHandleNV(CPU* cpu);
void vk_CreateRayTracingPipelinesNV(CPU* cpu);
void vk_CreateRayTracingPipelinesKHR(CPU* cpu);
void vk_GetPhysicalDeviceCooperativeMatrixPropertiesNV(CPU* cpu);
void vk_CmdTraceRaysIndirectKHR(CPU* cpu);
void vk_CmdTraceRaysIndirect2KHR(CPU* cpu);
void vk_GetDeviceAccelerationStructureCompatibilityKHR(CPU* cpu);
void vk_GetRayTracingShaderGroupStackSizeKHR(CPU* cpu);
void vk_CmdSetRayTracingPipelineStackSizeKHR(CPU* cpu);
void vk_GetImageViewHandleNVX(CPU* cpu);
void vk_GetImageViewHandle64NVX(CPU* cpu);
void vk_GetImageViewAddressNVX(CPU* cpu);
void vk_EnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR(CPU* cpu);
void vk_GetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR(CPU* cpu);
void vk_AcquireProfilingLockKHR(CPU* cpu);
void vk_ReleaseProfilingLockKHR(CPU* cpu);
void vk_GetBufferOpaqueCaptureAddress(CPU* cpu);
void vk_GetBufferOpaqueCaptureAddressKHR(CPU* cpu);
void vk_GetBufferDeviceAddress(CPU* cpu);
void vk_GetBufferDeviceAddressKHR(CPU* cpu);
void vk_GetBufferDeviceAddressEXT(CPU* cpu);
void vk_GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV(CPU* cpu);
void vk_InitializePerformanceApiINTEL(CPU* cpu);
void vk_UninitializePerformanceApiINTEL(CPU* cpu);
void vk_CmdSetPerformanceMarkerINTEL(CPU* cpu);
void vk_CmdSetPerformanceStreamMarkerINTEL(CPU* cpu);
void vk_CmdSetPerformanceOverrideINTEL(CPU* cpu);
void vk_AcquirePerformanceConfigurationINTEL(CPU* cpu);
void vk_ReleasePerformanceConfigurationINTEL(CPU* cpu);
void vk_QueueSetPerformanceConfigurationINTEL(CPU* cpu);
void vk_GetPerformanceParameterINTEL(CPU* cpu);
void vk_GetDeviceMemoryOpaqueCaptureAddress(CPU* cpu);
void vk_GetDeviceMemoryOpaqueCaptureAddressKHR(CPU* cpu);
void vk_GetPipelineExecutablePropertiesKHR(CPU* cpu);
void vk_GetPipelineExecutableStatisticsKHR(CPU* cpu);
void vk_GetPipelineExecutableInternalRepresentationsKHR(CPU* cpu);
void vk_CmdSetLineStipple(CPU* cpu);
void vk_CmdSetLineStippleKHR(CPU* cpu);
void vk_CmdSetLineStippleEXT(CPU* cpu);
void vk_GetPhysicalDeviceToolProperties(CPU* cpu);
void vk_GetPhysicalDeviceToolPropertiesEXT(CPU* cpu);
void vk_CreateAccelerationStructureKHR(CPU* cpu);
void vk_CmdBuildAccelerationStructuresKHR(CPU* cpu);
void vk_CmdBuildAccelerationStructuresIndirectKHR(CPU* cpu);
void vk_BuildAccelerationStructuresKHR(CPU* cpu);
void vk_GetAccelerationStructureDeviceAddressKHR(CPU* cpu);
void vk_CreateDeferredOperationKHR(CPU* cpu);
void vk_DestroyDeferredOperationKHR(CPU* cpu);
void vk_GetDeferredOperationMaxConcurrencyKHR(CPU* cpu);
void vk_GetDeferredOperationResultKHR(CPU* cpu);
void vk_DeferredOperationJoinKHR(CPU* cpu);
void vk_GetPipelineIndirectMemoryRequirementsNV(CPU* cpu);
void vk_GetPipelineIndirectDeviceAddressNV(CPU* cpu);
void vk_AntiLagUpdateAMD(CPU* cpu);
void vk_CmdSetCullMode(CPU* cpu);
void vk_CmdSetCullModeEXT(CPU* cpu);
void vk_CmdSetFrontFace(CPU* cpu);
void vk_CmdSetFrontFaceEXT(CPU* cpu);
void vk_CmdSetPrimitiveTopology(CPU* cpu);
void vk_CmdSetPrimitiveTopologyEXT(CPU* cpu);
void vk_CmdSetViewportWithCount(CPU* cpu);
void vk_CmdSetViewportWithCountEXT(CPU* cpu);
void vk_CmdSetScissorWithCount(CPU* cpu);
void vk_CmdSetScissorWithCountEXT(CPU* cpu);
void vk_CmdBindIndexBuffer2(CPU* cpu);
void vk_CmdBindIndexBuffer2KHR(CPU* cpu);
void vk_CmdBindVertexBuffers2(CPU* cpu);
void vk_CmdBindVertexBuffers2EXT(CPU* cpu);
void vk_CmdSetDepthTestEnable(CPU* cpu);
void vk_CmdSetDepthTestEnableEXT(CPU* cpu);
void vk_CmdSetDepthWriteEnable(CPU* cpu);
void vk_CmdSetDepthWriteEnableEXT(CPU* cpu);
void vk_CmdSetDepthCompareOp(CPU* cpu);
void vk_CmdSetDepthCompareOpEXT(CPU* cpu);
void vk_CmdSetDepthBoundsTestEnable(CPU* cpu);
void vk_CmdSetDepthBoundsTestEnableEXT(CPU* cpu);
void vk_CmdSetStencilTestEnable(CPU* cpu);
void vk_CmdSetStencilTestEnableEXT(CPU* cpu);
void vk_CmdSetStencilOp(CPU* cpu);
void vk_CmdSetStencilOpEXT(CPU* cpu);
void vk_CmdSetPatchControlPointsEXT(CPU* cpu);
void vk_CmdSetRasterizerDiscardEnable(CPU* cpu);
void vk_CmdSetRasterizerDiscardEnableEXT(CPU* cpu);
void vk_CmdSetDepthBiasEnable(CPU* cpu);
void vk_CmdSetDepthBiasEnableEXT(CPU* cpu);
void vk_CmdSetLogicOpEXT(CPU* cpu);
void vk_CmdSetPrimitiveRestartEnable(CPU* cpu);
void vk_CmdSetPrimitiveRestartEnableEXT(CPU* cpu);
void vk_CmdSetTessellationDomainOriginEXT(CPU* cpu);
void vk_CmdSetDepthClampEnableEXT(CPU* cpu);
void vk_CmdSetPolygonModeEXT(CPU* cpu);
void vk_CmdSetRasterizationSamplesEXT(CPU* cpu);
void vk_CmdSetSampleMaskEXT(CPU* cpu);
void vk_CmdSetAlphaToCoverageEnableEXT(CPU* cpu);
void vk_CmdSetAlphaToOneEnableEXT(CPU* cpu);
void vk_CmdSetLogicOpEnableEXT(CPU* cpu);
void vk_CmdSetColorBlendEnableEXT(CPU* cpu);
void vk_CmdSetColorBlendEquationEXT(CPU* cpu);
void vk_CmdSetColorWriteMaskEXT(CPU* cpu);
void vk_CmdSetRasterizationStreamEXT(CPU* cpu);
void vk_CmdSetConservativeRasterizationModeEXT(CPU* cpu);
void vk_CmdSetExtraPrimitiveOverestimationSizeEXT(CPU* cpu);
void vk_CmdSetDepthClipEnableEXT(CPU* cpu);
void vk_CmdSetSampleLocationsEnableEXT(CPU* cpu);
void vk_CmdSetColorBlendAdvancedEXT(CPU* cpu);
void vk_CmdSetProvokingVertexModeEXT(CPU* cpu);
void vk_CmdSetLineRasterizationModeEXT(CPU* cpu);
void vk_CmdSetLineStippleEnableEXT(CPU* cpu);
void vk_CmdSetDepthClipNegativeOneToOneEXT(CPU* cpu);
void vk_CmdSetViewportWScalingEnableNV(CPU* cpu);
void vk_CmdSetViewportSwizzleNV(CPU* cpu);
void vk_CmdSetCoverageToColorEnableNV(CPU* cpu);
void vk_CmdSetCoverageToColorLocationNV(CPU* cpu);
void vk_CmdSetCoverageModulationModeNV(CPU* cpu);
void vk_CmdSetCoverageModulationTableEnableNV(CPU* cpu);
void vk_CmdSetCoverageModulationTableNV(CPU* cpu);
void vk_CmdSetShadingRateImageEnableNV(CPU* cpu);
void vk_CmdSetCoverageReductionModeNV(CPU* cpu);
void vk_CmdSetRepresentativeFragmentTestEnableNV(CPU* cpu);
void vk_CreatePrivateDataSlot(CPU* cpu);
void vk_CreatePrivateDataSlotEXT(CPU* cpu);
void vk_DestroyPrivateDataSlot(CPU* cpu);
void vk_DestroyPrivateDataSlotEXT(CPU* cpu);
void vk_SetPrivateData(CPU* cpu);
void vk_SetPrivateDataEXT(CPU* cpu);
void vk_GetPrivateData(CPU* cpu);
void vk_GetPrivateDataEXT(CPU* cpu);
void vk_CmdCopyBuffer2(CPU* cpu);
void vk_CmdCopyBuffer2KHR(CPU* cpu);
void vk_CmdCopyImage2(CPU* cpu);
void vk_CmdCopyImage2KHR(CPU* cpu);
void vk_CmdBlitImage2(CPU* cpu);
void vk_CmdBlitImage2KHR(CPU* cpu);
void vk_CmdCopyBufferToImage2(CPU* cpu);
void vk_CmdCopyBufferToImage2KHR(CPU* cpu);
void vk_CmdCopyImageToBuffer2(CPU* cpu);
void vk_CmdCopyImageToBuffer2KHR(CPU* cpu);
void vk_CmdResolveImage2(CPU* cpu);
void vk_CmdResolveImage2KHR(CPU* cpu);
void vk_CmdSetFragmentShadingRateKHR(CPU* cpu);
void vk_GetPhysicalDeviceFragmentShadingRatesKHR(CPU* cpu);
void vk_CmdSetFragmentShadingRateEnumNV(CPU* cpu);
void vk_GetAccelerationStructureBuildSizesKHR(CPU* cpu);
void vk_CmdSetVertexInputEXT(CPU* cpu);
void vk_CmdSetColorWriteEnableEXT(CPU* cpu);
void vk_CmdSetEvent2(CPU* cpu);
void vk_CmdSetEvent2KHR(CPU* cpu);
void vk_CmdResetEvent2(CPU* cpu);
void vk_CmdResetEvent2KHR(CPU* cpu);
void vk_CmdWaitEvents2(CPU* cpu);
void vk_CmdWaitEvents2KHR(CPU* cpu);
void vk_CmdPipelineBarrier2(CPU* cpu);
void vk_CmdPipelineBarrier2KHR(CPU* cpu);
void vk_QueueSubmit2(CPU* cpu);
void vk_QueueSubmit2KHR(CPU* cpu);
void vk_CmdWriteTimestamp2(CPU* cpu);
void vk_CmdWriteTimestamp2KHR(CPU* cpu);
void vk_CmdWriteBufferMarker2AMD(CPU* cpu);
void vk_GetQueueCheckpointData2NV(CPU* cpu);
void vk_CopyMemoryToImage(CPU* cpu);
void vk_CopyMemoryToImageEXT(CPU* cpu);
void vk_CopyImageToMemory(CPU* cpu);
void vk_CopyImageToMemoryEXT(CPU* cpu);
void vk_CopyImageToImage(CPU* cpu);
void vk_CopyImageToImageEXT(CPU* cpu);
void vk_TransitionImageLayout(CPU* cpu);
void vk_TransitionImageLayoutEXT(CPU* cpu);
void vk_GetPhysicalDeviceVideoCapabilitiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceVideoFormatPropertiesKHR(CPU* cpu);
void vk_GetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR(CPU* cpu);
void vk_CreateVideoSessionKHR(CPU* cpu);
void vk_DestroyVideoSessionKHR(CPU* cpu);
void vk_CreateVideoSessionParametersKHR(CPU* cpu);
void vk_UpdateVideoSessionParametersKHR(CPU* cpu);
void vk_GetEncodedVideoSessionParametersKHR(CPU* cpu);
void vk_DestroyVideoSessionParametersKHR(CPU* cpu);
void vk_GetVideoSessionMemoryRequirementsKHR(CPU* cpu);
void vk_BindVideoSessionMemoryKHR(CPU* cpu);
void vk_CmdDecodeVideoKHR(CPU* cpu);
void vk_CmdBeginVideoCodingKHR(CPU* cpu);
void vk_CmdControlVideoCodingKHR(CPU* cpu);
void vk_CmdEndVideoCodingKHR(CPU* cpu);
void vk_CmdEncodeVideoKHR(CPU* cpu);
void vk_CmdDecompressMemoryNV(CPU* cpu);
void vk_CmdDecompressMemoryIndirectCountNV(CPU* cpu);
void vk_GetPartitionedAccelerationStructuresBuildSizesNV(CPU* cpu);
void vk_CmdBuildPartitionedAccelerationStructuresNV(CPU* cpu);
void vk_CmdDecompressMemoryEXT(CPU* cpu);
void vk_CmdDecompressMemoryIndirectCountEXT(CPU* cpu);
void vk_CreateCuModuleNVX(CPU* cpu);
void vk_CreateCuFunctionNVX(CPU* cpu);
void vk_DestroyCuModuleNVX(CPU* cpu);
void vk_DestroyCuFunctionNVX(CPU* cpu);
void vk_CmdCuLaunchKernelNVX(CPU* cpu);
void vk_GetDescriptorSetLayoutSizeEXT(CPU* cpu);
void vk_GetDescriptorSetLayoutBindingOffsetEXT(CPU* cpu);
void vk_GetDescriptorEXT(CPU* cpu);
void vk_CmdBindDescriptorBuffersEXT(CPU* cpu);
void vk_CmdSetDescriptorBufferOffsetsEXT(CPU* cpu);
void vk_CmdBindDescriptorBufferEmbeddedSamplersEXT(CPU* cpu);
void vk_GetBufferOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_GetImageOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_GetImageViewOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_GetSamplerOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_GetAccelerationStructureOpaqueCaptureDescriptorDataEXT(CPU* cpu);
void vk_SetDeviceMemoryPriorityEXT(CPU* cpu);
void vk_AcquireDrmDisplayEXT(CPU* cpu);
void vk_GetDrmDisplayEXT(CPU* cpu);
void vk_WaitForPresent2KHR(CPU* cpu);
void vk_WaitForPresentKHR(CPU* cpu);
void vk_CmdBeginRendering(CPU* cpu);
void vk_CmdBeginRenderingKHR(CPU* cpu);
void vk_CmdEndRendering(CPU* cpu);
void vk_CmdEndRendering2KHR(CPU* cpu);
void vk_CmdEndRendering2EXT(CPU* cpu);
void vk_CmdEndRenderingKHR(CPU* cpu);
void vk_GetDescriptorSetLayoutHostMappingInfoVALVE(CPU* cpu);
void vk_GetDescriptorSetHostMappingVALVE(CPU* cpu);
void vk_CreateMicromapEXT(CPU* cpu);
void vk_CmdBuildMicromapsEXT(CPU* cpu);
void vk_BuildMicromapsEXT(CPU* cpu);
void vk_DestroyMicromapEXT(CPU* cpu);
void vk_CmdCopyMicromapEXT(CPU* cpu);
void vk_CopyMicromapEXT(CPU* cpu);
void vk_CmdCopyMicromapToMemoryEXT(CPU* cpu);
void vk_CopyMicromapToMemoryEXT(CPU* cpu);
void vk_CmdCopyMemoryToMicromapEXT(CPU* cpu);
void vk_CopyMemoryToMicromapEXT(CPU* cpu);
void vk_CmdWriteMicromapsPropertiesEXT(CPU* cpu);
void vk_WriteMicromapsPropertiesEXT(CPU* cpu);
void vk_GetDeviceMicromapCompatibilityEXT(CPU* cpu);
void vk_GetMicromapBuildSizesEXT(CPU* cpu);
void vk_GetShaderModuleIdentifierEXT(CPU* cpu);
void vk_GetShaderModuleCreateInfoIdentifierEXT(CPU* cpu);
void vk_GetImageSubresourceLayout2(CPU* cpu);
void vk_GetImageSubresourceLayout2KHR(CPU* cpu);
void vk_GetImageSubresourceLayout2EXT(CPU* cpu);
void vk_GetPipelinePropertiesEXT(CPU* cpu);
void vk_CmdBindTileMemoryQCOM(CPU* cpu);
void vk_GetFramebufferTilePropertiesQCOM(CPU* cpu);
void vk_GetDynamicRenderingTilePropertiesQCOM(CPU* cpu);
void vk_GetPhysicalDeviceOpticalFlowImageFormatsNV(CPU* cpu);
void vk_CreateOpticalFlowSessionNV(CPU* cpu);
void vk_DestroyOpticalFlowSessionNV(CPU* cpu);
void vk_BindOpticalFlowSessionImageNV(CPU* cpu);
void vk_CmdOpticalFlowExecuteNV(CPU* cpu);
void vk_GetDeviceFaultInfoEXT(CPU* cpu);
void vk_CmdSetDepthBias2EXT(CPU* cpu);
void vk_ReleaseSwapchainImagesKHR(CPU* cpu);
void vk_ReleaseSwapchainImagesEXT(CPU* cpu);
void vk_GetDeviceImageSubresourceLayout(CPU* cpu);
void vk_GetDeviceImageSubresourceLayoutKHR(CPU* cpu);
void vk_MapMemory2(CPU* cpu);
void vk_MapMemory2KHR(CPU* cpu);
void vk_UnmapMemory2(CPU* cpu);
void vk_UnmapMemory2KHR(CPU* cpu);
void vk_CreateShadersEXT(CPU* cpu);
void vk_DestroyShaderEXT(CPU* cpu);
void vk_GetShaderBinaryDataEXT(CPU* cpu);
void vk_CmdBindShadersEXT(CPU* cpu);
void vk_SetSwapchainPresentTimingQueueSizeEXT(CPU* cpu);
void vk_GetSwapchainTimingPropertiesEXT(CPU* cpu);
void vk_GetSwapchainTimeDomainPropertiesEXT(CPU* cpu);
void vk_GetPastPresentationTimingEXT(CPU* cpu);
void vk_GetPhysicalDeviceCooperativeMatrixPropertiesKHR(CPU* cpu);
void vk_CmdBindDescriptorSets2(CPU* cpu);
void vk_CmdBindDescriptorSets2KHR(CPU* cpu);
void vk_CmdPushConstants2(CPU* cpu);
void vk_CmdPushConstants2KHR(CPU* cpu);
void vk_CmdPushDescriptorSet2(CPU* cpu);
void vk_CmdPushDescriptorSet2KHR(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplate2(CPU* cpu);
void vk_CmdPushDescriptorSetWithTemplate2KHR(CPU* cpu);
void vk_CmdSetDescriptorBufferOffsets2EXT(CPU* cpu);
void vk_CmdBindDescriptorBufferEmbeddedSamplers2EXT(CPU* cpu);
void vk_SetLatencySleepModeNV(CPU* cpu);
void vk_LatencySleepNV(CPU* cpu);
void vk_SetLatencyMarkerNV(CPU* cpu);
void vk_GetLatencyTimingsNV(CPU* cpu);
void vk_QueueNotifyOutOfBandNV(CPU* cpu);
void vk_CmdSetRenderingAttachmentLocations(CPU* cpu);
void vk_CmdSetRenderingAttachmentLocationsKHR(CPU* cpu);
void vk_CmdSetRenderingInputAttachmentIndices(CPU* cpu);
void vk_CmdSetRenderingInputAttachmentIndicesKHR(CPU* cpu);
void vk_CmdSetDepthClampRangeEXT(CPU* cpu);
void vk_GetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV(CPU* cpu);
void vk_GetPhysicalDeviceCooperativeVectorPropertiesNV(CPU* cpu);
void vk_ConvertCooperativeVectorMatrixNV(CPU* cpu);
void vk_CmdConvertCooperativeVectorMatrixNV(CPU* cpu);
void vk_CmdDispatchTileQCOM(CPU* cpu);
void vk_CmdBeginPerTileExecutionQCOM(CPU* cpu);
void vk_CmdEndPerTileExecutionQCOM(CPU* cpu);
void vk_CreateExternalComputeQueueNV(CPU* cpu);
void vk_DestroyExternalComputeQueueNV(CPU* cpu);
void vk_GetExternalComputeQueueDataNV(CPU* cpu);
void vk_EnumeratePhysicalDeviceQueueFamilyPerformanceCountersByRegionARM(CPU* cpu);
U64 translateVulkanObjectHandle(KMemory* memory, VkObjectType type, U64 handle);
bool prepareDescriptorTemplate(VkDescriptorUpdateTemplateCreateInfo& info, std::vector<VkDescriptorUpdateTemplateEntry>& entries);
const void* marshalDescriptorTemplateData(BoxedVulkanInfo* info, KMemory* memory, VkDescriptorUpdateTemplate descriptorTemplate, U32 address, std::vector<U8>& storage);
struct VulkanMemoryAllocation { U64 size = 0; U32 mappedAddress = 0; U32 mappedLen = 0; };
void registerVkMemoryAllocation(BoxedVulkanInfo* info, VkDeviceMemory memory, VkDeviceSize size);
void unregisterVkMemoryAllocation(BoxedVulkanInfo* info, VkDeviceMemory memory);
U32 mapVkMemory(BoxedVulkanInfo* info, VkDeviceMemory memory, void* pData, VkDeviceSize offset, VkDeviceSize len);
void unmapVkMemory(BoxedVulkanInfo* info, VkDeviceMemory memory);
void cacheDescriptorTemplate(BoxedVulkanInfo* info, U64 handle, const VkDescriptorUpdateTemplateCreateInfo& source);
void cacheImageInfo(BoxedVulkanInfo* info, U64 handle, const VkImageCreateInfo& source);
void registerVulkanCommandBuffer(BoxedVulkanInfo* info, VkCommandPool pool, U32 wrapper);
void releaseVulkanCommandBuffer(BoxedVulkanInfo* info, KMemory* memory, VkCommandPool pool, U32 wrapper);
void releaseVulkanCommandPool(BoxedVulkanInfo* info, KMemory* memory, VkCommandPool pool);
class BoxedVulkanInfo {
public:
    VkInstance instance = VK_NULL_HANDLE;
    VkDevice device = VK_NULL_HANDLE;
    PFN_vkGetDeviceProcAddr getDeviceProcAddr = nullptr;
    bool xlibSurfaceEnabled = false;
    BOXEDWINE_MUTEX memoryMutex;
    std::unordered_map<U64, VulkanMemoryAllocation> allocations;
    BOXEDWINE_MUTEX cacheMutex;
    std::unordered_map<U64, std::unordered_set<U32>> commandBuffersByPool;
    PFN_vkDestroyInstance pvkDestroyInstance = nullptr;
    PFN_vkEnumeratePhysicalDevices pvkEnumeratePhysicalDevices = nullptr;
    PFN_vkGetPhysicalDeviceProperties pvkGetPhysicalDeviceProperties = nullptr;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties pvkGetPhysicalDeviceQueueFamilyProperties = nullptr;
    PFN_vkGetPhysicalDeviceMemoryProperties pvkGetPhysicalDeviceMemoryProperties = nullptr;
    PFN_vkGetPhysicalDeviceFeatures pvkGetPhysicalDeviceFeatures = nullptr;
    PFN_vkGetPhysicalDeviceFormatProperties pvkGetPhysicalDeviceFormatProperties = nullptr;
    PFN_vkGetPhysicalDeviceImageFormatProperties pvkGetPhysicalDeviceImageFormatProperties = nullptr;
    PFN_vkCreateDevice pvkCreateDevice = nullptr;
    PFN_vkDestroyDevice pvkDestroyDevice = nullptr;
    PFN_vkEnumerateDeviceLayerProperties pvkEnumerateDeviceLayerProperties = nullptr;
    PFN_vkEnumerateDeviceExtensionProperties pvkEnumerateDeviceExtensionProperties = nullptr;
    PFN_vkGetDeviceQueue pvkGetDeviceQueue = nullptr;
    PFN_vkQueueSubmit pvkQueueSubmit = nullptr;
    PFN_vkQueueWaitIdle pvkQueueWaitIdle = nullptr;
    PFN_vkDeviceWaitIdle pvkDeviceWaitIdle = nullptr;
    PFN_vkAllocateMemory pvkAllocateMemory = nullptr;
    PFN_vkFreeMemory pvkFreeMemory = nullptr;
    PFN_vkMapMemory pvkMapMemory = nullptr;
    PFN_vkUnmapMemory pvkUnmapMemory = nullptr;
    PFN_vkFlushMappedMemoryRanges pvkFlushMappedMemoryRanges = nullptr;
    PFN_vkInvalidateMappedMemoryRanges pvkInvalidateMappedMemoryRanges = nullptr;
    PFN_vkGetDeviceMemoryCommitment pvkGetDeviceMemoryCommitment = nullptr;
    PFN_vkGetBufferMemoryRequirements pvkGetBufferMemoryRequirements = nullptr;
    PFN_vkBindBufferMemory pvkBindBufferMemory = nullptr;
    PFN_vkGetImageMemoryRequirements pvkGetImageMemoryRequirements = nullptr;
    PFN_vkBindImageMemory pvkBindImageMemory = nullptr;
    PFN_vkGetImageSparseMemoryRequirements pvkGetImageSparseMemoryRequirements = nullptr;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties pvkGetPhysicalDeviceSparseImageFormatProperties = nullptr;
    PFN_vkQueueBindSparse pvkQueueBindSparse = nullptr;
    PFN_vkCreateFence pvkCreateFence = nullptr;
    PFN_vkDestroyFence pvkDestroyFence = nullptr;
    PFN_vkResetFences pvkResetFences = nullptr;
    PFN_vkGetFenceStatus pvkGetFenceStatus = nullptr;
    PFN_vkWaitForFences pvkWaitForFences = nullptr;
    PFN_vkCreateSemaphore pvkCreateSemaphore = nullptr;
    PFN_vkDestroySemaphore pvkDestroySemaphore = nullptr;
    PFN_vkCreateEvent pvkCreateEvent = nullptr;
    PFN_vkDestroyEvent pvkDestroyEvent = nullptr;
    PFN_vkGetEventStatus pvkGetEventStatus = nullptr;
    PFN_vkSetEvent pvkSetEvent = nullptr;
    PFN_vkResetEvent pvkResetEvent = nullptr;
    PFN_vkCreateQueryPool pvkCreateQueryPool = nullptr;
    PFN_vkDestroyQueryPool pvkDestroyQueryPool = nullptr;
    PFN_vkGetQueryPoolResults pvkGetQueryPoolResults = nullptr;
    PFN_vkResetQueryPool pvkResetQueryPool = nullptr;
    PFN_vkResetQueryPoolEXT pvkResetQueryPoolEXT = nullptr;
    PFN_vkCreateBuffer pvkCreateBuffer = nullptr;
    PFN_vkDestroyBuffer pvkDestroyBuffer = nullptr;
    PFN_vkCreateBufferView pvkCreateBufferView = nullptr;
    PFN_vkDestroyBufferView pvkDestroyBufferView = nullptr;
    PFN_vkCreateImage pvkCreateImage = nullptr;
    PFN_vkDestroyImage pvkDestroyImage = nullptr;
    PFN_vkGetImageSubresourceLayout pvkGetImageSubresourceLayout = nullptr;
    PFN_vkCreateImageView pvkCreateImageView = nullptr;
    PFN_vkDestroyImageView pvkDestroyImageView = nullptr;
    PFN_vkCreateShaderModule pvkCreateShaderModule = nullptr;
    PFN_vkDestroyShaderModule pvkDestroyShaderModule = nullptr;
    PFN_vkCreatePipelineCache pvkCreatePipelineCache = nullptr;
    PFN_vkDestroyPipelineCache pvkDestroyPipelineCache = nullptr;
    PFN_vkGetPipelineCacheData pvkGetPipelineCacheData = nullptr;
    PFN_vkMergePipelineCaches pvkMergePipelineCaches = nullptr;
    PFN_vkCreatePipelineBinariesKHR pvkCreatePipelineBinariesKHR = nullptr;
    PFN_vkDestroyPipelineBinaryKHR pvkDestroyPipelineBinaryKHR = nullptr;
    PFN_vkGetPipelineKeyKHR pvkGetPipelineKeyKHR = nullptr;
    PFN_vkGetPipelineBinaryDataKHR pvkGetPipelineBinaryDataKHR = nullptr;
    PFN_vkReleaseCapturedPipelineDataKHR pvkReleaseCapturedPipelineDataKHR = nullptr;
    PFN_vkCreateGraphicsPipelines pvkCreateGraphicsPipelines = nullptr;
    PFN_vkCreateComputePipelines pvkCreateComputePipelines = nullptr;
    PFN_vkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI pvkGetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI = nullptr;
    PFN_vkDestroyPipeline pvkDestroyPipeline = nullptr;
    PFN_vkCreatePipelineLayout pvkCreatePipelineLayout = nullptr;
    PFN_vkDestroyPipelineLayout pvkDestroyPipelineLayout = nullptr;
    PFN_vkCreateSampler pvkCreateSampler = nullptr;
    PFN_vkDestroySampler pvkDestroySampler = nullptr;
    PFN_vkCreateDescriptorSetLayout pvkCreateDescriptorSetLayout = nullptr;
    PFN_vkDestroyDescriptorSetLayout pvkDestroyDescriptorSetLayout = nullptr;
    PFN_vkCreateDescriptorPool pvkCreateDescriptorPool = nullptr;
    PFN_vkDestroyDescriptorPool pvkDestroyDescriptorPool = nullptr;
    PFN_vkResetDescriptorPool pvkResetDescriptorPool = nullptr;
    PFN_vkAllocateDescriptorSets pvkAllocateDescriptorSets = nullptr;
    PFN_vkFreeDescriptorSets pvkFreeDescriptorSets = nullptr;
    PFN_vkUpdateDescriptorSets pvkUpdateDescriptorSets = nullptr;
    PFN_vkCreateFramebuffer pvkCreateFramebuffer = nullptr;
    PFN_vkDestroyFramebuffer pvkDestroyFramebuffer = nullptr;
    PFN_vkCreateRenderPass pvkCreateRenderPass = nullptr;
    PFN_vkDestroyRenderPass pvkDestroyRenderPass = nullptr;
    PFN_vkGetRenderAreaGranularity pvkGetRenderAreaGranularity = nullptr;
    PFN_vkGetRenderingAreaGranularity pvkGetRenderingAreaGranularity = nullptr;
    PFN_vkGetRenderingAreaGranularityKHR pvkGetRenderingAreaGranularityKHR = nullptr;
    PFN_vkCreateCommandPool pvkCreateCommandPool = nullptr;
    PFN_vkDestroyCommandPool pvkDestroyCommandPool = nullptr;
    PFN_vkResetCommandPool pvkResetCommandPool = nullptr;
    PFN_vkAllocateCommandBuffers pvkAllocateCommandBuffers = nullptr;
    PFN_vkFreeCommandBuffers pvkFreeCommandBuffers = nullptr;
    PFN_vkBeginCommandBuffer pvkBeginCommandBuffer = nullptr;
    PFN_vkEndCommandBuffer pvkEndCommandBuffer = nullptr;
    PFN_vkResetCommandBuffer pvkResetCommandBuffer = nullptr;
    PFN_vkCmdBindPipeline pvkCmdBindPipeline = nullptr;
    PFN_vkCmdSetAttachmentFeedbackLoopEnableEXT pvkCmdSetAttachmentFeedbackLoopEnableEXT = nullptr;
    PFN_vkCmdSetViewport pvkCmdSetViewport = nullptr;
    PFN_vkCmdSetScissor pvkCmdSetScissor = nullptr;
    PFN_vkCmdSetLineWidth pvkCmdSetLineWidth = nullptr;
    PFN_vkCmdSetDepthBias pvkCmdSetDepthBias = nullptr;
    PFN_vkCmdSetBlendConstants pvkCmdSetBlendConstants = nullptr;
    PFN_vkCmdSetDepthBounds pvkCmdSetDepthBounds = nullptr;
    PFN_vkCmdSetStencilCompareMask pvkCmdSetStencilCompareMask = nullptr;
    PFN_vkCmdSetStencilWriteMask pvkCmdSetStencilWriteMask = nullptr;
    PFN_vkCmdSetStencilReference pvkCmdSetStencilReference = nullptr;
    PFN_vkCmdBindDescriptorSets pvkCmdBindDescriptorSets = nullptr;
    PFN_vkCmdBindIndexBuffer pvkCmdBindIndexBuffer = nullptr;
    PFN_vkCmdBindVertexBuffers pvkCmdBindVertexBuffers = nullptr;
    PFN_vkCmdDraw pvkCmdDraw = nullptr;
    PFN_vkCmdDrawIndexed pvkCmdDrawIndexed = nullptr;
    PFN_vkCmdDrawMultiEXT pvkCmdDrawMultiEXT = nullptr;
    PFN_vkCmdDrawMultiIndexedEXT pvkCmdDrawMultiIndexedEXT = nullptr;
    PFN_vkCmdDrawIndirect pvkCmdDrawIndirect = nullptr;
    PFN_vkCmdDrawIndexedIndirect pvkCmdDrawIndexedIndirect = nullptr;
    PFN_vkCmdDispatch pvkCmdDispatch = nullptr;
    PFN_vkCmdDispatchIndirect pvkCmdDispatchIndirect = nullptr;
    PFN_vkCmdSubpassShadingHUAWEI pvkCmdSubpassShadingHUAWEI = nullptr;
    PFN_vkCmdDrawClusterHUAWEI pvkCmdDrawClusterHUAWEI = nullptr;
    PFN_vkCmdDrawClusterIndirectHUAWEI pvkCmdDrawClusterIndirectHUAWEI = nullptr;
    PFN_vkCmdUpdatePipelineIndirectBufferNV pvkCmdUpdatePipelineIndirectBufferNV = nullptr;
    PFN_vkCmdCopyBuffer pvkCmdCopyBuffer = nullptr;
    PFN_vkCmdCopyImage pvkCmdCopyImage = nullptr;
    PFN_vkCmdBlitImage pvkCmdBlitImage = nullptr;
    PFN_vkCmdCopyBufferToImage pvkCmdCopyBufferToImage = nullptr;
    PFN_vkCmdCopyImageToBuffer pvkCmdCopyImageToBuffer = nullptr;
    PFN_vkCmdCopyMemoryIndirectNV pvkCmdCopyMemoryIndirectNV = nullptr;
    PFN_vkCmdCopyMemoryIndirectKHR pvkCmdCopyMemoryIndirectKHR = nullptr;
    PFN_vkCmdCopyMemoryToImageIndirectNV pvkCmdCopyMemoryToImageIndirectNV = nullptr;
    PFN_vkCmdCopyMemoryToImageIndirectKHR pvkCmdCopyMemoryToImageIndirectKHR = nullptr;
    PFN_vkCmdUpdateBuffer pvkCmdUpdateBuffer = nullptr;
    PFN_vkCmdFillBuffer pvkCmdFillBuffer = nullptr;
    PFN_vkCmdClearColorImage pvkCmdClearColorImage = nullptr;
    PFN_vkCmdClearDepthStencilImage pvkCmdClearDepthStencilImage = nullptr;
    PFN_vkCmdClearAttachments pvkCmdClearAttachments = nullptr;
    PFN_vkCmdResolveImage pvkCmdResolveImage = nullptr;
    PFN_vkCmdSetEvent pvkCmdSetEvent = nullptr;
    PFN_vkCmdResetEvent pvkCmdResetEvent = nullptr;
    PFN_vkCmdWaitEvents pvkCmdWaitEvents = nullptr;
    PFN_vkCmdPipelineBarrier pvkCmdPipelineBarrier = nullptr;
    PFN_vkCmdBeginQuery pvkCmdBeginQuery = nullptr;
    PFN_vkCmdEndQuery pvkCmdEndQuery = nullptr;
    PFN_vkCmdBeginConditionalRenderingEXT pvkCmdBeginConditionalRenderingEXT = nullptr;
    PFN_vkCmdEndConditionalRenderingEXT pvkCmdEndConditionalRenderingEXT = nullptr;
    PFN_vkCmdBeginCustomResolveEXT pvkCmdBeginCustomResolveEXT = nullptr;
    PFN_vkCmdResetQueryPool pvkCmdResetQueryPool = nullptr;
    PFN_vkCmdWriteTimestamp pvkCmdWriteTimestamp = nullptr;
    PFN_vkCmdCopyQueryPoolResults pvkCmdCopyQueryPoolResults = nullptr;
    PFN_vkCmdPushConstants pvkCmdPushConstants = nullptr;
    PFN_vkCmdBeginRenderPass pvkCmdBeginRenderPass = nullptr;
    PFN_vkCmdNextSubpass pvkCmdNextSubpass = nullptr;
    PFN_vkCmdEndRenderPass pvkCmdEndRenderPass = nullptr;
    PFN_vkCmdExecuteCommands pvkCmdExecuteCommands = nullptr;
    PFN_vkCreateSharedSwapchainsKHR pvkCreateSharedSwapchainsKHR = nullptr;
    PFN_vkDestroySurfaceKHR pvkDestroySurfaceKHR = nullptr;
    PFN_vkGetPhysicalDeviceSurfaceSupportKHR pvkGetPhysicalDeviceSurfaceSupportKHR = nullptr;
    PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR pvkGetPhysicalDeviceSurfaceCapabilitiesKHR = nullptr;
    PFN_vkGetPhysicalDeviceSurfaceFormatsKHR pvkGetPhysicalDeviceSurfaceFormatsKHR = nullptr;
    PFN_vkGetPhysicalDeviceSurfacePresentModesKHR pvkGetPhysicalDeviceSurfacePresentModesKHR = nullptr;
    PFN_vkCreateSwapchainKHR pvkCreateSwapchainKHR = nullptr;
    PFN_vkDestroySwapchainKHR pvkDestroySwapchainKHR = nullptr;
    PFN_vkGetSwapchainImagesKHR pvkGetSwapchainImagesKHR = nullptr;
    PFN_vkAcquireNextImageKHR pvkAcquireNextImageKHR = nullptr;
    PFN_vkQueuePresentKHR pvkQueuePresentKHR = nullptr;
    PFN_vkCreateDebugReportCallbackEXT pvkCreateDebugReportCallbackEXT = nullptr;
    PFN_vkDestroyDebugReportCallbackEXT pvkDestroyDebugReportCallbackEXT = nullptr;
    PFN_vkDebugReportMessageEXT pvkDebugReportMessageEXT = nullptr;
    PFN_vkDebugMarkerSetObjectNameEXT pvkDebugMarkerSetObjectNameEXT = nullptr;
    PFN_vkDebugMarkerSetObjectTagEXT pvkDebugMarkerSetObjectTagEXT = nullptr;
    PFN_vkCmdDebugMarkerBeginEXT pvkCmdDebugMarkerBeginEXT = nullptr;
    PFN_vkCmdDebugMarkerEndEXT pvkCmdDebugMarkerEndEXT = nullptr;
    PFN_vkCmdDebugMarkerInsertEXT pvkCmdDebugMarkerInsertEXT = nullptr;
    PFN_vkCmdExecuteGeneratedCommandsNV pvkCmdExecuteGeneratedCommandsNV = nullptr;
    PFN_vkCmdPreprocessGeneratedCommandsNV pvkCmdPreprocessGeneratedCommandsNV = nullptr;
    PFN_vkCmdBindPipelineShaderGroupNV pvkCmdBindPipelineShaderGroupNV = nullptr;
    PFN_vkGetGeneratedCommandsMemoryRequirementsNV pvkGetGeneratedCommandsMemoryRequirementsNV = nullptr;
    PFN_vkCreateIndirectCommandsLayoutNV pvkCreateIndirectCommandsLayoutNV = nullptr;
    PFN_vkDestroyIndirectCommandsLayoutNV pvkDestroyIndirectCommandsLayoutNV = nullptr;
    PFN_vkCmdExecuteGeneratedCommandsEXT pvkCmdExecuteGeneratedCommandsEXT = nullptr;
    PFN_vkCmdPreprocessGeneratedCommandsEXT pvkCmdPreprocessGeneratedCommandsEXT = nullptr;
    PFN_vkGetGeneratedCommandsMemoryRequirementsEXT pvkGetGeneratedCommandsMemoryRequirementsEXT = nullptr;
    PFN_vkCreateIndirectCommandsLayoutEXT pvkCreateIndirectCommandsLayoutEXT = nullptr;
    PFN_vkDestroyIndirectCommandsLayoutEXT pvkDestroyIndirectCommandsLayoutEXT = nullptr;
    PFN_vkCreateIndirectExecutionSetEXT pvkCreateIndirectExecutionSetEXT = nullptr;
    PFN_vkDestroyIndirectExecutionSetEXT pvkDestroyIndirectExecutionSetEXT = nullptr;
    PFN_vkUpdateIndirectExecutionSetPipelineEXT pvkUpdateIndirectExecutionSetPipelineEXT = nullptr;
    PFN_vkUpdateIndirectExecutionSetShaderEXT pvkUpdateIndirectExecutionSetShaderEXT = nullptr;
    PFN_vkGetPhysicalDeviceFeatures2 pvkGetPhysicalDeviceFeatures2 = nullptr;
    PFN_vkGetPhysicalDeviceFeatures2KHR pvkGetPhysicalDeviceFeatures2KHR = nullptr;
    PFN_vkGetPhysicalDeviceProperties2 pvkGetPhysicalDeviceProperties2 = nullptr;
    PFN_vkGetPhysicalDeviceProperties2KHR pvkGetPhysicalDeviceProperties2KHR = nullptr;
    PFN_vkGetPhysicalDeviceFormatProperties2 pvkGetPhysicalDeviceFormatProperties2 = nullptr;
    PFN_vkGetPhysicalDeviceFormatProperties2KHR pvkGetPhysicalDeviceFormatProperties2KHR = nullptr;
    PFN_vkGetPhysicalDeviceImageFormatProperties2 pvkGetPhysicalDeviceImageFormatProperties2 = nullptr;
    PFN_vkGetPhysicalDeviceImageFormatProperties2KHR pvkGetPhysicalDeviceImageFormatProperties2KHR = nullptr;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties2 pvkGetPhysicalDeviceQueueFamilyProperties2 = nullptr;
    PFN_vkGetPhysicalDeviceQueueFamilyProperties2KHR pvkGetPhysicalDeviceQueueFamilyProperties2KHR = nullptr;
    PFN_vkGetPhysicalDeviceMemoryProperties2 pvkGetPhysicalDeviceMemoryProperties2 = nullptr;
    PFN_vkGetPhysicalDeviceMemoryProperties2KHR pvkGetPhysicalDeviceMemoryProperties2KHR = nullptr;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties2 pvkGetPhysicalDeviceSparseImageFormatProperties2 = nullptr;
    PFN_vkGetPhysicalDeviceSparseImageFormatProperties2KHR pvkGetPhysicalDeviceSparseImageFormatProperties2KHR = nullptr;
    PFN_vkCmdPushDescriptorSet pvkCmdPushDescriptorSet = nullptr;
    PFN_vkCmdPushDescriptorSetKHR pvkCmdPushDescriptorSetKHR = nullptr;
    PFN_vkTrimCommandPool pvkTrimCommandPool = nullptr;
    PFN_vkTrimCommandPoolKHR pvkTrimCommandPoolKHR = nullptr;
    PFN_vkGetPhysicalDeviceExternalBufferProperties pvkGetPhysicalDeviceExternalBufferProperties = nullptr;
    PFN_vkGetPhysicalDeviceExternalBufferPropertiesKHR pvkGetPhysicalDeviceExternalBufferPropertiesKHR = nullptr;
    PFN_vkGetPhysicalDeviceExternalSemaphoreProperties pvkGetPhysicalDeviceExternalSemaphoreProperties = nullptr;
    PFN_vkGetPhysicalDeviceExternalSemaphorePropertiesKHR pvkGetPhysicalDeviceExternalSemaphorePropertiesKHR = nullptr;
    PFN_vkGetPhysicalDeviceExternalFenceProperties pvkGetPhysicalDeviceExternalFenceProperties = nullptr;
    PFN_vkGetPhysicalDeviceExternalFencePropertiesKHR pvkGetPhysicalDeviceExternalFencePropertiesKHR = nullptr;
    PFN_vkReleaseDisplayEXT pvkReleaseDisplayEXT = nullptr;
    PFN_vkDisplayPowerControlEXT pvkDisplayPowerControlEXT = nullptr;
    PFN_vkRegisterDeviceEventEXT pvkRegisterDeviceEventEXT = nullptr;
    PFN_vkRegisterDisplayEventEXT pvkRegisterDisplayEventEXT = nullptr;
    PFN_vkGetSwapchainCounterEXT pvkGetSwapchainCounterEXT = nullptr;
    PFN_vkGetPhysicalDeviceSurfaceCapabilities2EXT pvkGetPhysicalDeviceSurfaceCapabilities2EXT = nullptr;
    PFN_vkEnumeratePhysicalDeviceGroups pvkEnumeratePhysicalDeviceGroups = nullptr;
    PFN_vkEnumeratePhysicalDeviceGroupsKHR pvkEnumeratePhysicalDeviceGroupsKHR = nullptr;
    PFN_vkGetDeviceGroupPeerMemoryFeatures pvkGetDeviceGroupPeerMemoryFeatures = nullptr;
    PFN_vkGetDeviceGroupPeerMemoryFeaturesKHR pvkGetDeviceGroupPeerMemoryFeaturesKHR = nullptr;
    PFN_vkBindBufferMemory2 pvkBindBufferMemory2 = nullptr;
    PFN_vkBindBufferMemory2KHR pvkBindBufferMemory2KHR = nullptr;
    PFN_vkBindImageMemory2 pvkBindImageMemory2 = nullptr;
    PFN_vkBindImageMemory2KHR pvkBindImageMemory2KHR = nullptr;
    PFN_vkCmdSetDeviceMask pvkCmdSetDeviceMask = nullptr;
    PFN_vkCmdSetDeviceMaskKHR pvkCmdSetDeviceMaskKHR = nullptr;
    PFN_vkGetDeviceGroupPresentCapabilitiesKHR pvkGetDeviceGroupPresentCapabilitiesKHR = nullptr;
    PFN_vkGetDeviceGroupSurfacePresentModesKHR pvkGetDeviceGroupSurfacePresentModesKHR = nullptr;
    PFN_vkAcquireNextImage2KHR pvkAcquireNextImage2KHR = nullptr;
    PFN_vkCmdDispatchBase pvkCmdDispatchBase = nullptr;
    PFN_vkCmdDispatchBaseKHR pvkCmdDispatchBaseKHR = nullptr;
    PFN_vkGetPhysicalDevicePresentRectanglesKHR pvkGetPhysicalDevicePresentRectanglesKHR = nullptr;
    PFN_vkCreateDescriptorUpdateTemplate pvkCreateDescriptorUpdateTemplate = nullptr;
    PFN_vkCreateDescriptorUpdateTemplateKHR pvkCreateDescriptorUpdateTemplateKHR = nullptr;
    PFN_vkDestroyDescriptorUpdateTemplate pvkDestroyDescriptorUpdateTemplate = nullptr;
    PFN_vkDestroyDescriptorUpdateTemplateKHR pvkDestroyDescriptorUpdateTemplateKHR = nullptr;
    PFN_vkUpdateDescriptorSetWithTemplate pvkUpdateDescriptorSetWithTemplate = nullptr;
    PFN_vkUpdateDescriptorSetWithTemplateKHR pvkUpdateDescriptorSetWithTemplateKHR = nullptr;
    PFN_vkCmdPushDescriptorSetWithTemplate pvkCmdPushDescriptorSetWithTemplate = nullptr;
    PFN_vkCmdPushDescriptorSetWithTemplateKHR pvkCmdPushDescriptorSetWithTemplateKHR = nullptr;
    PFN_vkSetHdrMetadataEXT pvkSetHdrMetadataEXT = nullptr;
    PFN_vkCmdSetViewportWScalingNV pvkCmdSetViewportWScalingNV = nullptr;
    PFN_vkCmdSetDiscardRectangleEXT pvkCmdSetDiscardRectangleEXT = nullptr;
    PFN_vkCmdSetDiscardRectangleEnableEXT pvkCmdSetDiscardRectangleEnableEXT = nullptr;
    PFN_vkCmdSetDiscardRectangleModeEXT pvkCmdSetDiscardRectangleModeEXT = nullptr;
    PFN_vkCmdSetSampleLocationsEXT pvkCmdSetSampleLocationsEXT = nullptr;
    PFN_vkGetPhysicalDeviceMultisamplePropertiesEXT pvkGetPhysicalDeviceMultisamplePropertiesEXT = nullptr;
    PFN_vkGetPhysicalDeviceSurfaceCapabilities2KHR pvkGetPhysicalDeviceSurfaceCapabilities2KHR = nullptr;
    PFN_vkGetPhysicalDeviceSurfaceFormats2KHR pvkGetPhysicalDeviceSurfaceFormats2KHR = nullptr;
    PFN_vkGetPhysicalDeviceDisplayProperties2KHR pvkGetPhysicalDeviceDisplayProperties2KHR = nullptr;
    PFN_vkGetPhysicalDeviceDisplayPlaneProperties2KHR pvkGetPhysicalDeviceDisplayPlaneProperties2KHR = nullptr;
    PFN_vkGetDisplayModeProperties2KHR pvkGetDisplayModeProperties2KHR = nullptr;
    PFN_vkGetDisplayPlaneCapabilities2KHR pvkGetDisplayPlaneCapabilities2KHR = nullptr;
    PFN_vkGetBufferMemoryRequirements2 pvkGetBufferMemoryRequirements2 = nullptr;
    PFN_vkGetBufferMemoryRequirements2KHR pvkGetBufferMemoryRequirements2KHR = nullptr;
    PFN_vkGetImageMemoryRequirements2 pvkGetImageMemoryRequirements2 = nullptr;
    PFN_vkGetImageMemoryRequirements2KHR pvkGetImageMemoryRequirements2KHR = nullptr;
    PFN_vkGetImageSparseMemoryRequirements2 pvkGetImageSparseMemoryRequirements2 = nullptr;
    PFN_vkGetImageSparseMemoryRequirements2KHR pvkGetImageSparseMemoryRequirements2KHR = nullptr;
    PFN_vkGetDeviceBufferMemoryRequirements pvkGetDeviceBufferMemoryRequirements = nullptr;
    PFN_vkGetDeviceBufferMemoryRequirementsKHR pvkGetDeviceBufferMemoryRequirementsKHR = nullptr;
    PFN_vkGetDeviceImageMemoryRequirements pvkGetDeviceImageMemoryRequirements = nullptr;
    PFN_vkGetDeviceImageMemoryRequirementsKHR pvkGetDeviceImageMemoryRequirementsKHR = nullptr;
    PFN_vkGetDeviceImageSparseMemoryRequirements pvkGetDeviceImageSparseMemoryRequirements = nullptr;
    PFN_vkGetDeviceImageSparseMemoryRequirementsKHR pvkGetDeviceImageSparseMemoryRequirementsKHR = nullptr;
    PFN_vkCreateSamplerYcbcrConversion pvkCreateSamplerYcbcrConversion = nullptr;
    PFN_vkCreateSamplerYcbcrConversionKHR pvkCreateSamplerYcbcrConversionKHR = nullptr;
    PFN_vkDestroySamplerYcbcrConversion pvkDestroySamplerYcbcrConversion = nullptr;
    PFN_vkDestroySamplerYcbcrConversionKHR pvkDestroySamplerYcbcrConversionKHR = nullptr;
    PFN_vkGetDeviceQueue2 pvkGetDeviceQueue2 = nullptr;
    PFN_vkCreateValidationCacheEXT pvkCreateValidationCacheEXT = nullptr;
    PFN_vkDestroyValidationCacheEXT pvkDestroyValidationCacheEXT = nullptr;
    PFN_vkGetValidationCacheDataEXT pvkGetValidationCacheDataEXT = nullptr;
    PFN_vkMergeValidationCachesEXT pvkMergeValidationCachesEXT = nullptr;
    PFN_vkGetDescriptorSetLayoutSupport pvkGetDescriptorSetLayoutSupport = nullptr;
    PFN_vkGetDescriptorSetLayoutSupportKHR pvkGetDescriptorSetLayoutSupportKHR = nullptr;
    PFN_vkGetShaderInfoAMD pvkGetShaderInfoAMD = nullptr;
    PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsKHR pvkGetPhysicalDeviceCalibrateableTimeDomainsKHR = nullptr;
    PFN_vkGetPhysicalDeviceCalibrateableTimeDomainsEXT pvkGetPhysicalDeviceCalibrateableTimeDomainsEXT = nullptr;
    PFN_vkGetCalibratedTimestampsKHR pvkGetCalibratedTimestampsKHR = nullptr;
    PFN_vkGetCalibratedTimestampsEXT pvkGetCalibratedTimestampsEXT = nullptr;
    PFN_vkSetDebugUtilsObjectNameEXT pvkSetDebugUtilsObjectNameEXT = nullptr;
    PFN_vkSetDebugUtilsObjectTagEXT pvkSetDebugUtilsObjectTagEXT = nullptr;
    PFN_vkQueueBeginDebugUtilsLabelEXT pvkQueueBeginDebugUtilsLabelEXT = nullptr;
    PFN_vkQueueEndDebugUtilsLabelEXT pvkQueueEndDebugUtilsLabelEXT = nullptr;
    PFN_vkQueueInsertDebugUtilsLabelEXT pvkQueueInsertDebugUtilsLabelEXT = nullptr;
    PFN_vkCmdBeginDebugUtilsLabelEXT pvkCmdBeginDebugUtilsLabelEXT = nullptr;
    PFN_vkCmdEndDebugUtilsLabelEXT pvkCmdEndDebugUtilsLabelEXT = nullptr;
    PFN_vkCmdInsertDebugUtilsLabelEXT pvkCmdInsertDebugUtilsLabelEXT = nullptr;
    PFN_vkCreateDebugUtilsMessengerEXT pvkCreateDebugUtilsMessengerEXT = nullptr;
    PFN_vkDestroyDebugUtilsMessengerEXT pvkDestroyDebugUtilsMessengerEXT = nullptr;
    PFN_vkSubmitDebugUtilsMessageEXT pvkSubmitDebugUtilsMessageEXT = nullptr;
    PFN_vkGetMemoryHostPointerPropertiesEXT pvkGetMemoryHostPointerPropertiesEXT = nullptr;
    PFN_vkCmdWriteBufferMarkerAMD pvkCmdWriteBufferMarkerAMD = nullptr;
    PFN_vkCreateRenderPass2 pvkCreateRenderPass2 = nullptr;
    PFN_vkCreateRenderPass2KHR pvkCreateRenderPass2KHR = nullptr;
    PFN_vkCmdBeginRenderPass2 pvkCmdBeginRenderPass2 = nullptr;
    PFN_vkCmdBeginRenderPass2KHR pvkCmdBeginRenderPass2KHR = nullptr;
    PFN_vkCmdNextSubpass2 pvkCmdNextSubpass2 = nullptr;
    PFN_vkCmdNextSubpass2KHR pvkCmdNextSubpass2KHR = nullptr;
    PFN_vkCmdEndRenderPass2 pvkCmdEndRenderPass2 = nullptr;
    PFN_vkCmdEndRenderPass2KHR pvkCmdEndRenderPass2KHR = nullptr;
    PFN_vkGetSemaphoreCounterValue pvkGetSemaphoreCounterValue = nullptr;
    PFN_vkGetSemaphoreCounterValueKHR pvkGetSemaphoreCounterValueKHR = nullptr;
    PFN_vkWaitSemaphores pvkWaitSemaphores = nullptr;
    PFN_vkWaitSemaphoresKHR pvkWaitSemaphoresKHR = nullptr;
    PFN_vkSignalSemaphore pvkSignalSemaphore = nullptr;
    PFN_vkSignalSemaphoreKHR pvkSignalSemaphoreKHR = nullptr;
    PFN_vkCmdDrawIndirectCount pvkCmdDrawIndirectCount = nullptr;
    PFN_vkCmdDrawIndirectCountKHR pvkCmdDrawIndirectCountKHR = nullptr;
    PFN_vkCmdDrawIndirectCountAMD pvkCmdDrawIndirectCountAMD = nullptr;
    PFN_vkCmdDrawIndexedIndirectCount pvkCmdDrawIndexedIndirectCount = nullptr;
    PFN_vkCmdDrawIndexedIndirectCountKHR pvkCmdDrawIndexedIndirectCountKHR = nullptr;
    PFN_vkCmdDrawIndexedIndirectCountAMD pvkCmdDrawIndexedIndirectCountAMD = nullptr;
    PFN_vkCmdSetCheckpointNV pvkCmdSetCheckpointNV = nullptr;
    PFN_vkGetQueueCheckpointDataNV pvkGetQueueCheckpointDataNV = nullptr;
    PFN_vkCmdBindTransformFeedbackBuffersEXT pvkCmdBindTransformFeedbackBuffersEXT = nullptr;
    PFN_vkCmdBeginTransformFeedbackEXT pvkCmdBeginTransformFeedbackEXT = nullptr;
    PFN_vkCmdEndTransformFeedbackEXT pvkCmdEndTransformFeedbackEXT = nullptr;
    PFN_vkCmdBeginQueryIndexedEXT pvkCmdBeginQueryIndexedEXT = nullptr;
    PFN_vkCmdEndQueryIndexedEXT pvkCmdEndQueryIndexedEXT = nullptr;
    PFN_vkCmdDrawIndirectByteCountEXT pvkCmdDrawIndirectByteCountEXT = nullptr;
    PFN_vkCmdSetExclusiveScissorNV pvkCmdSetExclusiveScissorNV = nullptr;
    PFN_vkCmdSetExclusiveScissorEnableNV pvkCmdSetExclusiveScissorEnableNV = nullptr;
    PFN_vkCmdBindShadingRateImageNV pvkCmdBindShadingRateImageNV = nullptr;
    PFN_vkCmdSetViewportShadingRatePaletteNV pvkCmdSetViewportShadingRatePaletteNV = nullptr;
    PFN_vkCmdSetCoarseSampleOrderNV pvkCmdSetCoarseSampleOrderNV = nullptr;
    PFN_vkCmdDrawMeshTasksNV pvkCmdDrawMeshTasksNV = nullptr;
    PFN_vkCmdDrawMeshTasksIndirectNV pvkCmdDrawMeshTasksIndirectNV = nullptr;
    PFN_vkCmdDrawMeshTasksIndirectCountNV pvkCmdDrawMeshTasksIndirectCountNV = nullptr;
    PFN_vkCmdDrawMeshTasksEXT pvkCmdDrawMeshTasksEXT = nullptr;
    PFN_vkCmdDrawMeshTasksIndirectEXT pvkCmdDrawMeshTasksIndirectEXT = nullptr;
    PFN_vkCmdDrawMeshTasksIndirectCountEXT pvkCmdDrawMeshTasksIndirectCountEXT = nullptr;
    PFN_vkCompileDeferredNV pvkCompileDeferredNV = nullptr;
    PFN_vkCreateAccelerationStructureNV pvkCreateAccelerationStructureNV = nullptr;
    PFN_vkCmdBindInvocationMaskHUAWEI pvkCmdBindInvocationMaskHUAWEI = nullptr;
    PFN_vkDestroyAccelerationStructureKHR pvkDestroyAccelerationStructureKHR = nullptr;
    PFN_vkDestroyAccelerationStructureNV pvkDestroyAccelerationStructureNV = nullptr;
    PFN_vkGetAccelerationStructureMemoryRequirementsNV pvkGetAccelerationStructureMemoryRequirementsNV = nullptr;
    PFN_vkBindAccelerationStructureMemoryNV pvkBindAccelerationStructureMemoryNV = nullptr;
    PFN_vkCmdCopyAccelerationStructureNV pvkCmdCopyAccelerationStructureNV = nullptr;
    PFN_vkCmdCopyAccelerationStructureKHR pvkCmdCopyAccelerationStructureKHR = nullptr;
    PFN_vkCopyAccelerationStructureKHR pvkCopyAccelerationStructureKHR = nullptr;
    PFN_vkCmdCopyAccelerationStructureToMemoryKHR pvkCmdCopyAccelerationStructureToMemoryKHR = nullptr;
    PFN_vkCopyAccelerationStructureToMemoryKHR pvkCopyAccelerationStructureToMemoryKHR = nullptr;
    PFN_vkCmdCopyMemoryToAccelerationStructureKHR pvkCmdCopyMemoryToAccelerationStructureKHR = nullptr;
    PFN_vkCopyMemoryToAccelerationStructureKHR pvkCopyMemoryToAccelerationStructureKHR = nullptr;
    PFN_vkCmdWriteAccelerationStructuresPropertiesKHR pvkCmdWriteAccelerationStructuresPropertiesKHR = nullptr;
    PFN_vkCmdWriteAccelerationStructuresPropertiesNV pvkCmdWriteAccelerationStructuresPropertiesNV = nullptr;
    PFN_vkCmdBuildAccelerationStructureNV pvkCmdBuildAccelerationStructureNV = nullptr;
    PFN_vkWriteAccelerationStructuresPropertiesKHR pvkWriteAccelerationStructuresPropertiesKHR = nullptr;
    PFN_vkCmdTraceRaysKHR pvkCmdTraceRaysKHR = nullptr;
    PFN_vkCmdTraceRaysNV pvkCmdTraceRaysNV = nullptr;
    PFN_vkGetRayTracingShaderGroupHandlesKHR pvkGetRayTracingShaderGroupHandlesKHR = nullptr;
    PFN_vkGetRayTracingShaderGroupHandlesNV pvkGetRayTracingShaderGroupHandlesNV = nullptr;
    PFN_vkGetRayTracingCaptureReplayShaderGroupHandlesKHR pvkGetRayTracingCaptureReplayShaderGroupHandlesKHR = nullptr;
    PFN_vkGetAccelerationStructureHandleNV pvkGetAccelerationStructureHandleNV = nullptr;
    PFN_vkCreateRayTracingPipelinesNV pvkCreateRayTracingPipelinesNV = nullptr;
    PFN_vkCreateRayTracingPipelinesKHR pvkCreateRayTracingPipelinesKHR = nullptr;
    PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesNV pvkGetPhysicalDeviceCooperativeMatrixPropertiesNV = nullptr;
    PFN_vkCmdTraceRaysIndirectKHR pvkCmdTraceRaysIndirectKHR = nullptr;
    PFN_vkCmdTraceRaysIndirect2KHR pvkCmdTraceRaysIndirect2KHR = nullptr;
    PFN_vkGetDeviceAccelerationStructureCompatibilityKHR pvkGetDeviceAccelerationStructureCompatibilityKHR = nullptr;
    PFN_vkGetRayTracingShaderGroupStackSizeKHR pvkGetRayTracingShaderGroupStackSizeKHR = nullptr;
    PFN_vkCmdSetRayTracingPipelineStackSizeKHR pvkCmdSetRayTracingPipelineStackSizeKHR = nullptr;
    PFN_vkGetImageViewHandleNVX pvkGetImageViewHandleNVX = nullptr;
    PFN_vkGetImageViewHandle64NVX pvkGetImageViewHandle64NVX = nullptr;
    PFN_vkGetImageViewAddressNVX pvkGetImageViewAddressNVX = nullptr;
    PFN_vkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR pvkEnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR = nullptr;
    PFN_vkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR pvkGetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR = nullptr;
    PFN_vkAcquireProfilingLockKHR pvkAcquireProfilingLockKHR = nullptr;
    PFN_vkReleaseProfilingLockKHR pvkReleaseProfilingLockKHR = nullptr;
    PFN_vkGetBufferOpaqueCaptureAddress pvkGetBufferOpaqueCaptureAddress = nullptr;
    PFN_vkGetBufferOpaqueCaptureAddressKHR pvkGetBufferOpaqueCaptureAddressKHR = nullptr;
    PFN_vkGetBufferDeviceAddress pvkGetBufferDeviceAddress = nullptr;
    PFN_vkGetBufferDeviceAddressKHR pvkGetBufferDeviceAddressKHR = nullptr;
    PFN_vkGetBufferDeviceAddressEXT pvkGetBufferDeviceAddressEXT = nullptr;
    PFN_vkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV pvkGetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV = nullptr;
    PFN_vkInitializePerformanceApiINTEL pvkInitializePerformanceApiINTEL = nullptr;
    PFN_vkUninitializePerformanceApiINTEL pvkUninitializePerformanceApiINTEL = nullptr;
    PFN_vkCmdSetPerformanceMarkerINTEL pvkCmdSetPerformanceMarkerINTEL = nullptr;
    PFN_vkCmdSetPerformanceStreamMarkerINTEL pvkCmdSetPerformanceStreamMarkerINTEL = nullptr;
    PFN_vkCmdSetPerformanceOverrideINTEL pvkCmdSetPerformanceOverrideINTEL = nullptr;
    PFN_vkAcquirePerformanceConfigurationINTEL pvkAcquirePerformanceConfigurationINTEL = nullptr;
    PFN_vkReleasePerformanceConfigurationINTEL pvkReleasePerformanceConfigurationINTEL = nullptr;
    PFN_vkQueueSetPerformanceConfigurationINTEL pvkQueueSetPerformanceConfigurationINTEL = nullptr;
    PFN_vkGetPerformanceParameterINTEL pvkGetPerformanceParameterINTEL = nullptr;
    PFN_vkGetDeviceMemoryOpaqueCaptureAddress pvkGetDeviceMemoryOpaqueCaptureAddress = nullptr;
    PFN_vkGetDeviceMemoryOpaqueCaptureAddressKHR pvkGetDeviceMemoryOpaqueCaptureAddressKHR = nullptr;
    PFN_vkGetPipelineExecutablePropertiesKHR pvkGetPipelineExecutablePropertiesKHR = nullptr;
    PFN_vkGetPipelineExecutableStatisticsKHR pvkGetPipelineExecutableStatisticsKHR = nullptr;
    PFN_vkGetPipelineExecutableInternalRepresentationsKHR pvkGetPipelineExecutableInternalRepresentationsKHR = nullptr;
    PFN_vkCmdSetLineStipple pvkCmdSetLineStipple = nullptr;
    PFN_vkCmdSetLineStippleKHR pvkCmdSetLineStippleKHR = nullptr;
    PFN_vkCmdSetLineStippleEXT pvkCmdSetLineStippleEXT = nullptr;
    PFN_vkGetPhysicalDeviceToolProperties pvkGetPhysicalDeviceToolProperties = nullptr;
    PFN_vkGetPhysicalDeviceToolPropertiesEXT pvkGetPhysicalDeviceToolPropertiesEXT = nullptr;
    PFN_vkCreateAccelerationStructureKHR pvkCreateAccelerationStructureKHR = nullptr;
    PFN_vkCmdBuildAccelerationStructuresKHR pvkCmdBuildAccelerationStructuresKHR = nullptr;
    PFN_vkCmdBuildAccelerationStructuresIndirectKHR pvkCmdBuildAccelerationStructuresIndirectKHR = nullptr;
    PFN_vkBuildAccelerationStructuresKHR pvkBuildAccelerationStructuresKHR = nullptr;
    PFN_vkGetAccelerationStructureDeviceAddressKHR pvkGetAccelerationStructureDeviceAddressKHR = nullptr;
    PFN_vkCreateDeferredOperationKHR pvkCreateDeferredOperationKHR = nullptr;
    PFN_vkDestroyDeferredOperationKHR pvkDestroyDeferredOperationKHR = nullptr;
    PFN_vkGetDeferredOperationMaxConcurrencyKHR pvkGetDeferredOperationMaxConcurrencyKHR = nullptr;
    PFN_vkGetDeferredOperationResultKHR pvkGetDeferredOperationResultKHR = nullptr;
    PFN_vkDeferredOperationJoinKHR pvkDeferredOperationJoinKHR = nullptr;
    PFN_vkGetPipelineIndirectMemoryRequirementsNV pvkGetPipelineIndirectMemoryRequirementsNV = nullptr;
    PFN_vkGetPipelineIndirectDeviceAddressNV pvkGetPipelineIndirectDeviceAddressNV = nullptr;
    PFN_vkAntiLagUpdateAMD pvkAntiLagUpdateAMD = nullptr;
    PFN_vkCmdSetCullMode pvkCmdSetCullMode = nullptr;
    PFN_vkCmdSetCullModeEXT pvkCmdSetCullModeEXT = nullptr;
    PFN_vkCmdSetFrontFace pvkCmdSetFrontFace = nullptr;
    PFN_vkCmdSetFrontFaceEXT pvkCmdSetFrontFaceEXT = nullptr;
    PFN_vkCmdSetPrimitiveTopology pvkCmdSetPrimitiveTopology = nullptr;
    PFN_vkCmdSetPrimitiveTopologyEXT pvkCmdSetPrimitiveTopologyEXT = nullptr;
    PFN_vkCmdSetViewportWithCount pvkCmdSetViewportWithCount = nullptr;
    PFN_vkCmdSetViewportWithCountEXT pvkCmdSetViewportWithCountEXT = nullptr;
    PFN_vkCmdSetScissorWithCount pvkCmdSetScissorWithCount = nullptr;
    PFN_vkCmdSetScissorWithCountEXT pvkCmdSetScissorWithCountEXT = nullptr;
    PFN_vkCmdBindIndexBuffer2 pvkCmdBindIndexBuffer2 = nullptr;
    PFN_vkCmdBindIndexBuffer2KHR pvkCmdBindIndexBuffer2KHR = nullptr;
    PFN_vkCmdBindVertexBuffers2 pvkCmdBindVertexBuffers2 = nullptr;
    PFN_vkCmdBindVertexBuffers2EXT pvkCmdBindVertexBuffers2EXT = nullptr;
    PFN_vkCmdSetDepthTestEnable pvkCmdSetDepthTestEnable = nullptr;
    PFN_vkCmdSetDepthTestEnableEXT pvkCmdSetDepthTestEnableEXT = nullptr;
    PFN_vkCmdSetDepthWriteEnable pvkCmdSetDepthWriteEnable = nullptr;
    PFN_vkCmdSetDepthWriteEnableEXT pvkCmdSetDepthWriteEnableEXT = nullptr;
    PFN_vkCmdSetDepthCompareOp pvkCmdSetDepthCompareOp = nullptr;
    PFN_vkCmdSetDepthCompareOpEXT pvkCmdSetDepthCompareOpEXT = nullptr;
    PFN_vkCmdSetDepthBoundsTestEnable pvkCmdSetDepthBoundsTestEnable = nullptr;
    PFN_vkCmdSetDepthBoundsTestEnableEXT pvkCmdSetDepthBoundsTestEnableEXT = nullptr;
    PFN_vkCmdSetStencilTestEnable pvkCmdSetStencilTestEnable = nullptr;
    PFN_vkCmdSetStencilTestEnableEXT pvkCmdSetStencilTestEnableEXT = nullptr;
    PFN_vkCmdSetStencilOp pvkCmdSetStencilOp = nullptr;
    PFN_vkCmdSetStencilOpEXT pvkCmdSetStencilOpEXT = nullptr;
    PFN_vkCmdSetPatchControlPointsEXT pvkCmdSetPatchControlPointsEXT = nullptr;
    PFN_vkCmdSetRasterizerDiscardEnable pvkCmdSetRasterizerDiscardEnable = nullptr;
    PFN_vkCmdSetRasterizerDiscardEnableEXT pvkCmdSetRasterizerDiscardEnableEXT = nullptr;
    PFN_vkCmdSetDepthBiasEnable pvkCmdSetDepthBiasEnable = nullptr;
    PFN_vkCmdSetDepthBiasEnableEXT pvkCmdSetDepthBiasEnableEXT = nullptr;
    PFN_vkCmdSetLogicOpEXT pvkCmdSetLogicOpEXT = nullptr;
    PFN_vkCmdSetPrimitiveRestartEnable pvkCmdSetPrimitiveRestartEnable = nullptr;
    PFN_vkCmdSetPrimitiveRestartEnableEXT pvkCmdSetPrimitiveRestartEnableEXT = nullptr;
    PFN_vkCmdSetTessellationDomainOriginEXT pvkCmdSetTessellationDomainOriginEXT = nullptr;
    PFN_vkCmdSetDepthClampEnableEXT pvkCmdSetDepthClampEnableEXT = nullptr;
    PFN_vkCmdSetPolygonModeEXT pvkCmdSetPolygonModeEXT = nullptr;
    PFN_vkCmdSetRasterizationSamplesEXT pvkCmdSetRasterizationSamplesEXT = nullptr;
    PFN_vkCmdSetSampleMaskEXT pvkCmdSetSampleMaskEXT = nullptr;
    PFN_vkCmdSetAlphaToCoverageEnableEXT pvkCmdSetAlphaToCoverageEnableEXT = nullptr;
    PFN_vkCmdSetAlphaToOneEnableEXT pvkCmdSetAlphaToOneEnableEXT = nullptr;
    PFN_vkCmdSetLogicOpEnableEXT pvkCmdSetLogicOpEnableEXT = nullptr;
    PFN_vkCmdSetColorBlendEnableEXT pvkCmdSetColorBlendEnableEXT = nullptr;
    PFN_vkCmdSetColorBlendEquationEXT pvkCmdSetColorBlendEquationEXT = nullptr;
    PFN_vkCmdSetColorWriteMaskEXT pvkCmdSetColorWriteMaskEXT = nullptr;
    PFN_vkCmdSetRasterizationStreamEXT pvkCmdSetRasterizationStreamEXT = nullptr;
    PFN_vkCmdSetConservativeRasterizationModeEXT pvkCmdSetConservativeRasterizationModeEXT = nullptr;
    PFN_vkCmdSetExtraPrimitiveOverestimationSizeEXT pvkCmdSetExtraPrimitiveOverestimationSizeEXT = nullptr;
    PFN_vkCmdSetDepthClipEnableEXT pvkCmdSetDepthClipEnableEXT = nullptr;
    PFN_vkCmdSetSampleLocationsEnableEXT pvkCmdSetSampleLocationsEnableEXT = nullptr;
    PFN_vkCmdSetColorBlendAdvancedEXT pvkCmdSetColorBlendAdvancedEXT = nullptr;
    PFN_vkCmdSetProvokingVertexModeEXT pvkCmdSetProvokingVertexModeEXT = nullptr;
    PFN_vkCmdSetLineRasterizationModeEXT pvkCmdSetLineRasterizationModeEXT = nullptr;
    PFN_vkCmdSetLineStippleEnableEXT pvkCmdSetLineStippleEnableEXT = nullptr;
    PFN_vkCmdSetDepthClipNegativeOneToOneEXT pvkCmdSetDepthClipNegativeOneToOneEXT = nullptr;
    PFN_vkCmdSetViewportWScalingEnableNV pvkCmdSetViewportWScalingEnableNV = nullptr;
    PFN_vkCmdSetViewportSwizzleNV pvkCmdSetViewportSwizzleNV = nullptr;
    PFN_vkCmdSetCoverageToColorEnableNV pvkCmdSetCoverageToColorEnableNV = nullptr;
    PFN_vkCmdSetCoverageToColorLocationNV pvkCmdSetCoverageToColorLocationNV = nullptr;
    PFN_vkCmdSetCoverageModulationModeNV pvkCmdSetCoverageModulationModeNV = nullptr;
    PFN_vkCmdSetCoverageModulationTableEnableNV pvkCmdSetCoverageModulationTableEnableNV = nullptr;
    PFN_vkCmdSetCoverageModulationTableNV pvkCmdSetCoverageModulationTableNV = nullptr;
    PFN_vkCmdSetShadingRateImageEnableNV pvkCmdSetShadingRateImageEnableNV = nullptr;
    PFN_vkCmdSetCoverageReductionModeNV pvkCmdSetCoverageReductionModeNV = nullptr;
    PFN_vkCmdSetRepresentativeFragmentTestEnableNV pvkCmdSetRepresentativeFragmentTestEnableNV = nullptr;
    PFN_vkCreatePrivateDataSlot pvkCreatePrivateDataSlot = nullptr;
    PFN_vkCreatePrivateDataSlotEXT pvkCreatePrivateDataSlotEXT = nullptr;
    PFN_vkDestroyPrivateDataSlot pvkDestroyPrivateDataSlot = nullptr;
    PFN_vkDestroyPrivateDataSlotEXT pvkDestroyPrivateDataSlotEXT = nullptr;
    PFN_vkSetPrivateData pvkSetPrivateData = nullptr;
    PFN_vkSetPrivateDataEXT pvkSetPrivateDataEXT = nullptr;
    PFN_vkGetPrivateData pvkGetPrivateData = nullptr;
    PFN_vkGetPrivateDataEXT pvkGetPrivateDataEXT = nullptr;
    PFN_vkCmdCopyBuffer2 pvkCmdCopyBuffer2 = nullptr;
    PFN_vkCmdCopyBuffer2KHR pvkCmdCopyBuffer2KHR = nullptr;
    PFN_vkCmdCopyImage2 pvkCmdCopyImage2 = nullptr;
    PFN_vkCmdCopyImage2KHR pvkCmdCopyImage2KHR = nullptr;
    PFN_vkCmdBlitImage2 pvkCmdBlitImage2 = nullptr;
    PFN_vkCmdBlitImage2KHR pvkCmdBlitImage2KHR = nullptr;
    PFN_vkCmdCopyBufferToImage2 pvkCmdCopyBufferToImage2 = nullptr;
    PFN_vkCmdCopyBufferToImage2KHR pvkCmdCopyBufferToImage2KHR = nullptr;
    PFN_vkCmdCopyImageToBuffer2 pvkCmdCopyImageToBuffer2 = nullptr;
    PFN_vkCmdCopyImageToBuffer2KHR pvkCmdCopyImageToBuffer2KHR = nullptr;
    PFN_vkCmdResolveImage2 pvkCmdResolveImage2 = nullptr;
    PFN_vkCmdResolveImage2KHR pvkCmdResolveImage2KHR = nullptr;
    PFN_vkCmdSetFragmentShadingRateKHR pvkCmdSetFragmentShadingRateKHR = nullptr;
    PFN_vkGetPhysicalDeviceFragmentShadingRatesKHR pvkGetPhysicalDeviceFragmentShadingRatesKHR = nullptr;
    PFN_vkCmdSetFragmentShadingRateEnumNV pvkCmdSetFragmentShadingRateEnumNV = nullptr;
    PFN_vkGetAccelerationStructureBuildSizesKHR pvkGetAccelerationStructureBuildSizesKHR = nullptr;
    PFN_vkCmdSetVertexInputEXT pvkCmdSetVertexInputEXT = nullptr;
    PFN_vkCmdSetColorWriteEnableEXT pvkCmdSetColorWriteEnableEXT = nullptr;
    PFN_vkCmdSetEvent2 pvkCmdSetEvent2 = nullptr;
    PFN_vkCmdSetEvent2KHR pvkCmdSetEvent2KHR = nullptr;
    PFN_vkCmdResetEvent2 pvkCmdResetEvent2 = nullptr;
    PFN_vkCmdResetEvent2KHR pvkCmdResetEvent2KHR = nullptr;
    PFN_vkCmdWaitEvents2 pvkCmdWaitEvents2 = nullptr;
    PFN_vkCmdWaitEvents2KHR pvkCmdWaitEvents2KHR = nullptr;
    PFN_vkCmdPipelineBarrier2 pvkCmdPipelineBarrier2 = nullptr;
    PFN_vkCmdPipelineBarrier2KHR pvkCmdPipelineBarrier2KHR = nullptr;
    PFN_vkQueueSubmit2 pvkQueueSubmit2 = nullptr;
    PFN_vkQueueSubmit2KHR pvkQueueSubmit2KHR = nullptr;
    PFN_vkCmdWriteTimestamp2 pvkCmdWriteTimestamp2 = nullptr;
    PFN_vkCmdWriteTimestamp2KHR pvkCmdWriteTimestamp2KHR = nullptr;
    PFN_vkCmdWriteBufferMarker2AMD pvkCmdWriteBufferMarker2AMD = nullptr;
    PFN_vkGetQueueCheckpointData2NV pvkGetQueueCheckpointData2NV = nullptr;
    PFN_vkCopyMemoryToImage pvkCopyMemoryToImage = nullptr;
    PFN_vkCopyMemoryToImageEXT pvkCopyMemoryToImageEXT = nullptr;
    PFN_vkCopyImageToMemory pvkCopyImageToMemory = nullptr;
    PFN_vkCopyImageToMemoryEXT pvkCopyImageToMemoryEXT = nullptr;
    PFN_vkCopyImageToImage pvkCopyImageToImage = nullptr;
    PFN_vkCopyImageToImageEXT pvkCopyImageToImageEXT = nullptr;
    PFN_vkTransitionImageLayout pvkTransitionImageLayout = nullptr;
    PFN_vkTransitionImageLayoutEXT pvkTransitionImageLayoutEXT = nullptr;
    PFN_vkGetPhysicalDeviceVideoCapabilitiesKHR pvkGetPhysicalDeviceVideoCapabilitiesKHR = nullptr;
    PFN_vkGetPhysicalDeviceVideoFormatPropertiesKHR pvkGetPhysicalDeviceVideoFormatPropertiesKHR = nullptr;
    PFN_vkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR pvkGetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR = nullptr;
    PFN_vkCreateVideoSessionKHR pvkCreateVideoSessionKHR = nullptr;
    PFN_vkDestroyVideoSessionKHR pvkDestroyVideoSessionKHR = nullptr;
    PFN_vkCreateVideoSessionParametersKHR pvkCreateVideoSessionParametersKHR = nullptr;
    PFN_vkUpdateVideoSessionParametersKHR pvkUpdateVideoSessionParametersKHR = nullptr;
    PFN_vkGetEncodedVideoSessionParametersKHR pvkGetEncodedVideoSessionParametersKHR = nullptr;
    PFN_vkDestroyVideoSessionParametersKHR pvkDestroyVideoSessionParametersKHR = nullptr;
    PFN_vkGetVideoSessionMemoryRequirementsKHR pvkGetVideoSessionMemoryRequirementsKHR = nullptr;
    PFN_vkBindVideoSessionMemoryKHR pvkBindVideoSessionMemoryKHR = nullptr;
    PFN_vkCmdDecodeVideoKHR pvkCmdDecodeVideoKHR = nullptr;
    PFN_vkCmdBeginVideoCodingKHR pvkCmdBeginVideoCodingKHR = nullptr;
    PFN_vkCmdControlVideoCodingKHR pvkCmdControlVideoCodingKHR = nullptr;
    PFN_vkCmdEndVideoCodingKHR pvkCmdEndVideoCodingKHR = nullptr;
    PFN_vkCmdEncodeVideoKHR pvkCmdEncodeVideoKHR = nullptr;
    PFN_vkCmdDecompressMemoryNV pvkCmdDecompressMemoryNV = nullptr;
    PFN_vkCmdDecompressMemoryIndirectCountNV pvkCmdDecompressMemoryIndirectCountNV = nullptr;
    PFN_vkGetPartitionedAccelerationStructuresBuildSizesNV pvkGetPartitionedAccelerationStructuresBuildSizesNV = nullptr;
    PFN_vkCmdBuildPartitionedAccelerationStructuresNV pvkCmdBuildPartitionedAccelerationStructuresNV = nullptr;
    PFN_vkCmdDecompressMemoryEXT pvkCmdDecompressMemoryEXT = nullptr;
    PFN_vkCmdDecompressMemoryIndirectCountEXT pvkCmdDecompressMemoryIndirectCountEXT = nullptr;
    PFN_vkCreateCuModuleNVX pvkCreateCuModuleNVX = nullptr;
    PFN_vkCreateCuFunctionNVX pvkCreateCuFunctionNVX = nullptr;
    PFN_vkDestroyCuModuleNVX pvkDestroyCuModuleNVX = nullptr;
    PFN_vkDestroyCuFunctionNVX pvkDestroyCuFunctionNVX = nullptr;
    PFN_vkCmdCuLaunchKernelNVX pvkCmdCuLaunchKernelNVX = nullptr;
    PFN_vkGetDescriptorSetLayoutSizeEXT pvkGetDescriptorSetLayoutSizeEXT = nullptr;
    PFN_vkGetDescriptorSetLayoutBindingOffsetEXT pvkGetDescriptorSetLayoutBindingOffsetEXT = nullptr;
    PFN_vkGetDescriptorEXT pvkGetDescriptorEXT = nullptr;
    PFN_vkCmdBindDescriptorBuffersEXT pvkCmdBindDescriptorBuffersEXT = nullptr;
    PFN_vkCmdSetDescriptorBufferOffsetsEXT pvkCmdSetDescriptorBufferOffsetsEXT = nullptr;
    PFN_vkCmdBindDescriptorBufferEmbeddedSamplersEXT pvkCmdBindDescriptorBufferEmbeddedSamplersEXT = nullptr;
    PFN_vkGetBufferOpaqueCaptureDescriptorDataEXT pvkGetBufferOpaqueCaptureDescriptorDataEXT = nullptr;
    PFN_vkGetImageOpaqueCaptureDescriptorDataEXT pvkGetImageOpaqueCaptureDescriptorDataEXT = nullptr;
    PFN_vkGetImageViewOpaqueCaptureDescriptorDataEXT pvkGetImageViewOpaqueCaptureDescriptorDataEXT = nullptr;
    PFN_vkGetSamplerOpaqueCaptureDescriptorDataEXT pvkGetSamplerOpaqueCaptureDescriptorDataEXT = nullptr;
    PFN_vkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT pvkGetAccelerationStructureOpaqueCaptureDescriptorDataEXT = nullptr;
    PFN_vkSetDeviceMemoryPriorityEXT pvkSetDeviceMemoryPriorityEXT = nullptr;
    PFN_vkAcquireDrmDisplayEXT pvkAcquireDrmDisplayEXT = nullptr;
    PFN_vkGetDrmDisplayEXT pvkGetDrmDisplayEXT = nullptr;
    PFN_vkWaitForPresent2KHR pvkWaitForPresent2KHR = nullptr;
    PFN_vkWaitForPresentKHR pvkWaitForPresentKHR = nullptr;
    PFN_vkCmdBeginRendering pvkCmdBeginRendering = nullptr;
    PFN_vkCmdBeginRenderingKHR pvkCmdBeginRenderingKHR = nullptr;
    PFN_vkCmdEndRendering pvkCmdEndRendering = nullptr;
    PFN_vkCmdEndRendering2KHR pvkCmdEndRendering2KHR = nullptr;
    PFN_vkCmdEndRendering2EXT pvkCmdEndRendering2EXT = nullptr;
    PFN_vkCmdEndRenderingKHR pvkCmdEndRenderingKHR = nullptr;
    PFN_vkGetDescriptorSetLayoutHostMappingInfoVALVE pvkGetDescriptorSetLayoutHostMappingInfoVALVE = nullptr;
    PFN_vkGetDescriptorSetHostMappingVALVE pvkGetDescriptorSetHostMappingVALVE = nullptr;
    PFN_vkCreateMicromapEXT pvkCreateMicromapEXT = nullptr;
    PFN_vkCmdBuildMicromapsEXT pvkCmdBuildMicromapsEXT = nullptr;
    PFN_vkBuildMicromapsEXT pvkBuildMicromapsEXT = nullptr;
    PFN_vkDestroyMicromapEXT pvkDestroyMicromapEXT = nullptr;
    PFN_vkCmdCopyMicromapEXT pvkCmdCopyMicromapEXT = nullptr;
    PFN_vkCopyMicromapEXT pvkCopyMicromapEXT = nullptr;
    PFN_vkCmdCopyMicromapToMemoryEXT pvkCmdCopyMicromapToMemoryEXT = nullptr;
    PFN_vkCopyMicromapToMemoryEXT pvkCopyMicromapToMemoryEXT = nullptr;
    PFN_vkCmdCopyMemoryToMicromapEXT pvkCmdCopyMemoryToMicromapEXT = nullptr;
    PFN_vkCopyMemoryToMicromapEXT pvkCopyMemoryToMicromapEXT = nullptr;
    PFN_vkCmdWriteMicromapsPropertiesEXT pvkCmdWriteMicromapsPropertiesEXT = nullptr;
    PFN_vkWriteMicromapsPropertiesEXT pvkWriteMicromapsPropertiesEXT = nullptr;
    PFN_vkGetDeviceMicromapCompatibilityEXT pvkGetDeviceMicromapCompatibilityEXT = nullptr;
    PFN_vkGetMicromapBuildSizesEXT pvkGetMicromapBuildSizesEXT = nullptr;
    PFN_vkGetShaderModuleIdentifierEXT pvkGetShaderModuleIdentifierEXT = nullptr;
    PFN_vkGetShaderModuleCreateInfoIdentifierEXT pvkGetShaderModuleCreateInfoIdentifierEXT = nullptr;
    PFN_vkGetImageSubresourceLayout2 pvkGetImageSubresourceLayout2 = nullptr;
    PFN_vkGetImageSubresourceLayout2KHR pvkGetImageSubresourceLayout2KHR = nullptr;
    PFN_vkGetImageSubresourceLayout2EXT pvkGetImageSubresourceLayout2EXT = nullptr;
    PFN_vkGetPipelinePropertiesEXT pvkGetPipelinePropertiesEXT = nullptr;
    PFN_vkCmdBindTileMemoryQCOM pvkCmdBindTileMemoryQCOM = nullptr;
    PFN_vkGetFramebufferTilePropertiesQCOM pvkGetFramebufferTilePropertiesQCOM = nullptr;
    PFN_vkGetDynamicRenderingTilePropertiesQCOM pvkGetDynamicRenderingTilePropertiesQCOM = nullptr;
    PFN_vkGetPhysicalDeviceOpticalFlowImageFormatsNV pvkGetPhysicalDeviceOpticalFlowImageFormatsNV = nullptr;
    PFN_vkCreateOpticalFlowSessionNV pvkCreateOpticalFlowSessionNV = nullptr;
    PFN_vkDestroyOpticalFlowSessionNV pvkDestroyOpticalFlowSessionNV = nullptr;
    PFN_vkBindOpticalFlowSessionImageNV pvkBindOpticalFlowSessionImageNV = nullptr;
    PFN_vkCmdOpticalFlowExecuteNV pvkCmdOpticalFlowExecuteNV = nullptr;
    PFN_vkGetDeviceFaultInfoEXT pvkGetDeviceFaultInfoEXT = nullptr;
    PFN_vkCmdSetDepthBias2EXT pvkCmdSetDepthBias2EXT = nullptr;
    PFN_vkReleaseSwapchainImagesKHR pvkReleaseSwapchainImagesKHR = nullptr;
    PFN_vkReleaseSwapchainImagesEXT pvkReleaseSwapchainImagesEXT = nullptr;
    PFN_vkGetDeviceImageSubresourceLayout pvkGetDeviceImageSubresourceLayout = nullptr;
    PFN_vkGetDeviceImageSubresourceLayoutKHR pvkGetDeviceImageSubresourceLayoutKHR = nullptr;
    PFN_vkMapMemory2 pvkMapMemory2 = nullptr;
    PFN_vkMapMemory2KHR pvkMapMemory2KHR = nullptr;
    PFN_vkUnmapMemory2 pvkUnmapMemory2 = nullptr;
    PFN_vkUnmapMemory2KHR pvkUnmapMemory2KHR = nullptr;
    PFN_vkCreateShadersEXT pvkCreateShadersEXT = nullptr;
    PFN_vkDestroyShaderEXT pvkDestroyShaderEXT = nullptr;
    PFN_vkGetShaderBinaryDataEXT pvkGetShaderBinaryDataEXT = nullptr;
    PFN_vkCmdBindShadersEXT pvkCmdBindShadersEXT = nullptr;
    PFN_vkSetSwapchainPresentTimingQueueSizeEXT pvkSetSwapchainPresentTimingQueueSizeEXT = nullptr;
    PFN_vkGetSwapchainTimingPropertiesEXT pvkGetSwapchainTimingPropertiesEXT = nullptr;
    PFN_vkGetSwapchainTimeDomainPropertiesEXT pvkGetSwapchainTimeDomainPropertiesEXT = nullptr;
    PFN_vkGetPastPresentationTimingEXT pvkGetPastPresentationTimingEXT = nullptr;
    PFN_vkGetPhysicalDeviceCooperativeMatrixPropertiesKHR pvkGetPhysicalDeviceCooperativeMatrixPropertiesKHR = nullptr;
    PFN_vkCmdBindDescriptorSets2 pvkCmdBindDescriptorSets2 = nullptr;
    PFN_vkCmdBindDescriptorSets2KHR pvkCmdBindDescriptorSets2KHR = nullptr;
    PFN_vkCmdPushConstants2 pvkCmdPushConstants2 = nullptr;
    PFN_vkCmdPushConstants2KHR pvkCmdPushConstants2KHR = nullptr;
    PFN_vkCmdPushDescriptorSet2 pvkCmdPushDescriptorSet2 = nullptr;
    PFN_vkCmdPushDescriptorSet2KHR pvkCmdPushDescriptorSet2KHR = nullptr;
    PFN_vkCmdPushDescriptorSetWithTemplate2 pvkCmdPushDescriptorSetWithTemplate2 = nullptr;
    PFN_vkCmdPushDescriptorSetWithTemplate2KHR pvkCmdPushDescriptorSetWithTemplate2KHR = nullptr;
    PFN_vkCmdSetDescriptorBufferOffsets2EXT pvkCmdSetDescriptorBufferOffsets2EXT = nullptr;
    PFN_vkCmdBindDescriptorBufferEmbeddedSamplers2EXT pvkCmdBindDescriptorBufferEmbeddedSamplers2EXT = nullptr;
    PFN_vkSetLatencySleepModeNV pvkSetLatencySleepModeNV = nullptr;
    PFN_vkLatencySleepNV pvkLatencySleepNV = nullptr;
    PFN_vkSetLatencyMarkerNV pvkSetLatencyMarkerNV = nullptr;
    PFN_vkGetLatencyTimingsNV pvkGetLatencyTimingsNV = nullptr;
    PFN_vkQueueNotifyOutOfBandNV pvkQueueNotifyOutOfBandNV = nullptr;
    PFN_vkCmdSetRenderingAttachmentLocations pvkCmdSetRenderingAttachmentLocations = nullptr;
    PFN_vkCmdSetRenderingAttachmentLocationsKHR pvkCmdSetRenderingAttachmentLocationsKHR = nullptr;
    PFN_vkCmdSetRenderingInputAttachmentIndices pvkCmdSetRenderingInputAttachmentIndices = nullptr;
    PFN_vkCmdSetRenderingInputAttachmentIndicesKHR pvkCmdSetRenderingInputAttachmentIndicesKHR = nullptr;
    PFN_vkCmdSetDepthClampRangeEXT pvkCmdSetDepthClampRangeEXT = nullptr;
    PFN_vkGetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV pvkGetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV = nullptr;
    PFN_vkGetPhysicalDeviceCooperativeVectorPropertiesNV pvkGetPhysicalDeviceCooperativeVectorPropertiesNV = nullptr;
    PFN_vkConvertCooperativeVectorMatrixNV pvkConvertCooperativeVectorMatrixNV = nullptr;
    PFN_vkCmdConvertCooperativeVectorMatrixNV pvkCmdConvertCooperativeVectorMatrixNV = nullptr;
    PFN_vkCmdDispatchTileQCOM pvkCmdDispatchTileQCOM = nullptr;
    PFN_vkCmdBeginPerTileExecutionQCOM pvkCmdBeginPerTileExecutionQCOM = nullptr;
    PFN_vkCmdEndPerTileExecutionQCOM pvkCmdEndPerTileExecutionQCOM = nullptr;
    PFN_vkCreateExternalComputeQueueNV pvkCreateExternalComputeQueueNV = nullptr;
    PFN_vkDestroyExternalComputeQueueNV pvkDestroyExternalComputeQueueNV = nullptr;
    PFN_vkGetExternalComputeQueueDataNV pvkGetExternalComputeQueueDataNV = nullptr;
    PFN_vkEnumeratePhysicalDeviceQueueFamilyPerformanceCountersByRegionARM pvkEnumeratePhysicalDeviceQueueFamilyPerformanceCountersByRegionARM = nullptr;
    std::unordered_map<BString, U32> functionAddressByName;
    std::unordered_map<U32, void*> rayTracingCaptureReplayShaderGroupHandles;
    std::unordered_map<U64, MarshalCallbackData*> debugReportCallbacks;
    std::unordered_map<U64, MarshalCallbackData*> debugUtilsCallbacks;
    std::unordered_map<U64, std::shared_ptr<MarshalVkDescriptorUpdateTemplateCreateInfo>> descriptorUpdateTemplateCreateInfo;
    std::unordered_map<U64, std::shared_ptr<MarshalVkImageCreateInfo>> imageCreateInfo;
    VkDebugUtilsMessengerEXT debugMessenger = VK_NULL_HANDLE;
};
#endif
