#define CreateInstance 1
#define DestroyInstance 2
#define EnumeratePhysicalDevices 3
#define GetDeviceProcAddr 4
#define GetInstanceProcAddr 5
#define GetPhysicalDeviceProperties 6
#define GetPhysicalDeviceQueueFamilyProperties 7
#define GetPhysicalDeviceMemoryProperties 8
#define GetPhysicalDeviceFeatures 9
#define GetPhysicalDeviceFormatProperties 10
#define GetPhysicalDeviceImageFormatProperties 11
#define CreateDevice 12
#define DestroyDevice 13
#define EnumerateInstanceVersion 14
#define EnumerateInstanceLayerProperties 15
#define EnumerateInstanceExtensionProperties 16
#define EnumerateDeviceLayerProperties 17
#define EnumerateDeviceExtensionProperties 18
#define GetDeviceQueue 19
#define QueueSubmit 20
#define QueueWaitIdle 21
#define DeviceWaitIdle 22
#define AllocateMemory 23
#define FreeMemory 24
#define MapMemory 25
#define UnmapMemory 26
#define FlushMappedMemoryRanges 27
#define InvalidateMappedMemoryRanges 28
#define GetDeviceMemoryCommitment 29
#define GetBufferMemoryRequirements 30
#define BindBufferMemory 31
#define GetImageMemoryRequirements 32
#define BindImageMemory 33
#define GetImageSparseMemoryRequirements 34
#define GetPhysicalDeviceSparseImageFormatProperties 35
#define QueueBindSparse 36
#define CreateFence 37
#define DestroyFence 38
#define ResetFences 39
#define GetFenceStatus 40
#define WaitForFences 41
#define CreateSemaphore 42
#define DestroySemaphore 43
#define CreateEvent 44
#define DestroyEvent 45
#define GetEventStatus 46
#define SetEvent 47
#define ResetEvent 48
#define CreateQueryPool 49
#define DestroyQueryPool 50
#define GetQueryPoolResults 51
#define ResetQueryPool 52
#define CreateBuffer 53
#define DestroyBuffer 54
#define CreateBufferView 55
#define DestroyBufferView 56
#define CreateImage 57
#define DestroyImage 58
#define GetImageSubresourceLayout 59
#define CreateImageView 60
#define DestroyImageView 61
#define CreateShaderModule 62
#define DestroyShaderModule 63
#define CreatePipelineCache 64
#define DestroyPipelineCache 65
#define GetPipelineCacheData 66
#define MergePipelineCaches 67
#define CreateGraphicsPipelines 68
#define CreateComputePipelines 69
#define GetSubpassShadingMaxWorkgroupSizeHUAWEI 70
#define DestroyPipeline 71
#define CreatePipelineLayout 72
#define DestroyPipelineLayout 73
#define CreateSampler 74
#define DestroySampler 75
#define CreateDescriptorSetLayout 76
#define DestroyDescriptorSetLayout 77
#define CreateDescriptorPool 78
#define DestroyDescriptorPool 79
#define ResetDescriptorPool 80
#define AllocateDescriptorSets 81
#define FreeDescriptorSets 82
#define UpdateDescriptorSets 83
#define CreateFramebuffer 84
#define DestroyFramebuffer 85
#define CreateRenderPass 86
#define DestroyRenderPass 87
#define GetRenderAreaGranularity 88
#define CreateCommandPool 89
#define DestroyCommandPool 90
#define ResetCommandPool 91
#define AllocateCommandBuffers 92
#define FreeCommandBuffers 93
#define BeginCommandBuffer 94
#define EndCommandBuffer 95
#define ResetCommandBuffer 96
#define CmdBindPipeline 97
#define CmdSetViewport 98
#define CmdSetScissor 99
#define CmdSetLineWidth 100
#define CmdSetDepthBias 101
#define CmdSetBlendConstants 102
#define CmdSetDepthBounds 103
#define CmdSetStencilCompareMask 104
#define CmdSetStencilWriteMask 105
#define CmdSetStencilReference 106
#define CmdBindDescriptorSets 107
#define CmdBindIndexBuffer 108
#define CmdBindVertexBuffers 109
#define CmdDraw 110
#define CmdDrawIndexed 111
#define CmdDrawMultiEXT 112
#define CmdDrawMultiIndexedEXT 113
#define CmdDrawIndirect 114
#define CmdDrawIndexedIndirect 115
#define CmdDispatch 116
#define CmdDispatchIndirect 117
#define CmdSubpassShadingHUAWEI 118
#define CmdCopyBuffer 119
#define CmdCopyImage 120
#define CmdBlitImage 121
#define CmdCopyBufferToImage 122
#define CmdCopyImageToBuffer 123
#define CmdUpdateBuffer 124
#define CmdFillBuffer 125
#define CmdClearColorImage 126
#define CmdClearDepthStencilImage 127
#define CmdClearAttachments 128
#define CmdResolveImage 129
#define CmdSetEvent 130
#define CmdResetEvent 131
#define CmdWaitEvents 132
#define CmdPipelineBarrier 133
#define CmdBeginQuery 134
#define CmdEndQuery 135
#define CmdBeginConditionalRenderingEXT 136
#define CmdEndConditionalRenderingEXT 137
#define CmdResetQueryPool 138
#define CmdWriteTimestamp 139
#define CmdCopyQueryPoolResults 140
#define CmdPushConstants 141
#define CmdBeginRenderPass 142
#define CmdNextSubpass 143
#define CmdEndRenderPass 144
#define CmdExecuteCommands 145
#define CreateAndroidSurfaceKHR 146
#define GetPhysicalDeviceDisplayPropertiesKHR 147
#define GetPhysicalDeviceDisplayPlanePropertiesKHR 148
#define GetDisplayPlaneSupportedDisplaysKHR 149
#define GetDisplayModePropertiesKHR 150
#define CreateDisplayModeKHR 151
#define GetDisplayPlaneCapabilitiesKHR 152
#define CreateDisplayPlaneSurfaceKHR 153
#define CreateSharedSwapchainsKHR 154
#define DestroySurfaceKHR 155
#define GetPhysicalDeviceSurfaceSupportKHR 156
#define GetPhysicalDeviceSurfaceCapabilitiesKHR 157
#define GetPhysicalDeviceSurfaceFormatsKHR 158
#define GetPhysicalDeviceSurfacePresentModesKHR 159
#define CreateSwapchainKHR 160
#define DestroySwapchainKHR 161
#define GetSwapchainImagesKHR 162
#define AcquireNextImageKHR 163
#define QueuePresentKHR 164
#define CreateViSurfaceNN 165
#define CreateWaylandSurfaceKHR 166
#define GetPhysicalDeviceWaylandPresentationSupportKHR 167
#define CreateWin32SurfaceKHR 168
#define GetPhysicalDeviceWin32PresentationSupportKHR 169
#define CreateXlibSurfaceKHR 170
#define GetPhysicalDeviceXlibPresentationSupportKHR 171
#define CreateXcbSurfaceKHR 172
#define GetPhysicalDeviceXcbPresentationSupportKHR 173
#define CreateDirectFBSurfaceEXT 174
#define GetPhysicalDeviceDirectFBPresentationSupportEXT 175
#define CreateImagePipeSurfaceFUCHSIA 176
#define CreateStreamDescriptorSurfaceGGP 177
#define CreateScreenSurfaceQNX 178
#define GetPhysicalDeviceScreenPresentationSupportQNX 179
#define CreateDebugReportCallbackEXT 180
#define DestroyDebugReportCallbackEXT 181
#define DebugReportMessageEXT 182
#define DebugMarkerSetObjectNameEXT 183
#define DebugMarkerSetObjectTagEXT 184
#define CmdDebugMarkerBeginEXT 185
#define CmdDebugMarkerEndEXT 186
#define CmdDebugMarkerInsertEXT 187
#define GetPhysicalDeviceExternalImageFormatPropertiesNV 188
#define GetMemoryWin32HandleNV 189
#define CmdExecuteGeneratedCommandsNV 190
#define CmdPreprocessGeneratedCommandsNV 191
#define CmdBindPipelineShaderGroupNV 192
#define GetGeneratedCommandsMemoryRequirementsNV 193
#define CreateIndirectCommandsLayoutNV 194
#define DestroyIndirectCommandsLayoutNV 195
#define GetPhysicalDeviceFeatures2 196
#define GetPhysicalDeviceProperties2 197
#define GetPhysicalDeviceFormatProperties2 198
#define GetPhysicalDeviceImageFormatProperties2 199
#define GetPhysicalDeviceQueueFamilyProperties2 200
#define GetPhysicalDeviceMemoryProperties2 201
#define GetPhysicalDeviceSparseImageFormatProperties2 202
#define CmdPushDescriptorSetKHR 203
#define TrimCommandPool 204
#define GetPhysicalDeviceExternalBufferProperties 205
#define GetMemoryWin32HandleKHR 206
#define GetMemoryWin32HandlePropertiesKHR 207
#define GetMemoryFdKHR 208
#define GetMemoryFdPropertiesKHR 209
#define GetMemoryZirconHandleFUCHSIA 210
#define GetMemoryZirconHandlePropertiesFUCHSIA 211
#define GetPhysicalDeviceExternalSemaphoreProperties 212
#define GetSemaphoreWin32HandleKHR 213
#define ImportSemaphoreWin32HandleKHR 214
#define GetSemaphoreFdKHR 215
#define ImportSemaphoreFdKHR 216
#define GetSemaphoreZirconHandleFUCHSIA 217
#define ImportSemaphoreZirconHandleFUCHSIA 218
#define GetPhysicalDeviceExternalFenceProperties 219
#define GetFenceWin32HandleKHR 220
#define ImportFenceWin32HandleKHR 221
#define GetFenceFdKHR 222
#define ImportFenceFdKHR 223
#define ReleaseDisplayEXT 224
#define AcquireXlibDisplayEXT 225
#define GetRandROutputDisplayEXT 226
#define AcquireWinrtDisplayNV 227
#define GetWinrtDisplayNV 228
#define DisplayPowerControlEXT 229
#define RegisterDeviceEventEXT 230
#define RegisterDisplayEventEXT 231
#define GetSwapchainCounterEXT 232
#define GetPhysicalDeviceSurfaceCapabilities2EXT 233
#define EnumeratePhysicalDeviceGroups 234
#define GetDeviceGroupPeerMemoryFeatures 235
#define BindBufferMemory2 236
#define BindImageMemory2 237
#define CmdSetDeviceMask 238
#define GetDeviceGroupPresentCapabilitiesKHR 239
#define GetDeviceGroupSurfacePresentModesKHR 240
#define AcquireNextImage2KHR 241
#define CmdDispatchBase 242
#define GetPhysicalDevicePresentRectanglesKHR 243
#define CreateDescriptorUpdateTemplate 244
#define DestroyDescriptorUpdateTemplate 245
#define UpdateDescriptorSetWithTemplate 246
#define CmdPushDescriptorSetWithTemplateKHR 247
#define SetHdrMetadataEXT 248
#define GetSwapchainStatusKHR 249
#define GetRefreshCycleDurationGOOGLE 250
#define GetPastPresentationTimingGOOGLE 251
#define CreateIOSSurfaceMVK 252
#define CreateMacOSSurfaceMVK 253
#define CreateMetalSurfaceEXT 254
#define CmdSetViewportWScalingNV 255
#define CmdSetDiscardRectangleEXT 256
#define CmdSetSampleLocationsEXT 257
#define GetPhysicalDeviceMultisamplePropertiesEXT 258
#define GetPhysicalDeviceSurfaceCapabilities2KHR 259
#define GetPhysicalDeviceSurfaceFormats2KHR 260
#define GetPhysicalDeviceDisplayProperties2KHR 261
#define GetPhysicalDeviceDisplayPlaneProperties2KHR 262
#define GetDisplayModeProperties2KHR 263
#define GetDisplayPlaneCapabilities2KHR 264
#define GetBufferMemoryRequirements2 265
#define GetImageMemoryRequirements2 266
#define GetImageSparseMemoryRequirements2 267
#define CreateSamplerYcbcrConversion 268
#define DestroySamplerYcbcrConversion 269
#define GetDeviceQueue2 270
#define CreateValidationCacheEXT 271
#define DestroyValidationCacheEXT 272
#define GetValidationCacheDataEXT 273
#define MergeValidationCachesEXT 274
#define GetDescriptorSetLayoutSupport 275
#define GetSwapchainGrallocUsageANDROID 276
#define GetSwapchainGrallocUsage2ANDROID 277
#define AcquireImageANDROID 278
#define QueueSignalReleaseImageANDROID 279
#define GetShaderInfoAMD 280
#define SetLocalDimmingAMD 281
#define GetPhysicalDeviceCalibrateableTimeDomainsEXT 282
#define GetCalibratedTimestampsEXT 283
#define SetDebugUtilsObjectNameEXT 284
#define SetDebugUtilsObjectTagEXT 285
#define QueueBeginDebugUtilsLabelEXT 286
#define QueueEndDebugUtilsLabelEXT 287
#define QueueInsertDebugUtilsLabelEXT 288
#define CmdBeginDebugUtilsLabelEXT 289
#define CmdEndDebugUtilsLabelEXT 290
#define CmdInsertDebugUtilsLabelEXT 291
#define CreateDebugUtilsMessengerEXT 292
#define DestroyDebugUtilsMessengerEXT 293
#define SubmitDebugUtilsMessageEXT 294
#define GetMemoryHostPointerPropertiesEXT 295
#define CmdWriteBufferMarkerAMD 296
#define CreateRenderPass2 297
#define CmdBeginRenderPass2 298
#define CmdNextSubpass2 299
#define CmdEndRenderPass2 300
#define GetSemaphoreCounterValue 301
#define WaitSemaphores 302
#define SignalSemaphore 303
#define GetAndroidHardwareBufferPropertiesANDROID 304
#define GetMemoryAndroidHardwareBufferANDROID 305
#define CmdDrawIndirectCount 306
#define CmdDrawIndexedIndirectCount 307
#define CmdSetCheckpointNV 308
#define GetQueueCheckpointDataNV 309
#define CmdBindTransformFeedbackBuffersEXT 310
#define CmdBeginTransformFeedbackEXT 311
#define CmdEndTransformFeedbackEXT 312
#define CmdBeginQueryIndexedEXT 313
#define CmdEndQueryIndexedEXT 314
#define CmdDrawIndirectByteCountEXT 315
#define CmdSetExclusiveScissorNV 316
#define CmdBindShadingRateImageNV 317
#define CmdSetViewportShadingRatePaletteNV 318
#define CmdSetCoarseSampleOrderNV 319
#define CmdDrawMeshTasksNV 320
#define CmdDrawMeshTasksIndirectNV 321
#define CmdDrawMeshTasksIndirectCountNV 322
#define CompileDeferredNV 323
#define CreateAccelerationStructureNV 324
#define DestroyAccelerationStructureKHR 325
#define DestroyAccelerationStructureNV 326
#define GetAccelerationStructureMemoryRequirementsNV 327
#define BindAccelerationStructureMemoryNV 328
#define CmdCopyAccelerationStructureNV 329
#define CmdCopyAccelerationStructureKHR 330
#define CopyAccelerationStructureKHR 331
#define CmdCopyAccelerationStructureToMemoryKHR 332
#define CopyAccelerationStructureToMemoryKHR 333
#define CmdCopyMemoryToAccelerationStructureKHR 334
#define CopyMemoryToAccelerationStructureKHR 335
#define CmdWriteAccelerationStructuresPropertiesKHR 336
#define CmdWriteAccelerationStructuresPropertiesNV 337
#define CmdBuildAccelerationStructureNV 338
#define WriteAccelerationStructuresPropertiesKHR 339
#define CmdTraceRaysKHR 340
#define CmdTraceRaysNV 341
#define GetRayTracingShaderGroupHandlesKHR 342
#define GetRayTracingCaptureReplayShaderGroupHandlesKHR 343
#define GetAccelerationStructureHandleNV 344
#define CreateRayTracingPipelinesNV 345
#define CreateRayTracingPipelinesKHR 346
#define GetPhysicalDeviceCooperativeMatrixPropertiesNV 347
#define CmdTraceRaysIndirectKHR 348
#define GetDeviceAccelerationStructureCompatibilityKHR 349
#define GetRayTracingShaderGroupStackSizeKHR 350
#define CmdSetRayTracingPipelineStackSizeKHR 351
#define GetImageViewHandleNVX 352
#define GetImageViewAddressNVX 353
#define GetPhysicalDeviceSurfacePresentModes2EXT 354
#define GetDeviceGroupSurfacePresentModes2EXT 355
#define AcquireFullScreenExclusiveModeEXT 356
#define ReleaseFullScreenExclusiveModeEXT 357
#define EnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR 358
#define GetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR 359
#define AcquireProfilingLockKHR 360
#define ReleaseProfilingLockKHR 361
#define GetImageDrmFormatModifierPropertiesEXT 362
#define GetBufferOpaqueCaptureAddress 363
#define GetBufferDeviceAddress 364
#define CreateHeadlessSurfaceEXT 365
#define GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV 366
#define InitializePerformanceApiINTEL 367
#define UninitializePerformanceApiINTEL 368
#define CmdSetPerformanceMarkerINTEL 369
#define CmdSetPerformanceStreamMarkerINTEL 370
#define CmdSetPerformanceOverrideINTEL 371
#define AcquirePerformanceConfigurationINTEL 372
#define ReleasePerformanceConfigurationINTEL 373
#define QueueSetPerformanceConfigurationINTEL 374
#define GetPerformanceParameterINTEL 375
#define GetDeviceMemoryOpaqueCaptureAddress 376
#define GetPipelineExecutablePropertiesKHR 377
#define GetPipelineExecutableStatisticsKHR 378
#define GetPipelineExecutableInternalRepresentationsKHR 379
#define CmdSetLineStippleEXT 380
#define GetPhysicalDeviceToolPropertiesEXT 381
#define CreateAccelerationStructureKHR 382
#define CmdBuildAccelerationStructuresKHR 383
#define CmdBuildAccelerationStructuresIndirectKHR 384
#define BuildAccelerationStructuresKHR 385
#define GetAccelerationStructureDeviceAddressKHR 386
#define CreateDeferredOperationKHR 387
#define DestroyDeferredOperationKHR 388
#define GetDeferredOperationMaxConcurrencyKHR 389
#define GetDeferredOperationResultKHR 390
#define DeferredOperationJoinKHR 391
#define CmdSetCullModeEXT 392
#define CmdSetFrontFaceEXT 393
#define CmdSetPrimitiveTopologyEXT 394
#define CmdSetViewportWithCountEXT 395
#define CmdSetScissorWithCountEXT 396
#define CmdBindVertexBuffers2EXT 397
#define CmdSetDepthTestEnableEXT 398
#define CmdSetDepthWriteEnableEXT 399
#define CmdSetDepthCompareOpEXT 400
#define CmdSetDepthBoundsTestEnableEXT 401
#define CmdSetStencilTestEnableEXT 402
#define CmdSetStencilOpEXT 403
#define CmdSetPatchControlPointsEXT 404
#define CmdSetRasterizerDiscardEnableEXT 405
#define CmdSetDepthBiasEnableEXT 406
#define CmdSetLogicOpEXT 407
#define CmdSetPrimitiveRestartEnableEXT 408
#define CreatePrivateDataSlotEXT 409
#define DestroyPrivateDataSlotEXT 410
#define SetPrivateDataEXT 411
#define GetPrivateDataEXT 412
#define CmdCopyBuffer2KHR 413
#define CmdCopyImage2KHR 414
#define CmdBlitImage2KHR 415
#define CmdCopyBufferToImage2KHR 416
#define CmdCopyImageToBuffer2KHR 417
#define CmdResolveImage2KHR 418
#define CmdSetFragmentShadingRateKHR 419
#define GetPhysicalDeviceFragmentShadingRatesKHR 420
#define CmdSetFragmentShadingRateEnumNV 421
#define GetAccelerationStructureBuildSizesKHR 422
#define CmdSetVertexInputEXT 423
#define CmdSetColorWriteEnableEXT 424
#define CmdSetEvent2KHR 425
#define CmdResetEvent2KHR 426
#define CmdWaitEvents2KHR 427
#define CmdPipelineBarrier2KHR 428
#define QueueSubmit2KHR 429
#define CmdWriteTimestamp2KHR 430
#define CmdWriteBufferMarker2AMD 431
#define GetQueueCheckpointData2NV 432
#define GetPhysicalDeviceVideoCapabilitiesKHR 433
#define GetPhysicalDeviceVideoFormatPropertiesKHR 434
#define CreateVideoSessionKHR 435
#define DestroyVideoSessionKHR 436
#define CreateVideoSessionParametersKHR 437
#define UpdateVideoSessionParametersKHR 438
#define DestroyVideoSessionParametersKHR 439
#define GetVideoSessionMemoryRequirementsKHR 440
#define BindVideoSessionMemoryKHR 441
#define CmdDecodeVideoKHR 442
#define CmdBeginVideoCodingKHR 443
#define CmdControlVideoCodingKHR 444
#define CmdEndVideoCodingKHR 445
#define CmdEncodeVideoKHR 446
#define CreateCuModuleNVX 447
#define CreateCuFunctionNVX 448
#define DestroyCuModuleNVX 449
#define DestroyCuFunctionNVX 450
#define CmdCuLaunchKernelNVX 451
#define AcquireDrmDisplayEXT 452
#define GetDrmDisplayEXT 453
#define VK_LAST_VALUE 453
