#define CreateInstance 1
#define DestroyInstance 2
#define EnumeratePhysicalDevices 3
#define GetDeviceProcAddr 4
#define GetInstanceProcAddr 5
#define GetPhysicalDeviceProperties 6
#define GetPhysicalDeviceQueueFamilyProperties 7
#define GetPhysicalDeviceMemoryProperties 8
#define GetPhysicalDeviceFeatures 9
#define GetPhysicalDeviceFormatProperties 10
#define GetPhysicalDeviceImageFormatProperties 11
#define CreateDevice 12
#define DestroyDevice 13
#define EnumerateInstanceVersion 14
#define EnumerateInstanceLayerProperties 15
#define EnumerateInstanceExtensionProperties 16
#define EnumerateDeviceLayerProperties 17
#define EnumerateDeviceExtensionProperties 18
#define GetDeviceQueue 19
#define QueueSubmit 20
#define QueueWaitIdle 21
#define DeviceWaitIdle 22
#define AllocateMemory 23
#define FreeMemory 24
#define MapMemory 25
#define UnmapMemory 26
#define FlushMappedMemoryRanges 27
#define InvalidateMappedMemoryRanges 28
#define GetDeviceMemoryCommitment 29
#define GetBufferMemoryRequirements 30
#define BindBufferMemory 31
#define GetImageMemoryRequirements 32
#define BindImageMemory 33
#define GetImageSparseMemoryRequirements 34
#define GetPhysicalDeviceSparseImageFormatProperties 35
#define QueueBindSparse 36
#define CreateFence 37
#define DestroyFence 38
#define ResetFences 39
#define GetFenceStatus 40
#define WaitForFences 41
#define CreateSemaphore 42
#define DestroySemaphore 43
#define CreateEvent 44
#define DestroyEvent 45
#define GetEventStatus 46
#define SetEvent 47
#define ResetEvent 48
#define CreateQueryPool 49
#define DestroyQueryPool 50
#define GetQueryPoolResults 51
#define ResetQueryPool 52
#define ResetQueryPoolEXT 53
#define CreateBuffer 54
#define DestroyBuffer 55
#define CreateBufferView 56
#define DestroyBufferView 57
#define CreateImage 58
#define DestroyImage 59
#define GetImageSubresourceLayout 60
#define CreateImageView 61
#define DestroyImageView 62
#define CreateShaderModule 63
#define DestroyShaderModule 64
#define CreatePipelineCache 65
#define DestroyPipelineCache 66
#define GetPipelineCacheData 67
#define MergePipelineCaches 68
#define CreatePipelineBinariesKHR 69
#define DestroyPipelineBinaryKHR 70
#define GetPipelineKeyKHR 71
#define GetPipelineBinaryDataKHR 72
#define ReleaseCapturedPipelineDataKHR 73
#define CreateGraphicsPipelines 74
#define CreateComputePipelines 75
#define GetDeviceSubpassShadingMaxWorkgroupSizeHUAWEI 76
#define DestroyPipeline 77
#define CreatePipelineLayout 78
#define DestroyPipelineLayout 79
#define CreateSampler 80
#define DestroySampler 81
#define CreateDescriptorSetLayout 82
#define DestroyDescriptorSetLayout 83
#define CreateDescriptorPool 84
#define DestroyDescriptorPool 85
#define ResetDescriptorPool 86
#define AllocateDescriptorSets 87
#define FreeDescriptorSets 88
#define UpdateDescriptorSets 89
#define CreateFramebuffer 90
#define DestroyFramebuffer 91
#define CreateRenderPass 92
#define DestroyRenderPass 93
#define GetRenderAreaGranularity 94
#define GetRenderingAreaGranularity 95
#define GetRenderingAreaGranularityKHR 96
#define CreateCommandPool 97
#define DestroyCommandPool 98
#define ResetCommandPool 99
#define AllocateCommandBuffers 100
#define FreeCommandBuffers 101
#define BeginCommandBuffer 102
#define EndCommandBuffer 103
#define ResetCommandBuffer 104
#define CmdBindPipeline 105
#define CmdSetAttachmentFeedbackLoopEnableEXT 106
#define CmdSetViewport 107
#define CmdSetScissor 108
#define CmdSetLineWidth 109
#define CmdSetDepthBias 110
#define CmdSetBlendConstants 111
#define CmdSetDepthBounds 112
#define CmdSetStencilCompareMask 113
#define CmdSetStencilWriteMask 114
#define CmdSetStencilReference 115
#define CmdBindDescriptorSets 116
#define CmdBindIndexBuffer 117
#define CmdBindVertexBuffers 118
#define CmdDraw 119
#define CmdDrawIndexed 120
#define CmdDrawMultiEXT 121
#define CmdDrawMultiIndexedEXT 122
#define CmdDrawIndirect 123
#define CmdDrawIndexedIndirect 124
#define CmdDispatch 125
#define CmdDispatchIndirect 126
#define CmdSubpassShadingHUAWEI 127
#define CmdDrawClusterHUAWEI 128
#define CmdDrawClusterIndirectHUAWEI 129
#define CmdUpdatePipelineIndirectBufferNV 130
#define CmdCopyBuffer 131
#define CmdCopyImage 132
#define CmdBlitImage 133
#define CmdCopyBufferToImage 134
#define CmdCopyImageToBuffer 135
#define CmdCopyMemoryIndirectNV 136
#define CmdCopyMemoryToImageIndirectNV 137
#define CmdUpdateBuffer 138
#define CmdFillBuffer 139
#define CmdClearColorImage 140
#define CmdClearDepthStencilImage 141
#define CmdClearAttachments 142
#define CmdResolveImage 143
#define CmdSetEvent 144
#define CmdResetEvent 145
#define CmdWaitEvents 146
#define CmdPipelineBarrier 147
#define CmdBeginQuery 148
#define CmdEndQuery 149
#define CmdBeginConditionalRenderingEXT 150
#define CmdEndConditionalRenderingEXT 151
#define CmdResetQueryPool 152
#define CmdWriteTimestamp 153
#define CmdCopyQueryPoolResults 154
#define CmdPushConstants 155
#define CmdBeginRenderPass 156
#define CmdNextSubpass 157
#define CmdEndRenderPass 158
#define CmdExecuteCommands 159
#define CreateSharedSwapchainsKHR 160
#define DestroySurfaceKHR 161
#define GetPhysicalDeviceSurfaceSupportKHR 162
#define GetPhysicalDeviceSurfaceCapabilitiesKHR 163
#define GetPhysicalDeviceSurfaceFormatsKHR 164
#define GetPhysicalDeviceSurfacePresentModesKHR 165
#define CreateSwapchainKHR 166
#define DestroySwapchainKHR 167
#define GetSwapchainImagesKHR 168
#define AcquireNextImageKHR 169
#define QueuePresentKHR 170
#define CreateXlibSurfaceKHR 171
#define GetPhysicalDeviceXlibPresentationSupportKHR 172
#define CreateDebugReportCallbackEXT 173
#define DestroyDebugReportCallbackEXT 174
#define DebugReportMessageEXT 175
#define DebugMarkerSetObjectNameEXT 176
#define DebugMarkerSetObjectTagEXT 177
#define CmdDebugMarkerBeginEXT 178
#define CmdDebugMarkerEndEXT 179
#define CmdDebugMarkerInsertEXT 180
#define CmdExecuteGeneratedCommandsNV 181
#define CmdPreprocessGeneratedCommandsNV 182
#define CmdBindPipelineShaderGroupNV 183
#define GetGeneratedCommandsMemoryRequirementsNV 184
#define CreateIndirectCommandsLayoutNV 185
#define DestroyIndirectCommandsLayoutNV 186
#define CmdExecuteGeneratedCommandsEXT 187
#define CmdPreprocessGeneratedCommandsEXT 188
#define GetGeneratedCommandsMemoryRequirementsEXT 189
#define CreateIndirectCommandsLayoutEXT 190
#define DestroyIndirectCommandsLayoutEXT 191
#define CreateIndirectExecutionSetEXT 192
#define DestroyIndirectExecutionSetEXT 193
#define UpdateIndirectExecutionSetPipelineEXT 194
#define UpdateIndirectExecutionSetShaderEXT 195
#define GetPhysicalDeviceFeatures2 196
#define GetPhysicalDeviceFeatures2KHR 197
#define GetPhysicalDeviceProperties2 198
#define GetPhysicalDeviceProperties2KHR 199
#define GetPhysicalDeviceFormatProperties2 200
#define GetPhysicalDeviceFormatProperties2KHR 201
#define GetPhysicalDeviceImageFormatProperties2 202
#define GetPhysicalDeviceImageFormatProperties2KHR 203
#define GetPhysicalDeviceQueueFamilyProperties2 204
#define GetPhysicalDeviceQueueFamilyProperties2KHR 205
#define GetPhysicalDeviceMemoryProperties2 206
#define GetPhysicalDeviceMemoryProperties2KHR 207
#define GetPhysicalDeviceSparseImageFormatProperties2 208
#define GetPhysicalDeviceSparseImageFormatProperties2KHR 209
#define CmdPushDescriptorSet 210
#define CmdPushDescriptorSetKHR 211
#define TrimCommandPool 212
#define TrimCommandPoolKHR 213
#define GetPhysicalDeviceExternalBufferProperties 214
#define GetPhysicalDeviceExternalBufferPropertiesKHR 215
#define GetPhysicalDeviceExternalSemaphoreProperties 216
#define GetPhysicalDeviceExternalSemaphorePropertiesKHR 217
#define GetPhysicalDeviceExternalFenceProperties 218
#define GetPhysicalDeviceExternalFencePropertiesKHR 219
#define ReleaseDisplayEXT 220
#define DisplayPowerControlEXT 221
#define RegisterDeviceEventEXT 222
#define RegisterDisplayEventEXT 223
#define GetSwapchainCounterEXT 224
#define GetPhysicalDeviceSurfaceCapabilities2EXT 225
#define EnumeratePhysicalDeviceGroups 226
#define EnumeratePhysicalDeviceGroupsKHR 227
#define GetDeviceGroupPeerMemoryFeatures 228
#define GetDeviceGroupPeerMemoryFeaturesKHR 229
#define BindBufferMemory2 230
#define BindBufferMemory2KHR 231
#define BindImageMemory2 232
#define BindImageMemory2KHR 233
#define CmdSetDeviceMask 234
#define CmdSetDeviceMaskKHR 235
#define GetDeviceGroupPresentCapabilitiesKHR 236
#define GetDeviceGroupSurfacePresentModesKHR 237
#define AcquireNextImage2KHR 238
#define CmdDispatchBase 239
#define CmdDispatchBaseKHR 240
#define GetPhysicalDevicePresentRectanglesKHR 241
#define CreateDescriptorUpdateTemplate 242
#define CreateDescriptorUpdateTemplateKHR 243
#define DestroyDescriptorUpdateTemplate 244
#define DestroyDescriptorUpdateTemplateKHR 245
#define UpdateDescriptorSetWithTemplate 246
#define UpdateDescriptorSetWithTemplateKHR 247
#define CmdPushDescriptorSetWithTemplate 248
#define CmdPushDescriptorSetWithTemplateKHR 249
#define SetHdrMetadataEXT 250
#define CmdSetViewportWScalingNV 251
#define CmdSetDiscardRectangleEXT 252
#define CmdSetDiscardRectangleEnableEXT 253
#define CmdSetDiscardRectangleModeEXT 254
#define CmdSetSampleLocationsEXT 255
#define GetPhysicalDeviceMultisamplePropertiesEXT 256
#define GetPhysicalDeviceSurfaceCapabilities2KHR 257
#define GetPhysicalDeviceSurfaceFormats2KHR 258
#define GetPhysicalDeviceDisplayProperties2KHR 259
#define GetPhysicalDeviceDisplayPlaneProperties2KHR 260
#define GetDisplayModeProperties2KHR 261
#define GetDisplayPlaneCapabilities2KHR 262
#define GetBufferMemoryRequirements2 263
#define GetBufferMemoryRequirements2KHR 264
#define GetImageMemoryRequirements2 265
#define GetImageMemoryRequirements2KHR 266
#define GetImageSparseMemoryRequirements2 267
#define GetImageSparseMemoryRequirements2KHR 268
#define GetDeviceBufferMemoryRequirements 269
#define GetDeviceBufferMemoryRequirementsKHR 270
#define GetDeviceImageMemoryRequirements 271
#define GetDeviceImageMemoryRequirementsKHR 272
#define GetDeviceImageSparseMemoryRequirements 273
#define GetDeviceImageSparseMemoryRequirementsKHR 274
#define CreateSamplerYcbcrConversion 275
#define CreateSamplerYcbcrConversionKHR 276
#define DestroySamplerYcbcrConversion 277
#define DestroySamplerYcbcrConversionKHR 278
#define GetDeviceQueue2 279
#define CreateValidationCacheEXT 280
#define DestroyValidationCacheEXT 281
#define GetValidationCacheDataEXT 282
#define MergeValidationCachesEXT 283
#define GetDescriptorSetLayoutSupport 284
#define GetDescriptorSetLayoutSupportKHR 285
#define GetShaderInfoAMD 286
#define GetPhysicalDeviceCalibrateableTimeDomainsKHR 287
#define GetPhysicalDeviceCalibrateableTimeDomainsEXT 288
#define GetCalibratedTimestampsKHR 289
#define GetCalibratedTimestampsEXT 290
#define SetDebugUtilsObjectNameEXT 291
#define SetDebugUtilsObjectTagEXT 292
#define QueueBeginDebugUtilsLabelEXT 293
#define QueueEndDebugUtilsLabelEXT 294
#define QueueInsertDebugUtilsLabelEXT 295
#define CmdBeginDebugUtilsLabelEXT 296
#define CmdEndDebugUtilsLabelEXT 297
#define CmdInsertDebugUtilsLabelEXT 298
#define CreateDebugUtilsMessengerEXT 299
#define DestroyDebugUtilsMessengerEXT 300
#define SubmitDebugUtilsMessageEXT 301
#define GetMemoryHostPointerPropertiesEXT 302
#define CmdWriteBufferMarkerAMD 303
#define CreateRenderPass2 304
#define CreateRenderPass2KHR 305
#define CmdBeginRenderPass2 306
#define CmdBeginRenderPass2KHR 307
#define CmdNextSubpass2 308
#define CmdNextSubpass2KHR 309
#define CmdEndRenderPass2 310
#define CmdEndRenderPass2KHR 311
#define GetSemaphoreCounterValue 312
#define GetSemaphoreCounterValueKHR 313
#define WaitSemaphores 314
#define WaitSemaphoresKHR 315
#define SignalSemaphore 316
#define SignalSemaphoreKHR 317
#define CmdDrawIndirectCount 318
#define CmdDrawIndirectCountKHR 319
#define CmdDrawIndirectCountAMD 320
#define CmdDrawIndexedIndirectCount 321
#define CmdDrawIndexedIndirectCountKHR 322
#define CmdDrawIndexedIndirectCountAMD 323
#define CmdSetCheckpointNV 324
#define GetQueueCheckpointDataNV 325
#define CmdBindTransformFeedbackBuffersEXT 326
#define CmdBeginTransformFeedbackEXT 327
#define CmdEndTransformFeedbackEXT 328
#define CmdBeginQueryIndexedEXT 329
#define CmdEndQueryIndexedEXT 330
#define CmdDrawIndirectByteCountEXT 331
#define CmdSetExclusiveScissorNV 332
#define CmdSetExclusiveScissorEnableNV 333
#define CmdBindShadingRateImageNV 334
#define CmdSetViewportShadingRatePaletteNV 335
#define CmdSetCoarseSampleOrderNV 336
#define CmdDrawMeshTasksNV 337
#define CmdDrawMeshTasksIndirectNV 338
#define CmdDrawMeshTasksIndirectCountNV 339
#define CmdDrawMeshTasksEXT 340
#define CmdDrawMeshTasksIndirectEXT 341
#define CmdDrawMeshTasksIndirectCountEXT 342
#define CompileDeferredNV 343
#define CreateAccelerationStructureNV 344
#define CmdBindInvocationMaskHUAWEI 345
#define DestroyAccelerationStructureKHR 346
#define DestroyAccelerationStructureNV 347
#define GetAccelerationStructureMemoryRequirementsNV 348
#define BindAccelerationStructureMemoryNV 349
#define CmdCopyAccelerationStructureNV 350
#define CmdCopyAccelerationStructureKHR 351
#define CopyAccelerationStructureKHR 352
#define CmdCopyAccelerationStructureToMemoryKHR 353
#define CopyAccelerationStructureToMemoryKHR 354
#define CmdCopyMemoryToAccelerationStructureKHR 355
#define CopyMemoryToAccelerationStructureKHR 356
#define CmdWriteAccelerationStructuresPropertiesKHR 357
#define CmdWriteAccelerationStructuresPropertiesNV 358
#define CmdBuildAccelerationStructureNV 359
#define WriteAccelerationStructuresPropertiesKHR 360
#define CmdTraceRaysKHR 361
#define CmdTraceRaysNV 362
#define GetRayTracingShaderGroupHandlesKHR 363
#define GetRayTracingShaderGroupHandlesNV 364
#define GetRayTracingCaptureReplayShaderGroupHandlesKHR 365
#define GetAccelerationStructureHandleNV 366
#define CreateRayTracingPipelinesNV 367
#define CreateRayTracingPipelinesKHR 368
#define GetPhysicalDeviceCooperativeMatrixPropertiesNV 369
#define CmdTraceRaysIndirectKHR 370
#define CmdTraceRaysIndirect2KHR 371
#define GetDeviceAccelerationStructureCompatibilityKHR 372
#define GetRayTracingShaderGroupStackSizeKHR 373
#define CmdSetRayTracingPipelineStackSizeKHR 374
#define GetImageViewHandleNVX 375
#define GetImageViewHandle64NVX 376
#define GetImageViewAddressNVX 377
#define EnumeratePhysicalDeviceQueueFamilyPerformanceQueryCountersKHR 378
#define GetPhysicalDeviceQueueFamilyPerformanceQueryPassesKHR 379
#define AcquireProfilingLockKHR 380
#define ReleaseProfilingLockKHR 381
#define GetBufferOpaqueCaptureAddress 382
#define GetBufferOpaqueCaptureAddressKHR 383
#define GetBufferDeviceAddress 384
#define GetBufferDeviceAddressKHR 385
#define GetBufferDeviceAddressEXT 386
#define GetPhysicalDeviceSupportedFramebufferMixedSamplesCombinationsNV 387
#define InitializePerformanceApiINTEL 388
#define UninitializePerformanceApiINTEL 389
#define CmdSetPerformanceMarkerINTEL 390
#define CmdSetPerformanceStreamMarkerINTEL 391
#define CmdSetPerformanceOverrideINTEL 392
#define AcquirePerformanceConfigurationINTEL 393
#define ReleasePerformanceConfigurationINTEL 394
#define QueueSetPerformanceConfigurationINTEL 395
#define GetPerformanceParameterINTEL 396
#define GetDeviceMemoryOpaqueCaptureAddress 397
#define GetDeviceMemoryOpaqueCaptureAddressKHR 398
#define GetPipelineExecutablePropertiesKHR 399
#define GetPipelineExecutableStatisticsKHR 400
#define GetPipelineExecutableInternalRepresentationsKHR 401
#define CmdSetLineStipple 402
#define CmdSetLineStippleKHR 403
#define CmdSetLineStippleEXT 404
#define GetPhysicalDeviceToolProperties 405
#define GetPhysicalDeviceToolPropertiesEXT 406
#define CreateAccelerationStructureKHR 407
#define CmdBuildAccelerationStructuresKHR 408
#define CmdBuildAccelerationStructuresIndirectKHR 409
#define BuildAccelerationStructuresKHR 410
#define GetAccelerationStructureDeviceAddressKHR 411
#define CreateDeferredOperationKHR 412
#define DestroyDeferredOperationKHR 413
#define GetDeferredOperationMaxConcurrencyKHR 414
#define GetDeferredOperationResultKHR 415
#define DeferredOperationJoinKHR 416
#define GetPipelineIndirectMemoryRequirementsNV 417
#define GetPipelineIndirectDeviceAddressNV 418
#define AntiLagUpdateAMD 419
#define CmdSetCullMode 420
#define CmdSetCullModeEXT 421
#define CmdSetFrontFace 422
#define CmdSetFrontFaceEXT 423
#define CmdSetPrimitiveTopology 424
#define CmdSetPrimitiveTopologyEXT 425
#define CmdSetViewportWithCount 426
#define CmdSetViewportWithCountEXT 427
#define CmdSetScissorWithCount 428
#define CmdSetScissorWithCountEXT 429
#define CmdBindIndexBuffer2 430
#define CmdBindIndexBuffer2KHR 431
#define CmdBindVertexBuffers2 432
#define CmdBindVertexBuffers2EXT 433
#define CmdSetDepthTestEnable 434
#define CmdSetDepthTestEnableEXT 435
#define CmdSetDepthWriteEnable 436
#define CmdSetDepthWriteEnableEXT 437
#define CmdSetDepthCompareOp 438
#define CmdSetDepthCompareOpEXT 439
#define CmdSetDepthBoundsTestEnable 440
#define CmdSetDepthBoundsTestEnableEXT 441
#define CmdSetStencilTestEnable 442
#define CmdSetStencilTestEnableEXT 443
#define CmdSetStencilOp 444
#define CmdSetStencilOpEXT 445
#define CmdSetPatchControlPointsEXT 446
#define CmdSetRasterizerDiscardEnable 447
#define CmdSetRasterizerDiscardEnableEXT 448
#define CmdSetDepthBiasEnable 449
#define CmdSetDepthBiasEnableEXT 450
#define CmdSetLogicOpEXT 451
#define CmdSetPrimitiveRestartEnable 452
#define CmdSetPrimitiveRestartEnableEXT 453
#define CmdSetTessellationDomainOriginEXT 454
#define CmdSetDepthClampEnableEXT 455
#define CmdSetPolygonModeEXT 456
#define CmdSetRasterizationSamplesEXT 457
#define CmdSetSampleMaskEXT 458
#define CmdSetAlphaToCoverageEnableEXT 459
#define CmdSetAlphaToOneEnableEXT 460
#define CmdSetLogicOpEnableEXT 461
#define CmdSetColorBlendEnableEXT 462
#define CmdSetColorBlendEquationEXT 463
#define CmdSetColorWriteMaskEXT 464
#define CmdSetRasterizationStreamEXT 465
#define CmdSetConservativeRasterizationModeEXT 466
#define CmdSetExtraPrimitiveOverestimationSizeEXT 467
#define CmdSetDepthClipEnableEXT 468
#define CmdSetSampleLocationsEnableEXT 469
#define CmdSetColorBlendAdvancedEXT 470
#define CmdSetProvokingVertexModeEXT 471
#define CmdSetLineRasterizationModeEXT 472
#define CmdSetLineStippleEnableEXT 473
#define CmdSetDepthClipNegativeOneToOneEXT 474
#define CmdSetViewportWScalingEnableNV 475
#define CmdSetViewportSwizzleNV 476
#define CmdSetCoverageToColorEnableNV 477
#define CmdSetCoverageToColorLocationNV 478
#define CmdSetCoverageModulationModeNV 479
#define CmdSetCoverageModulationTableEnableNV 480
#define CmdSetCoverageModulationTableNV 481
#define CmdSetShadingRateImageEnableNV 482
#define CmdSetCoverageReductionModeNV 483
#define CmdSetRepresentativeFragmentTestEnableNV 484
#define CreatePrivateDataSlot 485
#define CreatePrivateDataSlotEXT 486
#define DestroyPrivateDataSlot 487
#define DestroyPrivateDataSlotEXT 488
#define SetPrivateData 489
#define SetPrivateDataEXT 490
#define GetPrivateData 491
#define GetPrivateDataEXT 492
#define CmdCopyBuffer2 493
#define CmdCopyBuffer2KHR 494
#define CmdCopyImage2 495
#define CmdCopyImage2KHR 496
#define CmdBlitImage2 497
#define CmdBlitImage2KHR 498
#define CmdCopyBufferToImage2 499
#define CmdCopyBufferToImage2KHR 500
#define CmdCopyImageToBuffer2 501
#define CmdCopyImageToBuffer2KHR 502
#define CmdResolveImage2 503
#define CmdResolveImage2KHR 504
#define CmdSetFragmentShadingRateKHR 505
#define GetPhysicalDeviceFragmentShadingRatesKHR 506
#define CmdSetFragmentShadingRateEnumNV 507
#define GetAccelerationStructureBuildSizesKHR 508
#define CmdSetVertexInputEXT 509
#define CmdSetColorWriteEnableEXT 510
#define CmdSetEvent2 511
#define CmdSetEvent2KHR 512
#define CmdResetEvent2 513
#define CmdResetEvent2KHR 514
#define CmdWaitEvents2 515
#define CmdWaitEvents2KHR 516
#define CmdPipelineBarrier2 517
#define CmdPipelineBarrier2KHR 518
#define QueueSubmit2 519
#define QueueSubmit2KHR 520
#define CmdWriteTimestamp2 521
#define CmdWriteTimestamp2KHR 522
#define CmdWriteBufferMarker2AMD 523
#define GetQueueCheckpointData2NV 524
#define CopyMemoryToImage 525
#define CopyMemoryToImageEXT 526
#define CopyImageToMemory 527
#define CopyImageToMemoryEXT 528
#define CopyImageToImage 529
#define CopyImageToImageEXT 530
#define TransitionImageLayout 531
#define TransitionImageLayoutEXT 532
#define GetPhysicalDeviceVideoCapabilitiesKHR 533
#define GetPhysicalDeviceVideoFormatPropertiesKHR 534
#define GetPhysicalDeviceVideoEncodeQualityLevelPropertiesKHR 535
#define CreateVideoSessionKHR 536
#define DestroyVideoSessionKHR 537
#define CreateVideoSessionParametersKHR 538
#define UpdateVideoSessionParametersKHR 539
#define GetEncodedVideoSessionParametersKHR 540
#define DestroyVideoSessionParametersKHR 541
#define GetVideoSessionMemoryRequirementsKHR 542
#define BindVideoSessionMemoryKHR 543
#define CmdDecodeVideoKHR 544
#define CmdBeginVideoCodingKHR 545
#define CmdControlVideoCodingKHR 546
#define CmdEndVideoCodingKHR 547
#define CmdEncodeVideoKHR 548
#define CmdDecompressMemoryNV 549
#define CmdDecompressMemoryIndirectCountNV 550
#define CreateCuModuleNVX 551
#define CreateCuFunctionNVX 552
#define DestroyCuModuleNVX 553
#define DestroyCuFunctionNVX 554
#define CmdCuLaunchKernelNVX 555
#define GetDescriptorSetLayoutSizeEXT 556
#define GetDescriptorSetLayoutBindingOffsetEXT 557
#define GetDescriptorEXT 558
#define CmdBindDescriptorBuffersEXT 559
#define CmdSetDescriptorBufferOffsetsEXT 560
#define CmdBindDescriptorBufferEmbeddedSamplersEXT 561
#define GetBufferOpaqueCaptureDescriptorDataEXT 562
#define GetImageOpaqueCaptureDescriptorDataEXT 563
#define GetImageViewOpaqueCaptureDescriptorDataEXT 564
#define GetSamplerOpaqueCaptureDescriptorDataEXT 565
#define GetAccelerationStructureOpaqueCaptureDescriptorDataEXT 566
#define SetDeviceMemoryPriorityEXT 567
#define AcquireDrmDisplayEXT 568
#define GetDrmDisplayEXT 569
#define WaitForPresentKHR 570
#define CreateCudaModuleNV 571
#define GetCudaModuleCacheNV 572
#define CreateCudaFunctionNV 573
#define DestroyCudaModuleNV 574
#define DestroyCudaFunctionNV 575
#define CmdCudaLaunchKernelNV 576
#define CmdBeginRendering 577
#define CmdBeginRenderingKHR 578
#define CmdEndRendering 579
#define CmdEndRenderingKHR 580
#define GetDescriptorSetLayoutHostMappingInfoVALVE 581
#define GetDescriptorSetHostMappingVALVE 582
#define CreateMicromapEXT 583
#define CmdBuildMicromapsEXT 584
#define BuildMicromapsEXT 585
#define DestroyMicromapEXT 586
#define CmdCopyMicromapEXT 587
#define CopyMicromapEXT 588
#define CmdCopyMicromapToMemoryEXT 589
#define CopyMicromapToMemoryEXT 590
#define CmdCopyMemoryToMicromapEXT 591
#define CopyMemoryToMicromapEXT 592
#define CmdWriteMicromapsPropertiesEXT 593
#define WriteMicromapsPropertiesEXT 594
#define GetDeviceMicromapCompatibilityEXT 595
#define GetMicromapBuildSizesEXT 596
#define GetShaderModuleIdentifierEXT 597
#define GetShaderModuleCreateInfoIdentifierEXT 598
#define GetImageSubresourceLayout2 599
#define GetImageSubresourceLayout2KHR 600
#define GetImageSubresourceLayout2EXT 601
#define GetPipelinePropertiesEXT 602
#define GetFramebufferTilePropertiesQCOM 603
#define GetDynamicRenderingTilePropertiesQCOM 604
#define GetPhysicalDeviceOpticalFlowImageFormatsNV 605
#define CreateOpticalFlowSessionNV 606
#define DestroyOpticalFlowSessionNV 607
#define BindOpticalFlowSessionImageNV 608
#define CmdOpticalFlowExecuteNV 609
#define GetDeviceFaultInfoEXT 610
#define CmdSetDepthBias2EXT 611
#define ReleaseSwapchainImagesEXT 612
#define GetDeviceImageSubresourceLayout 613
#define GetDeviceImageSubresourceLayoutKHR 614
#define MapMemory2 615
#define MapMemory2KHR 616
#define UnmapMemory2 617
#define UnmapMemory2KHR 618
#define CreateShadersEXT 619
#define DestroyShaderEXT 620
#define GetShaderBinaryDataEXT 621
#define CmdBindShadersEXT 622
#define GetPhysicalDeviceCooperativeMatrixPropertiesKHR 623
#define CmdBindDescriptorSets2 624
#define CmdBindDescriptorSets2KHR 625
#define CmdPushConstants2 626
#define CmdPushConstants2KHR 627
#define CmdPushDescriptorSet2 628
#define CmdPushDescriptorSet2KHR 629
#define CmdPushDescriptorSetWithTemplate2 630
#define CmdPushDescriptorSetWithTemplate2KHR 631
#define CmdSetDescriptorBufferOffsets2EXT 632
#define CmdBindDescriptorBufferEmbeddedSamplers2EXT 633
#define SetLatencySleepModeNV 634
#define LatencySleepNV 635
#define SetLatencyMarkerNV 636
#define GetLatencyTimingsNV 637
#define QueueNotifyOutOfBandNV 638
#define CmdSetRenderingAttachmentLocations 639
#define CmdSetRenderingAttachmentLocationsKHR 640
#define CmdSetRenderingInputAttachmentIndices 641
#define CmdSetRenderingInputAttachmentIndicesKHR 642
#define CmdSetDepthClampRangeEXT 643
#define GetPhysicalDeviceCooperativeMatrixFlexibleDimensionsPropertiesNV 644
#define VK_LAST_VALUE 644
