#ifndef _GL4ES_MAIN_CONFIG_H
#define _GL4ES_MAIN_CONFIG_H

#define SYS_proxy 9999
#define MAX_EVAL_ORDER 30
#define MAX_TEX 16
#define MAX_LIGHT 8
#define MAX_STACK_PROJECTION	16
#define MAX_STACK_TEXTURE	16
#define MAX_STACK_MODELVIEW	64
#define MAX_STACK_COLOR 16
#define MAX_STACK_ARB_MATRIX 8
#define MAX_CLIP_PLANES 6
#define MAX_VATTRIB 32
#define MAX_MAP_SIZE 256
#define MAX_ARB_MATRIX  8
#define MAX_VTX_PROG_ENV_PARAMS 96
#define MAX_VTX_PROG_LOC_PARAMS 96
#define MAX_FRG_PROG_ENV_PARAMS 24
#define MAX_FRG_PROG_LOC_PARAMS 24
#define MAX_DRAW_BUFFERS    16

#endif // _GL4ES_MAIN_CONFIG_H
